// Comprehensive agent data for all suites
import type { LucideIcon } from "lucide-react"
import {
  FileText,
  Target,
  TrendingUp,
  Briefcase,
  Shield,
  RefreshCw,
  CreditCard,
  Phone,
  MessageSquare,
  Users,
  Settings,
  Zap,
  Database,
  Network,
  Headphones,
  Server,
  BarChart3,
  Wrench,
  Calendar,
  CheckCircle,
  Stethoscope,
  ShoppingBag,
  Heart,
  Eye,
  Code,
  Globe,
  BookOpen,
  Building,
  Activity,
  PieChart,
  Lock,
  AlertCircle,
  Plug,
  Search,
  Clipboard,
  Sparkles,
  Lightbulb,
  Rocket,
  TrendingDown,
  LineChart,
  Store,
  DollarSign,
  HelpCircle,
  Telescope,
  Bug,
  Cpu,
  Package,
  Star,
  Mic,
  Mail,
  LayoutGrid,
} from "lucide-react"

export interface Agent {
  id: string
  name: string
  suite: string
  description: string
  detailedDescription?: string
  primaryIntegrations: string[]
  secondaryIntegrations: string[]
  author?: string
  likes?: number
  videoUrl?: string
  problems?: string[]
  benefits?: string[]
  category?: string
}

// Helper function to generate integration icons based on agent ID
export function getIntegrationIcons(agentId: number): Array<{ bg: string; icon?: LucideIcon; label: string; isText?: boolean }> {
  const iconSets: Array<Array<{ bg: string; icon?: LucideIcon; label: string; isText?: boolean }>> = [
    [
      { bg: "bg-orange-500", icon: Target, label: "HS" },
      { bg: "bg-green-500", icon: Headphones, label: "" },
      { bg: "bg-black", icon: Zap, label: "" },
      { bg: "bg-gray-400", label: "+1", isText: true },
    ],
    [
      { bg: "bg-blue-500", icon: FileText, label: "" },
      { bg: "bg-purple-500", icon: Briefcase, label: "" },
      { bg: "bg-red-500", icon: Zap, label: "" },
    ],
    [
      { bg: "bg-orange-500", icon: Target, label: "HS" },
      { bg: "bg-indigo-500", icon: Shield, label: "" },
      { bg: "bg-pink-500", icon: MessageSquare, label: "" },
      { bg: "bg-gray-400", label: "+2", isText: true },
    ],
    [
      { bg: "bg-green-500", icon: TrendingUp, label: "" },
      { bg: "bg-blue-500", icon: BarChart3, label: "" },
      { bg: "bg-purple-500", icon: MessageSquare, label: "" },
    ],
    [
      { bg: "bg-orange-500", icon: Server, label: "" },
      { bg: "bg-teal-500", icon: Users, label: "" },
      { bg: "bg-yellow-500", icon: CreditCard, label: "" },
    ],
    [
      { bg: "bg-blue-500", icon: Server, label: "" },
      { bg: "bg-green-500", icon: Database, label: "" },
      { bg: "bg-purple-500", icon: Network, label: "" },
    ],
    [
      { bg: "bg-orange-500", icon: Target, label: "HS" },
      { bg: "bg-pink-500", icon: TrendingUp, label: "" },
      { bg: "bg-blue-500", icon: BarChart3, label: "" },
    ],
    [
      { bg: "bg-orange-500", icon: Target, label: "HS" },
      { bg: "bg-blue-500", icon: Briefcase, label: "" },
      { bg: "bg-green-500", icon: MessageSquare, label: "" },
    ],
    [
      { bg: "bg-indigo-500", icon: Briefcase, label: "" },
      { bg: "bg-blue-500", icon: MessageSquare, label: "" },
      { bg: "bg-green-500", icon: Target, label: "" },
    ],
    [
      { bg: "bg-blue-500", icon: FileText, label: "" },
      { bg: "bg-purple-500", icon: Calendar, label: "" },
      { bg: "bg-green-500", icon: Users, label: "" },
    ],
    [
      { bg: "bg-pink-500", icon: MessageSquare, label: "" },
      { bg: "bg-blue-500", icon: Target, label: "" },
      { bg: "bg-orange-500", icon: TrendingUp, label: "" },
    ],
    [
      { bg: "bg-orange-500", icon: Target, label: "HS" },
      { bg: "bg-blue-500", icon: BarChart3, label: "" },
      { bg: "bg-green-500", icon: MessageSquare, label: "" },
    ],
    [
      { bg: "bg-cyan-500", icon: Phone, label: "" },
      { bg: "bg-blue-500", icon: Headphones, label: "" },
      { bg: "bg-green-500", icon: MessageSquare, label: "" },
    ],
    [
      { bg: "bg-pink-500", icon: MessageSquare, label: "" },
      { bg: "bg-purple-500", icon: Shield, label: "" },
      { bg: "bg-blue-500", icon: Target, label: "" },
    ],
    [
      { bg: "bg-purple-500", icon: Shield, label: "" },
      { bg: "bg-blue-500", icon: Users, label: "" },
      { bg: "bg-green-500", icon: FileText, label: "" },
    ],
    [
      { bg: "bg-green-500", icon: TrendingUp, label: "" },
      { bg: "bg-blue-500", icon: BarChart3, label: "" },
      { bg: "bg-purple-500", icon: MessageSquare, label: "" },
    ],
    [
      { bg: "bg-lime-500", icon: Wrench, label: "" },
      { bg: "bg-blue-500", icon: FileText, label: "" },
      { bg: "bg-green-500", icon: Settings, label: "" },
    ],
    [
      { bg: "bg-blue-500", icon: FileText, label: "" },
      { bg: "bg-purple-500", icon: Wrench, label: "" },
      { bg: "bg-green-500", icon: CheckCircle, label: "" },
    ],
  ]
  return iconSets[agentId % iconSets.length] || iconSets[0]
}

// Sales Suite Agents
const salesSuiteAgents: Agent[] = [
  {
    id: "proposal-reviewer",
    name: "Proposal Reviewer",
    suite: "Sales Suite",
    description: "Ensures proposals follow company style, pricing rules, and legal guidelines for every deal. Improves clarity and persuasion by rewriting sections and highlighting gaps before submission. Enables faster deal closure with professional, consistent messaging.",
    detailedDescription: "The Proposal Reviewer agent ensures that every proposal submitted follows your company's style guidelines, pricing rules, and legal requirements. It automatically reviews proposals for consistency, clarity, and compliance, rewriting sections when necessary to improve persuasion and highlight any gaps that need attention before submission. This agent enables faster deal closure by ensuring all proposals are professional, consistent, and ready for client review.",
    primaryIntegrations: ["Salesforce", "HubSpot", "Gmail/Outlook"],
    secondaryIntegrations: ["Google Drive", "e-signature tools", "SharePoint"],
    author: "Sales Team",
    likes: 145,
    problems: [
      "Proposals often lack consistency in style and messaging across different sales reps",
      "Manual review of proposals is time-consuming and error-prone",
      "Missing compliance checks can lead to legal issues or pricing errors",
      "Inconsistent proposal quality affects win rates and brand perception",
    ],
    benefits: [
      "Ensures 100% compliance with company style and pricing guidelines",
      "Reduces proposal review time by 70% through automated checks",
      "Improves win rates by ensuring professional, consistent messaging",
      "Highlights gaps and missing information before submission",
    ],
  },
  {
    id: "lead-analyzer",
    name: "Lead Analyzer",
    suite: "Sales Suite",
    description: "Ingests inbound leads, enriches them with firmographic and intent data, and scores them in real time. Prioritizes high-value leads and routes them to the right owner or sequence. Accelerates conversion by focusing on qualified prospects.",
    detailedDescription: "The Lead Analyzer agent automatically processes all inbound leads, enriching them with comprehensive firmographic data and intent signals. It scores each lead in real-time based on multiple factors including company size, industry fit, buying signals, and engagement history. The agent then prioritizes high-value leads and routes them to the appropriate sales owner or automated sequence, ensuring your team focuses on the most qualified prospects.",
    primaryIntegrations: ["Salesforce", "HubSpot", "Clearbit/ZoomInfo"],
    secondaryIntegrations: ["Google Sheets", "Slack", "MS Teams"],
    author: "Marketing Team",
    likes: 203,
    problems: [
      "Manual lead qualification is slow and inconsistent",
      "High-value leads get lost in the queue",
      "Lack of lead enrichment leads to poor conversion rates",
      "Inefficient routing causes delays in follow-up",
    ],
    benefits: [
      "Real-time lead scoring and prioritization",
      "Automatic enrichment with firmographic and intent data",
      "Intelligent routing to the right sales rep or sequence",
      "Increases conversion rates by focusing on qualified leads",
    ],
  },
  {
    id: "rfp-response-automation",
    name: "RFP Response Automation",
    suite: "Sales Suite",
    description: "Generates first-draft RFP responses using your content library, past deals, and product docs. Suggests best answers, flags missing information, and tracks sections that need SME review. Reduces manual effort while maintaining quality and accuracy.",
    detailedDescription: "The RFP Response Automation agent transforms the time-consuming process of responding to RFPs. It automatically generates first-draft responses by pulling from your content library, past successful deals, and product documentation. The agent suggests the best answers for each question, flags missing information, and tracks which sections need subject matter expert review. This dramatically reduces manual effort while maintaining high quality and accuracy.",
    primaryIntegrations: ["SharePoint", "Google Drive", "Salesforce"],
    secondaryIntegrations: ["CLM tools", "Gmail/Outlook", "Content management"],
    author: "Sales Operations",
    likes: 178,
    problems: [
      "RFP responses require extensive manual research and writing",
      "Inconsistent answers across different RFPs",
      "Missing critical information leads to disqualification",
      "SME review process is slow and inefficient",
    ],
    benefits: [
      "Generates first-draft responses automatically",
      "Ensures consistency by using approved content library",
      "Flags missing information early in the process",
      "Reduces RFP response time by 60%",
    ],
  },
  {
    id: "deal-desk-assistant",
    name: "Deal Desk Assistant",
    suite: "Sales Suite",
    description: "Guides reps through discount approvals, exceptions, and non-standard terms with policy enforcement. Checks deal data against policy and suggests the fastest compliant approval path. Accelerates deal velocity while maintaining margin discipline.",
    detailedDescription: "The Deal Desk Assistant agent helps sales reps navigate complex deal approvals, discount requests, and non-standard terms. It automatically checks deal data against company policies and suggests the fastest compliant approval path. The agent guides reps through the entire process, ensuring policy enforcement while accelerating deal velocity and maintaining margin discipline.",
    primaryIntegrations: ["CPQ", "Salesforce", "CLM"],
    secondaryIntegrations: ["Slack", "MS Teams", "e-signature tools"],
    author: "Deal Desk Team",
    likes: 192,
    problems: [
      "Deal approvals are slow and require multiple manual checks",
      "Reps don't know the fastest approval path",
      "Policy violations lead to rejected deals",
      "Lack of visibility into approval status",
    ],
    benefits: [
      "Automates policy checks and validation",
      "Suggests fastest compliant approval path",
      "Reduces approval time by 50%",
      "Maintains margin discipline automatically",
    ],
  },
  {
    id: "account-briefing-agent",
    name: "Account Briefing Agent",
    suite: "Sales Suite",
    description: "Summarizes account health, open opportunities, support tickets, and executive news before key meetings. Generates concise briefs and talking points tailored to role and objective. Enables smarter, data-driven customer conversations.",
    detailedDescription: "The Account Briefing Agent automatically prepares comprehensive account briefings before important customer meetings. It summarizes account health metrics, open opportunities, recent support tickets, and relevant executive news. The agent generates concise briefs and talking points tailored to the meeting attendee's role and the meeting's objective, enabling smarter, data-driven customer conversations.",
    primaryIntegrations: ["Salesforce", "Zendesk/Freshdesk", "Calendar"],
    secondaryIntegrations: ["Google News API", "Gmail/Outlook", "Analytics"],
    author: "Account Management",
    likes: 167,
    problems: [
      "Manual account research before meetings is time-consuming",
      "Missing context leads to unprepared conversations",
      "No single source of truth for account information",
      "Briefings are inconsistent across team members",
    ],
    benefits: [
      "Automatically generates comprehensive account briefings",
      "Provides real-time account health and opportunity data",
      "Includes relevant news and support ticket context",
      "Saves 2+ hours per meeting in preparation time",
    ],
  },
  {
    id: "competitive-battlecard-agent",
    name: "Competitive Battlecard Agent",
    suite: "Sales Suite",
    description: "Builds live battlecards from internal win-loss notes, public sources, and product changes. Arms reps with objection handling, pricing comparisons, and feature gaps in real time. Levels the playing field against competitive threats.",
    detailedDescription: "The Competitive Battlecard Agent continuously builds and updates competitive battlecards by aggregating information from internal win-loss notes, public sources, and product changes. It arms sales reps with real-time objection handling strategies, pricing comparisons, and feature gap analysis. This ensures your team is always prepared to handle competitive threats effectively.",
    primaryIntegrations: ["Confluence/Notion", "Google Search API"],
    secondaryIntegrations: ["Salesforce notes", "Slack", "Competitive intelligence tools"],
    author: "Competitive Intelligence",
    likes: 156,
    problems: [
      "Battlecards are outdated and incomplete",
      "Reps lack real-time competitive intelligence",
      "No systematic way to capture win-loss insights",
      "Inconsistent objection handling across the team",
    ],
    benefits: [
      "Automatically builds and updates battlecards",
      "Provides real-time competitive intelligence",
      "Captures win-loss insights systematically",
      "Ensures consistent objection handling",
    ],
  },
  {
    id: "renewal-upsell-advisor",
    name: "Renewal & Upsell Advisor",
    suite: "Sales Suite",
    description: "Monitors contracts, usage, and sentiment to predict renewal risk and upsell potential. Recommends plays, outreach cadences, and tailored value messaging. Protects ARR and identifies expansion revenue early.",
    detailedDescription: "The Renewal & Upsell Advisor agent continuously monitors customer contracts, usage patterns, and sentiment signals to predict renewal risk and identify upsell opportunities. It recommends specific plays, outreach cadences, and tailored value messaging for each account. This proactive approach protects ARR and identifies expansion revenue opportunities early.",
    primaryIntegrations: ["Salesforce", "Stripe/Chargebee", "Analytics"],
    secondaryIntegrations: ["CS tools", "Email", "Product data"],
    author: "Customer Success",
    likes: 189,
    problems: [
      "Renewal risk goes undetected until it's too late",
      "Upsell opportunities are missed",
      "No systematic approach to renewal management",
      "Lack of visibility into usage and sentiment",
    ],
    benefits: [
      "Predicts renewal risk with high accuracy",
      "Identifies upsell opportunities early",
      "Recommends tailored renewal and expansion plays",
      "Protects ARR and increases expansion revenue",
    ],
  },
  {
    id: "sales-email-drafter",
    name: "Sales Email Drafter",
    suite: "Sales Suite",
    description: "Drafts personalized outreach, follow-ups, and recap emails using CRM and call notes. Optimizes tone, length, and CTAs for each segment and objective. Speeds up rep productivity and improves response rates.",
    detailedDescription: "The Sales Email Drafter agent automatically drafts personalized sales emails including outreach, follow-ups, and meeting recaps. It uses CRM data and call notes to personalize each message, optimizing tone, length, and CTAs based on the recipient's segment and the email's objective. This dramatically speeds up rep productivity while improving email response rates.",
    primaryIntegrations: ["Salesforce", "Outreach/Salesloft", "Gmail"],
    secondaryIntegrations: ["Outlook", "Calendly", "Engagement tracking"],
    author: "Sales Enablement",
    likes: 234,
    problems: [
      "Writing personalized emails is time-consuming",
      "Inconsistent email quality across reps",
      "Low response rates due to generic messaging",
      "No optimization based on recipient or objective",
    ],
    benefits: [
      "Drafts personalized emails automatically",
      "Optimizes tone and CTAs for each segment",
      "Improves response rates by 40%",
      "Saves 5+ hours per week per rep",
    ],
  },
  {
    id: "lead-routing-orchestrator",
    name: "Lead Routing Orchestrator",
    suite: "Sales Suite",
    description: "Assigns leads based on territory, industry, capacity, and product line rules with conflict resolution. Explains every routing decision transparently. Maximizes lead coverage and minimizes dropped opportunities.",
    detailedDescription: "The Lead Routing Orchestrator agent intelligently assigns leads to the right sales rep based on territory, industry expertise, current capacity, and product line specialization. It includes conflict resolution logic and provides transparent explanations for every routing decision. This ensures maximum lead coverage and minimizes dropped opportunities.",
    primaryIntegrations: ["CRM (Salesforce/HubSpot)", "Marketing automation"],
    secondaryIntegrations: ["Slack", "MS Teams", "Lead API"],
    author: "Sales Operations",
    likes: 198,
    problems: [
      "Manual lead routing is slow and inconsistent",
      "Leads get assigned to wrong reps",
      "No visibility into routing logic",
      "Dropped leads due to poor routing",
    ],
    benefits: [
      "Automatically routes leads to the right rep",
      "Considers territory, capacity, and expertise",
      "Provides transparent routing explanations",
      "Maximizes lead coverage and conversion",
    ],
  },
  {
    id: "partner-sales-co-pilot",
    name: "Partner Sales Co-Pilot",
    suite: "Sales Suite",
    description: "Supports channel partners with deal registration, enablement content, and guided quoting. Answers FAQs about incentives, processes, and approvals in conversational form. Scales partner productivity without adding headcount.",
    detailedDescription: "The Partner Sales Co-Pilot agent supports your channel partners throughout the sales process. It helps with deal registration, provides access to enablement content, and guides partners through quoting processes. The agent answers frequently asked questions about incentives, processes, and approvals in a conversational format, scaling partner productivity without requiring additional headcount.",
    primaryIntegrations: ["PRM", "Salesforce", "Document management"],
    secondaryIntegrations: ["Partner portals", "Email", "Slack"],
    author: "Channel Team",
    likes: 176,
    problems: [
      "Partners lack self-service access to information",
      "Deal registration process is confusing",
      "Enablement content is hard to find",
      "Partner support requires significant resources",
    ],
    benefits: [
      "Provides 24/7 partner support",
      "Guides partners through deal registration",
      "Makes enablement content easily accessible",
      "Scales partner productivity without adding headcount",
    ],
  },
  {
    id: "ai-sales-sdr",
    name: "AI Sales SDR",
    suite: "Sales Suite",
    description: "Acts as a virtual sales development representative that researches prospects, personalizes outreach, and executes multi-step outbound sequences. Engages leads across email and partner channels while qualifying intent and interest automatically. Helps scale pipeline generation without increasing SDR headcount.",
    detailedDescription: "The AI Sales SDR agent acts as a virtual sales development representative, handling the entire outbound prospecting process. It researches prospects, personalizes outreach messages, and executes multi-step outbound sequences across email and partner channels. The agent automatically qualifies intent and interest, engaging leads until they're ready for handoff to sales. This helps scale pipeline generation without increasing SDR headcount.",
    primaryIntegrations: ["PRM", "Salesforce", "Document management"],
    secondaryIntegrations: ["Partner portals", "Email", "Slack"],
    author: "Sales Development",
    likes: 267,
    problems: [
      "SDR headcount limits pipeline generation",
      "Manual prospecting is time-consuming",
      "Inconsistent outreach quality",
      "Difficulty scaling outbound efforts",
    ],
    benefits: [
      "Acts as a virtual SDR 24/7",
      "Automates research and personalization",
      "Executes multi-step outbound sequences",
      "Scales pipeline without increasing headcount",
    ],
  },
  {
    id: "ai-sales-coach",
    name: "AI Sales Coach",
    suite: "Sales Suite",
    description: "Analyzes sales calls, emails, and deal progress to provide real-time coaching and post-call feedback to reps. Identifies skill gaps, recommends best practices, and suggests next actions tailored to each opportunity. Improves win rates and ramp time through continuous, data-driven coaching.",
    detailedDescription: "The AI Sales Coach agent analyzes sales calls, emails, and deal progress to provide real-time coaching and post-call feedback to sales reps. It identifies skill gaps, recommends best practices, and suggests next actions tailored to each opportunity. The agent provides continuous, data-driven coaching that improves win rates and reduces ramp time for new reps.",
    primaryIntegrations: ["PRM", "Salesforce", "Document management"],
    secondaryIntegrations: ["Partner portals", "Email", "Slack"],
    author: "Sales Enablement",
    likes: 245,
    problems: [
      "Limited coaching resources for sales reps",
      "Inconsistent feedback and development",
      "Skill gaps go undetected",
      "Long ramp time for new reps",
    ],
    benefits: [
      "Provides real-time coaching and feedback",
      "Identifies skill gaps automatically",
      "Recommends best practices and next actions",
      "Improves win rates and reduces ramp time",
    ],
  },
]

// Continue with all other suites... (Due to length, I'll create a function to generate all agents)
// For brevity, I'll create a comprehensive list with all agents

const allAgentsData = [
  ...salesSuiteAgents,
  // Marketing Suite (10 agents)
  {
    id: "campaign-planner-agent",
    name: "Campaign Planner Agent",
    suite: "Marketing Suite",
    description: "Turns goals and audiences into multi-channel campaign plans with timelines and budgets. Suggests messaging angles and content types for each stage of the funnel. Transforms strategy into executable, cross-channel roadmaps.",
    detailedDescription: "The Campaign Planner Agent transforms high-level marketing goals and target audiences into detailed, multi-channel campaign plans complete with timelines and budgets. It suggests messaging angles and content types for each stage of the funnel, ensuring your strategy becomes an executable, cross-channel roadmap that your team can follow.",
    primaryIntegrations: ["Google Ads", "Meta Ads", "LinkedIn Ads"],
    secondaryIntegrations: ["Google Sheets", "Asana", "Jira", "Marketing automation"],
    author: "Marketing Team",
    likes: 189,
    problems: ["Manual campaign planning is time-consuming", "Inconsistent messaging across channels", "Difficulty aligning strategy with execution", "No systematic approach to campaign planning"],
    benefits: ["Automatically generates multi-channel campaign plans", "Ensures consistent messaging across channels", "Creates executable roadmaps with timelines", "Saves 10+ hours per campaign"],
  },
  {
    id: "content-brief-generator",
    name: "Content Brief Generator",
    suite: "Marketing Suite",
    description: "Converts keyword research and personas into detailed content briefs with SEO alignment. Aligns briefs to SEO and brand guidelines and tracks content status to publish. Streamlines content creation and ensures search visibility.",
    detailedDescription: "The Content Brief Generator agent automatically converts keyword research and persona data into comprehensive content briefs that are aligned with SEO best practices. It ensures all briefs follow your brand guidelines and tracks content status through the publishing workflow, streamlining content creation while ensuring search visibility.",
    primaryIntegrations: ["Google Search Console", "SEMrush/Ahrefs"],
    secondaryIntegrations: ["Docs", "Notion", "Trello", "Analytics"],
    author: "Content Team",
    likes: 167,
    problems: ["Manual brief creation is slow", "Inconsistent SEO alignment", "Briefs don't follow brand guidelines", "No visibility into content status"],
    benefits: ["Generates SEO-optimized content briefs automatically", "Ensures brand guideline compliance", "Tracks content through publishing workflow", "Reduces brief creation time by 75%"],
  },
  {
    id: "social-media-manager",
    name: "Social Media Manager",
    suite: "Marketing Suite",
    description: "Drafts and schedules posts across platforms, re-purposing content into multiple formats. Surfaces comments that need responses and proposes engaging replies. Maintains brand voice and engagement without constant manual effort.",
    detailedDescription: "The Social Media Manager agent drafts and schedules social media posts across all major platforms, automatically re-purposing content into multiple formats. It surfaces comments that need responses and proposes engaging replies that maintain your brand voice. This ensures consistent engagement without requiring constant manual effort.",
    primaryIntegrations: ["X (Twitter)", "LinkedIn", "Meta", "Hootsuite/Buffer"],
    secondaryIntegrations: ["Canva", "DAM", "Analytics", "Scheduling"],
    author: "Social Media Team",
    likes: 234,
    problems: ["Managing multiple platforms is time-consuming", "Inconsistent brand voice", "Comments go unanswered", "Difficulty repurposing content"],
    benefits: ["Drafts and schedules posts automatically", "Maintains consistent brand voice", "Surfaces and responds to comments", "Repurposes content across platforms"],
  },
  {
    id: "brand-sentiment-analyzer",
    name: "Brand Sentiment Analyzer",
    suite: "Marketing Suite",
    description: "Aggregates reviews, social mentions, and survey feedback to score sentiment in real time. Highlights root causes, emerging topics, and segments needing experimentation. Turns customer voice into actionable product and marketing decisions.",
    detailedDescription: "The Brand Sentiment Analyzer agent continuously aggregates reviews, social media mentions, and survey feedback to score brand sentiment in real-time. It highlights root causes of sentiment changes, identifies emerging topics, and flags customer segments that need experimentation. This turns customer voice into actionable insights for product and marketing decisions.",
    primaryIntegrations: ["SurveyMonkey", "App Store/Play reviews"],
    secondaryIntegrations: ["Social APIs", "BI tools", "Alerts"],
    author: "Analytics Team",
    likes: 198,
    problems: ["Manual sentiment analysis is slow", "No real-time visibility", "Difficulty identifying root causes", "Customer feedback goes unaddressed"],
    benefits: ["Real-time sentiment scoring", "Identifies root causes automatically", "Surfaces emerging topics early", "Enables data-driven decisions"],
  },
  {
    id: "event-webinar-concierge",
    name: "Event & Webinar Concierge",
    suite: "Marketing Suite",
    description: "Manages registration, reminders, FAQs, and post-event follow-ups automatically. Syncs attendance and engagement data back to CRM and scoring models. Delivers seamless event experiences and captures lead value.",
    detailedDescription: "The Event & Webinar Concierge agent manages the entire event lifecycle automatically. It handles registration, sends reminders, answers FAQs, and executes post-event follow-ups. The agent syncs attendance and engagement data back to your CRM and lead scoring models, ensuring seamless event experiences while capturing maximum lead value.",
    primaryIntegrations: ["Zoom/Teams", "Eventbrite", "HubSpot/Salesforce"],
    secondaryIntegrations: ["Email", "Calendars", "Analytics", "Messaging"],
    author: "Events Team",
    likes: 176,
    problems: ["Event management is manual and time-consuming", "Poor attendee experience", "Lead data doesn't sync to CRM", "Post-event follow-up is inconsistent"],
    benefits: ["Automates entire event lifecycle", "Improves attendee experience", "Syncs data to CRM automatically", "Ensures consistent follow-up"],
  },
  {
    id: "website-conversion-coach",
    name: "Website Conversion Coach",
    suite: "Marketing Suite",
    description: "Analyzes journeys, drop-offs, and heatmaps to suggest CRO experiments with precision. Drafts copy variants and micro-interactions for key pages and forms. Turns website traffic into sustainable conversion growth.",
    detailedDescription: "The Website Conversion Coach agent analyzes user journeys, identifies drop-off points, and reviews heatmaps to suggest conversion rate optimization experiments with precision. It drafts copy variants and micro-interactions for key pages and forms, helping turn website traffic into sustainable conversion growth.",
    primaryIntegrations: ["Google Analytics", "Hotjar/FullStory"],
    secondaryIntegrations: ["CMS", "A/B testing tools", "Messaging"],
    author: "Growth Team",
    likes: 189,
    problems: ["Manual CRO analysis is slow", "Difficulty identifying optimization opportunities", "No systematic approach to testing", "Low conversion rates"],
    benefits: ["Identifies CRO opportunities automatically", "Suggests precise experiments", "Drafts copy variants and interactions", "Improves conversion rates systematically"],
  },
  {
    id: "survey-nps-orchestrator",
    name: "Survey & NPS Orchestrator",
    suite: "Marketing Suite",
    description: "Designs surveys, distributes them, and summarizes insights by persona and channel. Surfaces verbatim comments with the biggest impact on satisfaction and churn. Drives product decisions from quantified customer feedback.",
    detailedDescription: "The Survey & NPS Orchestrator agent designs surveys, distributes them across channels, and summarizes insights by persona and channel. It surfaces verbatim comments with the biggest impact on satisfaction and churn, driving product decisions from quantified customer feedback.",
    primaryIntegrations: ["SurveyMonkey", "Typeform", "Zendesk/Freshdesk"],
    secondaryIntegrations: ["Slack", "MS Teams", "Analytics"],
    author: "Customer Success",
    likes: 167,
    problems: ["Survey design and distribution is manual", "Difficulty analyzing responses", "No systematic insight extraction", "Feedback doesn't drive decisions"],
    benefits: ["Designs and distributes surveys automatically", "Summarizes insights by persona", "Surfaces high-impact feedback", "Drives data-driven product decisions"],
  },
  {
    id: "product-launch-assistant",
    name: "Product Launch Assistant",
    suite: "Marketing Suite",
    description: "Coordinates cross-team launch plans, checklists, and messaging assets across functions. Tracks dependencies and alerts owners when key milestones slip. Ensures launches stay on track and all teams stay aligned.",
    detailedDescription: "The Product Launch Assistant agent coordinates cross-team launch plans, maintains checklists, and manages messaging assets across all functions. It tracks dependencies and alerts owners when key milestones slip, ensuring launches stay on track and all teams remain aligned throughout the process.",
    primaryIntegrations: ["Jira/Asana", "Docs", "CMS"],
    secondaryIntegrations: ["Slack", "MS Teams", "Email", "Analytics"],
    author: "Product Marketing",
    likes: 198,
    problems: ["Launch coordination is chaotic", "Teams get out of sync", "Missed dependencies cause delays", "No visibility into launch status"],
    benefits: ["Coordinates cross-team launch plans", "Tracks dependencies automatically", "Alerts on milestone slips", "Ensures team alignment"],
  },
  {
    id: "abm-engagement-agent",
    name: "ABM Engagement Agent",
    suite: "Marketing Suite",
    description: "Builds tailored microscripts and sequences for high-value accounts with precision targeting. Continuously updates account intelligence and recommended next actions. Turns account lists into revenue through coordinated plays.",
    detailedDescription: "The ABM Engagement Agent builds tailored microscripts and sequences for high-value accounts with precision targeting. It continuously updates account intelligence and recommends next actions, turning account lists into revenue through coordinated, personalized plays.",
    primaryIntegrations: ["6sense/Terminus", "Salesforce", "Outreach/Salesloft"],
    secondaryIntegrations: ["LinkedIn Ads", "Email", "CRM data"],
    author: "ABM Team",
    likes: 189,
    problems: ["Manual ABM execution is time-consuming", "Difficulty personalizing at scale", "Account intelligence is outdated", "No systematic approach to engagement"],
    benefits: ["Builds tailored sequences automatically", "Updates account intelligence continuously", "Recommends next actions", "Scales ABM execution"],
  },
  {
    id: "seo-health-monitor",
    name: "SEO Health Monitor",
    suite: "Marketing Suite",
    description: "Monitors rankings, crawl issues, and content decay for critical keywords in real time. Triggers tasks to refresh content or fix technical issues automatically. Maintains long-term organic visibility and search authority.",
    detailedDescription: "The SEO Health Monitor agent continuously monitors keyword rankings, identifies crawl issues, and detects content decay for critical keywords in real-time. It automatically triggers tasks to refresh content or fix technical issues, maintaining long-term organic visibility and search authority.",
    primaryIntegrations: ["Google Search Console", "Ahrefs/SEMrush"],
    secondaryIntegrations: ["Jira", "CMS", "Alerting tools"],
    author: "SEO Team",
    likes: 176,
    problems: ["Manual SEO monitoring is time-consuming", "Ranking drops go unnoticed", "Content decay affects visibility", "Technical issues cause ranking losses"],
    benefits: ["Monitors SEO health in real-time", "Identifies issues automatically", "Triggers fixes proactively", "Maintains search visibility"],
  },
  // Customer Service Suite (10 agents)
  {
    id: "omni-channel-support-agent",
    name: "Omni-Channel Support Agent",
    suite: "Customer Service Suite",
    description: "Handles common inquiries across chat, email, voice, and messaging with consistent context. Resolves issues with connected systems and escalates seamlessly to live agents when needed. Delivers 24/7 support without overwhelming your team.",
    detailedDescription: "The Omni-Channel Support Agent provides seamless customer support across all channels including chat, email, voice, and messaging platforms. It maintains consistent context across interactions, resolves common issues using connected systems, and seamlessly escalates complex cases to live agents when needed. This delivers 24/7 support coverage without overwhelming your support team.",
    primaryIntegrations: ["Zendesk", "Freshdesk", "Salesforce Service"],
    secondaryIntegrations: ["WhatsApp", "IVR", "Messaging", "CRM"],
    author: "Support Team",
    likes: 234,
    problems: ["Support across multiple channels is fragmented", "Inconsistent context across channels", "High support volume overwhelms team", "Difficulty maintaining 24/7 coverage"],
    benefits: ["Unified support across all channels", "Maintains consistent context", "Reduces support volume by 60%", "Enables 24/7 coverage"],
  },
  {
    id: "ticket-triage-routing",
    name: "Ticket Triage & Routing",
    suite: "Customer Service Suite",
    description: "Reads new tickets, predicts topic and priority, and routes to the right queue instantly. Suggests templates and knowledge articles to speed resolution. Reduces first-response time and improves SLA adherence.",
    detailedDescription: "The Ticket Triage & Routing agent automatically reads incoming support tickets, predicts their topic and priority level, and routes them to the appropriate queue instantly. It suggests relevant response templates and knowledge base articles to speed resolution, significantly reducing first-response time and improving SLA adherence.",
    primaryIntegrations: ["Zendesk", "ServiceNow", "Freshdesk"],
    secondaryIntegrations: ["Jira Service Management", "AI routing"],
    author: "Support Operations",
    likes: 198,
    problems: ["Manual ticket routing is slow", "Tickets go to wrong queues", "No template suggestions", "Poor SLA adherence"],
    benefits: ["Instant intelligent routing", "Predicts priority automatically", "Suggests templates and articles", "Improves SLA adherence"],
  },
  {
    id: "order-status-returns-agent",
    name: "Order Status & Returns Agent",
    suite: "Customer Service Suite",
    description: "Lets customers track orders, request returns, and print labels conversationally. Applies policy rules and provides proactive updates throughout the journey. Reduces returns-related support volume by 60%+.",
    detailedDescription: "The Order Status & Returns Agent enables customers to track orders, request returns, and print return labels through natural conversation. It automatically applies policy rules and provides proactive updates throughout the order and return journey, reducing returns-related support volume by over 60%.",
    primaryIntegrations: ["Shopify", "BigCommerce", "Logistics APIs"],
    secondaryIntegrations: ["Zendesk", "Email", "SMS", "Notifications"],
    author: "E-commerce Team",
    likes: 267,
    problems: ["High volume of order status inquiries", "Returns process is confusing", "Manual label generation", "No proactive updates"],
    benefits: ["Self-service order tracking", "Automated returns processing", "Proactive status updates", "Reduces support volume by 60%"],
  },
  {
    id: "knowledge-base-curator",
    name: "Knowledge-Base Curator",
    suite: "Customer Service Suite",
    description: "Generates, updates, and de-duplicates knowledge-base articles from resolved tickets automatically. Scores article usefulness and flags content that needs SME review. Builds searchable knowledge faster than manual authoring.",
    detailedDescription: "The Knowledge-Base Curator agent automatically generates new knowledge base articles from resolved support tickets, updates existing articles, and removes duplicates. It scores article usefulness based on usage data and flags content that needs subject matter expert review, building a comprehensive searchable knowledge base faster than manual authoring.",
    primaryIntegrations: ["Zendesk Guide", "Confluence", "Notion"],
    secondaryIntegrations: ["Search tools", "Analytics", "Workflow tools"],
    author: "Knowledge Management",
    likes: 189,
    problems: ["Manual KB authoring is slow", "Articles become outdated", "Duplicate content confuses users", "No visibility into article usefulness"],
    benefits: ["Auto-generates articles from tickets", "Updates content automatically", "Removes duplicates", "Scores article usefulness"],
  },
  {
    id: "warranty-claims-assistant",
    name: "Warranty & Claims Assistant",
    suite: "Customer Service Suite",
    description: "Guides users through warranty checks and claim submission with policy validation. Automatically validates eligibility and collects required evidence in structured form. Accelerates claims processing and reduces disputes.",
    detailedDescription: "The Warranty & Claims Assistant agent guides customers through warranty checks and claim submission processes with automatic policy validation. It validates eligibility automatically and collects required evidence in a structured format, accelerating claims processing while reducing disputes.",
    primaryIntegrations: ["CRM", "Claims systems", "Document upload"],
    secondaryIntegrations: ["Email", "SMS", "Forms", "Policy engines"],
    author: "Claims Team",
    likes: 176,
    problems: ["Claims process is confusing", "Manual eligibility checks", "Missing documentation delays claims", "High dispute rates"],
    benefits: ["Guides customers through process", "Auto-validates eligibility", "Collects evidence automatically", "Reduces disputes"],
  },
  {
    id: "feedback-complaint-resolver",
    name: "Feedback & Complaint Resolver",
    suite: "Customer Service Suite",
    description: "Captures complaints, classifies severity, and suggests empathetic responses automatically. Escalates high-risk cases and tracks resolution SLAs rigorously. Turns complaints into retention opportunities.",
    detailedDescription: "The Feedback & Complaint Resolver agent captures customer complaints, automatically classifies their severity, and suggests empathetic response templates. It escalates high-risk cases immediately and tracks resolution SLAs rigorously, turning complaints into opportunities to retain customers.",
    primaryIntegrations: ["Zendesk", "Survey tools", "Voice of Customer"],
    secondaryIntegrations: ["Slack", "Escalation tools", "Email"],
    author: "Customer Success",
    likes: 198,
    problems: ["Complaints go unaddressed", "No severity classification", "Poor response quality", "High churn from unresolved complaints"],
    benefits: ["Captures and classifies complaints", "Suggests empathetic responses", "Escalates high-risk cases", "Turns complaints into retention"],
  },
  {
    id: "subscription-billing-helper",
    name: "Subscription & Billing Helper",
    suite: "Customer Service Suite",
    description: "Manages plan changes, invoices, payment issues, and refunds with clear explanations. Explains charges and recommends best-fit plans based on usage. Reduces churn by improving billing transparency.",
    detailedDescription: "The Subscription & Billing Helper agent manages all subscription and billing inquiries including plan changes, invoice questions, payment issues, and refund requests. It provides clear explanations of charges and recommends best-fit plans based on usage patterns, reducing churn by improving billing transparency.",
    primaryIntegrations: ["Stripe", "Chargebee", "Recurly"],
    secondaryIntegrations: ["CRM", "Email", "Payment APIs"],
    author: "Billing Team",
    likes: 234,
    problems: ["Billing inquiries are time-consuming", "Unclear charge explanations", "No plan recommendations", "Billing confusion causes churn"],
    benefits: ["Handles all billing inquiries", "Explains charges clearly", "Recommends optimal plans", "Reduces churn"],
  },
  {
    id: "multilingual-support-translator",
    name: "Multilingual Support Translator",
    suite: "Customer Service Suite",
    description: "Translates incoming messages and agent replies while preserving context and tone. Learns terminology specific to your products and regions over time. Expands support reach to global customers effortlessly.",
    detailedDescription: "The Multilingual Support Translator agent automatically translates incoming customer messages and agent replies while preserving context and tone. It learns product-specific terminology and regional variations over time, expanding your support reach to global customers effortlessly.",
    primaryIntegrations: ["Zendesk", "Freshdesk", "Translation APIs"],
    secondaryIntegrations: ["Slack", "MS Teams", "NLP tools"],
    author: "Global Support",
    likes: 189,
    problems: ["Language barriers limit support", "Manual translation is slow", "Context and tone are lost", "No product-specific terminology"],
    benefits: ["Real-time translation", "Preserves context and tone", "Learns product terminology", "Expands global reach"],
  },
  {
    id: "proactive-outage-communicator",
    name: "Proactive Outage Communicator",
    suite: "Customer Service Suite",
    description: "Pushes targeted updates during incidents with FAQs, ETAs, and next steps. Reduces ticket spikes by giving real-time status via preferred channels. Turns crisis moments into trust-building opportunities.",
    detailedDescription: "The Proactive Outage Communicator agent automatically pushes targeted updates to customers during service incidents, including FAQs, ETAs, and next steps. It reduces ticket spikes by providing real-time status updates via customers' preferred channels, turning crisis moments into trust-building opportunities.",
    primaryIntegrations: ["Status page tools", "Incident management", "Email/SMS"],
    secondaryIntegrations: ["Web chat", "Push notifications", "CRM"],
    author: "Incident Management",
    likes: 167,
    problems: ["Outages cause ticket spikes", "No proactive communication", "Customers feel uninformed", "Crisis damages trust"],
    benefits: ["Proactive incident updates", "Reduces ticket spikes", "Keeps customers informed", "Builds trust during crises"],
  },
  {
    id: "community-forum-moderator",
    name: "Community Forum Moderator",
    suite: "Customer Service Suite",
    description: "Auto-tags posts, suggests answers, and flags abuse or spam in community spaces. Promotes helpful replies and routes unresolved threads to support teams. Builds peer-to-peer support and brand advocacy.",
    detailedDescription: "The Community Forum Moderator agent automatically tags posts, suggests answers from the knowledge base, and flags abuse or spam in community forums. It promotes helpful replies and routes unresolved threads to support teams, building peer-to-peer support and brand advocacy.",
    primaryIntegrations: ["Discourse", "Khoros", "Reddit", "Slack communities"],
    secondaryIntegrations: ["Zendesk", "Moderation tools", "Analytics"],
    author: "Community Team",
    likes: 198,
    problems: ["Manual moderation is time-consuming", "Abuse and spam go unchecked", "No answer suggestions", "Unresolved threads frustrate users"],
    benefits: ["Auto-tags and moderates", "Suggests answers", "Flags abuse automatically", "Builds peer support"],
  },
]

// Helper function to generate problems and benefits for agents
function generateAgentDetails(description: string, suite: string): { problems: string[], benefits: string[] } {
  const suiteProblems: Record<string, string[]> = {
    "Sales Suite": [
      "Manual processes slow down sales cycles",
      "Inconsistent execution across team members",
      "Lack of real-time insights and recommendations",
      "Difficulty scaling without adding headcount",
    ],
    "Marketing Suite": [
      "Manual campaign management is time-consuming",
      "Inconsistent messaging across channels",
      "Difficulty measuring and optimizing performance",
      "Limited ability to personalize at scale",
    ],
    "Customer Service Suite": [
      "High support volume overwhelms teams",
      "Inconsistent response quality",
      "Difficulty maintaining 24/7 coverage",
      "Poor customer experience leads to churn",
    ],
    "HR & Talent Suite": [
      "Manual HR processes are slow and error-prone",
      "Inconsistent policy application",
      "Difficulty scaling HR support",
      "Poor employee experience",
    ],
    "IT & Operations Suite": [
      "Manual IT processes create bottlenecks",
      "Difficulty maintaining security and compliance",
      "High ticket volume overwhelms IT teams",
      "Lack of self-service options",
    ],
    "Finance & Banking Suite": [
      "Manual financial processes are slow",
      "Compliance and audit challenges",
      "Difficulty providing self-service options",
      "High error rates in manual processing",
    ],
    "Retail & E-Commerce Suite": [
      "Manual retail operations are inefficient",
      "Difficulty personalizing customer experience",
      "Inventory and order management challenges",
      "Poor customer experience affects sales",
    ],
    "Healthcare Suite": [
      "Manual healthcare processes create delays",
      "Difficulty maintaining compliance",
      "High administrative burden on clinicians",
      "Poor patient experience",
    ],
    "Cross-Industry Analytics Suite": [
      "Manual data analysis is slow",
      "Difficulty extracting insights from data",
      "No real-time visibility",
      "Inconsistent reporting",
    ],
    "Community & Innovation Suite": [
      "Manual innovation processes are slow",
      "Difficulty sharing knowledge",
      "Limited collaboration tools",
      "Difficulty scaling innovation",
    ],
  }

  const suiteBenefits: Record<string, string[]> = {
    "Sales Suite": [
      "Automates repetitive sales tasks",
      "Provides real-time insights and recommendations",
      "Ensures consistent execution",
      "Scales sales operations without adding headcount",
    ],
    "Marketing Suite": [
      "Automates campaign management",
      "Ensures consistent messaging",
      "Provides real-time performance insights",
      "Enables personalization at scale",
    ],
    "Customer Service Suite": [
      "Reduces support volume significantly",
      "Ensures consistent response quality",
      "Enables 24/7 coverage",
      "Improves customer satisfaction",
    ],
    "HR & Talent Suite": [
      "Automates HR processes",
      "Ensures policy compliance",
      "Scales HR support efficiently",
      "Improves employee experience",
    ],
    "IT & Operations Suite": [
      "Automates IT processes",
      "Maintains security and compliance",
      "Reduces ticket volume",
      "Enables self-service",
    ],
    "Finance & Banking Suite": [
      "Automates financial processes",
      "Ensures compliance",
      "Provides self-service options",
      "Reduces errors significantly",
    ],
    "Retail & E-Commerce Suite": [
      "Automates retail operations",
      "Personalizes customer experience",
      "Improves inventory management",
      "Enhances customer satisfaction",
    ],
    "Healthcare Suite": [
      "Automates healthcare processes",
      "Maintains compliance",
      "Reduces administrative burden",
      "Improves patient experience",
    ],
    "Cross-Industry Analytics Suite": [
      "Automates data analysis",
      "Extracts insights automatically",
      "Provides real-time visibility",
      "Ensures consistent reporting",
    ],
    "Community & Innovation Suite": [
      "Accelerates innovation processes",
      "Facilitates knowledge sharing",
      "Enables collaboration",
      "Scales innovation efficiently",
    ],
  }

  return {
    problems: suiteProblems[suite] || [
      "Manual processes are time-consuming and error-prone",
      "Difficulty scaling operations",
      "Inconsistent execution",
      "Poor user experience",
    ],
    benefits: suiteBenefits[suite] || [
      "Automates repetitive tasks",
      "Improves efficiency and accuracy",
      "Ensures consistent execution",
      "Enhances user experience",
    ],
  }
}

// Generate remaining agents programmatically
const generateRemainingAgents = (): Agent[] => {
  const agentTemplates = [
    // HR & Talent Suite (10)
    { name: "Leave & Absence Assistant", suite: "HR & Talent Suite", desc: "Provides policy-aware leave self-service for employees and managers instantly. Checks eligibility, balances, and overlapping shifts before submitting requests. Reduces HR workload while ensuring compliance with policies.", integrations: ["BambooHR", "Workday", "UKG"], second: ["Calendars", "Email", "Notifications"] },
    { name: "Payroll & Earnings Explainer", suite: "HR & Talent Suite", desc: "Lets employees retrieve payslips and ask questions like \"What was my total bonus last year?\". Breaks down earnings, deductions, and tax changes in plain language. Improves payroll transparency and reduces HR inquiries.", integrations: ["Payroll systems", "HRIS", "Document vaults"], second: ["Email", "Self-service portals", "Analytics"] },
    { name: "Resume Screener Agent", suite: "HR & Talent Suite", desc: "Reviews resumes against role criteria and diversity goals with consistency and speed. Produces shortlists with rationale and risk flags for hiring managers. Accelerates recruiting while reducing bias in screening.", integrations: ["ATS (Greenhouse, Lever)", "Job boards"], second: ["HRIS", "Analytics", "Sourcing tools"] },
    { name: "Interview Intelligence Agent", suite: "HR & Talent Suite", desc: "Analyzes interview notes and transcripts to summarize strengths and concerns objectively. Recommends next-round decisions and follow-up questions based on role requirements. Improves hiring quality and consistency.", integrations: ["ATS", "Zoom", "Microsoft Teams", "Note-taking apps"], second: ["HRIS", "Interview platforms", "Feedback tools"] },
    { name: "Onboarding Concierge", suite: "HR & Talent Suite", desc: "Guides new hires through paperwork, tools, and training with personalized checklists. Tracks task completion and nudges stakeholders to remove blockers. Ensures smooth first-day experiences and faster time-to-productivity.", integrations: ["HRIS", "LMS", "ITSM", "e-signature tools"], second: ["Calendars", "Email", "Slack", "HR tools"] },
    { name: "Policy Q&A Assistant", suite: "HR & Talent Suite", desc: "Answers questions on benefits, travel, compliance, and company policies 24/7. Escalates ambiguous or sensitive topics to HR partners for human judgment. Reduces HR team burden on routine inquiries.", integrations: ["HRIS", "Document repositories", "Policy databases"], second: ["Slack", "Microsoft Teams", "Email", "Knowledge bases"] },
    { name: "Time & Attendance Helper", suite: "HR & Talent Suite", desc: "Supports shift swaps, overtime requests, and time corrections with real-time validation. Automatically enforces rules, approvals, and union agreements. Streamlines scheduling and reduces manual administration.", integrations: ["Time-tracking systems", "HRIS", "Scheduling tools"], second: ["Messaging apps", "Slack", "Email", "Mobile apps"] },
    { name: "Performance Review Co-Pilot", suite: "HR & Talent Suite", desc: "Helps managers and employees write balanced, data-driven performance reviews. Surfaces goals, feedback, and outcomes from the review period automatically. Improves review quality and reduces manager effort.", integrations: ["Performance management systems", "HRIS", "Feedback platforms"], second: ["Goal-tracking tools", "Analytics", "Email"] },
    { name: "Learning Path Advisor", suite: "HR & Talent Suite", desc: "Recommends courses and learning paths based on role, skills, and career goals. Tracks completion and links learning outcomes to performance metrics. Drives continuous development and employee retention.", integrations: ["LMS", "HRIS", "Skill taxonomies"], second: ["Calendars", "Analytics", "Content libraries"] },
    { name: "HR Case Manager", suite: "HR & Talent Suite", desc: "Centralizes employee relations cases with structured, guided workflows. Maintains documentation, audit trails, and compliance for sensitive issues. Protects the organization while ensuring fair employee treatment.", integrations: ["HR case management tools", "HRIS", "Document management"], second: ["Email", "Case tracking", "Legal and compliance alerts"] },
    // IT & Operations Suite (10)
    { name: "IT Helpdesk Virtual Agent", suite: "IT & Operations Suite", desc: "Transforms IT issue reporting into a conversational experience for employees. Collects diagnostics, suggests quick fixes, and opens tickets when needed. Reduces helpdesk volume while improving user satisfaction.", integrations: ["ServiceNow", "Jira Service Management"], second: ["Intune", "Jamf", "Email", "Mobile apps"] },
    { name: "IT Request Fulfillment Agent", suite: "IT & Operations Suite", desc: "Enables users to request hardware, software, and access through chat instantly. Tracks approvals and provides real-time fulfillment status updates. Accelerates onboarding and reduces approval bottlenecks.", integrations: ["ServiceNow", "Okta", "Azure AD"], second: ["Asset tools", "Slack", "Email", "Approval workflows"] },
    { name: "Password Reset & Unlock Agent", suite: "IT & Operations Suite", desc: "Unlocks accounts and guides secure password resets for enterprise applications. Enforces MFA and security policies automatically. Reduces IT tickets while maintaining strong access controls.", integrations: ["Active Directory", "Okta", "Azure AD"], second: ["Email", "SMS", "MFA platforms", "Security tools"] },
    { name: "Incident Command Assistant", suite: "IT & Operations Suite", desc: "Orchestrates incident response bridges, timelines, and stakeholder updates automatically. Captures post-incident timelines for reviews and learning. Improves communication and speeds resolution during outages.", integrations: ["PagerDuty", "Opsgenie", "Slack", "Microsoft Teams"], second: ["Jira", "Status pages", "Escalation tools"] },
    { name: "Change Request Co-Pilot", suite: "IT & Operations Suite", desc: "Guides engineers in drafting and submitting change requests with built-in policy checks. Evaluates dependencies, risks, and approval requirements automatically. Accelerates change delivery while minimizing risk.", integrations: ["ServiceNow", "Jira", "CMDB"], second: ["GitHub", "GitLab", "Approval workflows", "Email"] },
    { name: "Asset & License Tracker", suite: "IT & Operations Suite", desc: "Tracks hardware and software usage, renewals, and compliance continuously. Identifies underutilized licenses and optimization opportunities. Reduces software spend and improves asset visibility.", integrations: ["ServiceNow", "Intune", "Jamf", "SaaS tools"], second: ["BI tools", "Alerts", "Email", "Analytics"] },
    { name: "Knowledge Search for IT", suite: "IT & Operations Suite", desc: "Allows employees to ask IT questions in natural language across documentation. Returns step-by-step resolutions and related ticket history. Enables self-service and lowers support ticket volume.", integrations: ["Confluence", "SharePoint", "Git repositories"], second: ["Search engines", "Ticketing systems", "Email"] },
    { name: "DevOps Release Assistant", suite: "IT & Operations Suite", desc: "Guides teams through deployment pipelines and release gates with real-time insights. Summarizes build status, test coverage, and rollback options. Speeds up releases while maintaining quality standards.", integrations: ["Jenkins", "GitHub Actions", "Jira"], second: ["Kubernetes", "ChatOps", "Monitoring", "CI/CD tools"] },
    { name: "Access Review Agent", suite: "IT & Operations Suite", desc: "Automates periodic access certifications and exception handling workflows. Maintains audit trails and approver evidence for compliance. Reduces security risk and audit findings.", integrations: ["IGA tools", "Okta", "Azure AD"], second: ["HRIS", "Email", "Ticketing", "Reporting"] },
    { name: "ITSM Analytics Analyst", suite: "IT & Operations Suite", desc: "Analyzes incident, problem, and change data to uncover trends and inefficiencies. Recommends automation opportunities and knowledge gaps proactively. Drives continuous improvement across IT operations.", integrations: ["ServiceNow", "Jira", "BI tools"], second: ["Data warehouses", "Reporting tools", "Analytics"] },
    // Finance & Banking Suite (10)
    { name: "Account Management Assistant", suite: "Finance & Banking Suite", desc: "Supports customers with balance checks, statements, and account updates securely. Guides users through self-service actions across digital channels. Reduces branch visits and call center volume significantly.", integrations: ["Core banking systems", "KYC platforms", "IVR"], second: ["Mobile apps", "Web apps", "SMS", "Email"] },
    { name: "Dispute & Fraud Handler", suite: "Finance & Banking Suite", desc: "Helps users report suspicious transactions and initiate dispute workflows quickly. Collects evidence, explains timelines, and provides transparent case updates. Builds customer trust during fraud incidents.", integrations: ["Core banking systems", "Fraud detection platforms", "Case management tools"], second: ["SMS", "Email", "Document upload", "Messaging platforms"] },
    { name: "ATM & Branch Locator", suite: "Finance & Banking Suite", desc: "Allows customers to find nearby ATMs and branches with hours and services instantly. Supports location-aware suggestions and accessibility filters. Improves convenience and branch utilization.", integrations: ["Maps APIs", "Core banking systems"], second: ["Mobile apps", "Web chat", "Notifications"] },
    { name: "Loan Eligibility & Pre-Qualification Agent", suite: "Finance & Banking Suite", desc: "Evaluates loan eligibility using declared data and credit rules in real time. Generates personalized pre-qualified offers and clear next steps. Accelerates the loan origination pipeline.", integrations: ["Loan origination systems", "Credit bureaus"], second: ["CRM", "Application tools", "Email"] },
    { name: "Investment Profile Generator", suite: "Finance & Banking Suite", desc: "Creates structured profiles of companies and investors using key financial metrics. Summarizes ownership, risk factors, and strategic fit for relationship managers. Speeds up deal evaluation and due diligence.", integrations: ["Market data feeds", "CRM", "Research platforms"], second: ["BI tools", "Document repositories", "Email"] },
    { name: "Client Briefing & Sentiment Agent", suite: "Finance & Banking Suite", desc: "Processes meeting notes, emails, and transcripts to generate client briefings automatically. Adds sentiment and risk cues for relationship managers. Improves account insights and relationship quality.", integrations: ["CRM", "Email", "Calendar", "Call recording tools"], second: ["BI tools", "NLP platforms", "Document tools"] },
    { name: "Expense Management Assistant", suite: "Finance & Banking Suite", desc: "Guides employees through compliant expense submissions and approval flows. Detects policy violations and duplicate claims in real time. Reduces processing time and fraud risk.", integrations: ["SAP Concur", "Expensify", "ERP systems"], second: ["Corporate cards", "Approval workflows", "Email"] },
    { name: "invoice-processing-agent-finance", suite: "Finance & Banking Suite", desc: "Reads invoices, matches them with purchase orders, and flags exceptions automatically. Updates payment status and communicates with vendors seamlessly. Accelerates accounts payable operations.", integrations: ["Accounts payable systems", "OCR", "ERP"], second: ["Email", "Document storage", "Payment tools"] },
    { name: "Treasury & Cash Insight Agent", suite: "Finance & Banking Suite", desc: "Provides real-time summaries of cash positions, forecasts, and liquidity scenarios. Alerts treasury teams to anomalies and threshold breaches. Improves cash optimization and financial planning.", integrations: ["Treasury management platforms", "Bank feeds"], second: ["BI tools", "Data warehouses", "Reporting", "Email"] },
    { name: "Compliance & Policy Checker", suite: "Finance & Banking Suite", desc: "Scans transactions and communications for regulatory and policy violations continuously. Recommends remediation actions and escalates high-risk cases. Reduces compliance breaches and regulatory exposure.", integrations: ["AML systems", "Trade surveillance tools", "Email"], second: ["Case management systems", "Alerts", "Policy databases"] },
    // Retail & E-Commerce Suite (10)
    { name: "Product Search & Discovery Agent", suite: "Retail & E-Commerce Suite", desc: "Enables shoppers to search by name, SKU, model, or description using conversational filters. Supports comparisons and guided discovery journeys. Reduces browsing time and increases purchase intent.", integrations: ["Shopify", "BigCommerce", "PIM", "Search engines"], second: ["Product analytics", "Recommendation engines", "CRM"] },
    { name: "Cart & Checkout Assistant", suite: "Retail & E-Commerce Suite", desc: "Provides a real-time cart experience via chat with add/remove and upsell actions. Answers shipping, billing, and payment questions instantly. Reduces checkout abandonment and recovers lost sales.", integrations: ["Commerce platforms", "Payment gateways"], second: ["Analytics", "Discount engines", "Notifications"] },
    { name: "Order Management Helper", suite: "Retail & E-Commerce Suite", desc: "Helps customers track orders, cancellations, returns, and refunds with live updates. Syncs status across channels to avoid conflicting information. Improves satisfaction and reduces support inquiries.", integrations: ["Shopify", "Logistics APIs", "CRM"], second: ["Support tools", "Notifications", "SMS"] },
    { name: "In-Store Associate Co-Pilot", suite: "Retail & E-Commerce Suite", desc: "Gives store associates instant access to product details, inventory, and policies. Suggests cross-sell and service recommendations per customer scenario. Elevates in-store customer experience.", integrations: ["POS systems", "Inventory systems", "Mobile apps"], second: ["CRM", "Product databases", "Promotions", "Email"] },
    { name: "Pricing & Promotion Advisor", suite: "Retail & E-Commerce Suite", desc: "Analyzes demand elasticity and competitor pricing to suggest optimal promotions. Simulates margin impact before launch. Maximizes revenue while protecting profitability.", integrations: ["POS systems", "Pricing tools", "Competitive data"], second: ["BI tools", "Analytics", "Promotion platforms"] },
    { name: "Returns Intelligence Agent", suite: "Retail & E-Commerce Suite", desc: "Analyzes return reasons to detect quality, sizing, or expectation issues. Recommends policy and product page improvements proactively. Reduces future returns and improves product quality.", integrations: ["Returns platforms", "Commerce systems", "BI tools"], second: ["Survey tools", "Product analytics", "Email"] },
    { name: "Store Operations Helper", suite: "Retail & E-Commerce Suite", desc: "Automates daily checklists, audits, and task assignments for store managers. Highlights compliance gaps and exceptions by location. Ensures consistent operations across stores.", integrations: ["Task management systems", "HR systems", "Mobile apps"], second: ["Analytics", "Alerts", "Reporting", "Slack"] },
    { name: "Loyalty & Rewards Assistant", suite: "Retail & E-Commerce Suite", desc: "Explains loyalty tiers, rewards, and redemptions to customers clearly. Delivers personalized offers to re-engage lapsed members. Increases retention and lifetime value.", integrations: ["Loyalty platforms", "POS systems", "CRM"], second: ["Email", "SMS", "Personalization tools", "Analytics"] },
    { name: "Visual Merchandising Planner", suite: "Retail & E-Commerce Suite", desc: "Recommends planograms and display rotations using performance data. Generates actionable store-level guidelines and tasks. Improves shelf utilization and sales per square foot.", integrations: ["Planogram tools", "POS systems", "Project tools"], second: ["DAM", "Analytics", "Reporting", "Mobile apps"] },
    { name: "Voice Commerce Agent", suite: "Retail & E-Commerce Suite", desc: "Enables voice-based shopping for reorders and frequent purchases. Handles subscriptions, basket building, and checkout via voice. Delivers convenience-first shopping experiences.", integrations: ["Voice platforms", "Commerce systems", "Payment gateways"], second: ["Inventory systems", "CRM", "Analytics", "Notifications"] },
    // Healthcare Suite (11)
    { name: "Patient Access Assistant", suite: "Healthcare Suite", desc: "Supports appointment booking, rescheduling, and automated reminders seamlessly. Collects pre-visit information and verifies eligibility securely before visits. Improves patient access while reducing front-desk administrative load.", integrations: ["EHR systems", "Scheduling systems", "Insurance verification"], second: ["SMS", "Email", "Notifications", "Patient portals"] },
    { name: "Care Navigation Agent", suite: "Healthcare Suite", desc: "Guides patients through care pathways, discharge instructions, and follow-up resources. Detects risk signals and escalates to care coordinators or nurses when required. Reduces readmissions and improves long-term outcomes.", integrations: ["EHR systems", "Care management platforms", "Telehealth"], second: ["Messaging", "Alerts", "Resource databases", "Email"] },
    { name: "Benefits & Coverage Explainer", suite: "Healthcare Suite", desc: "Answers patient questions about coverage, co-pays, and authorization requirements. Provides out-of-pocket cost estimates for common procedures. Reduces billing confusion and improves financial transparency.", integrations: ["Payer systems", "Eligibility APIs"], second: ["Patient portals", "Email", "SMS", "Cost calculators"] },
    { name: "Provider Support Co-Pilot", suite: "Healthcare Suite", desc: "Helps clinicians quickly access protocols, order sets, and reference content. Summarizes patient history and highlights risks before encounters. Improves care quality while reducing clinician burnout.", integrations: ["EHR systems", "Knowledge bases", "Dictation tools"], second: ["Clinical guidelines DB", "Analytics", "Mobile apps"] },
    { name: "Clinical Documentation Assistant", suite: "Healthcare Suite", desc: "Converts notes and transcripts into structured, coded clinical documentation. Flags missing elements needed for billing and quality reporting. Improves coding accuracy and reduces revenue leakage.", integrations: ["EHR systems", "Dictation tools", "Coding platforms"], second: ["NLP engines", "RCM tools", "Compliance systems", "Email"] },
    { name: "Prior Authorization Orchestrator", suite: "Healthcare Suite", desc: "Collects required documentation and submits prior authorization requests automatically. Tracks approvals and updates clinics and patients in real time. Accelerates care delivery and reduces admin burden.", integrations: ["Payer portals", "EHR systems", "Fax/Email gateways"], second: ["Approval workflows", "Email", "SMS", "Patient portals"] },
    { name: "Population Health Insight Agent", suite: "Healthcare Suite", desc: "Identifies high-risk cohorts and care gaps needing proactive outreach. Generates prioritized patient lists and engagement scripts. Improves quality scores while reducing preventable costs.", integrations: ["Population health platforms", "EHR systems"], second: ["Analytics tools", "Outreach platforms", "Reporting", "Mobile apps"] },
    { name: "Clinical Trial Matchmaker", suite: "Healthcare Suite", desc: "Matches eligible patients to clinical trials using medical history and criteria. Generates pre-screening summaries for research teams. Accelerates recruitment and study enrollment.", integrations: ["EHR systems", "Trial registries", "Research CRMs"], second: ["Protocol databases", "Analytics", "Messaging", "Email"] },
    { name: "Pharmacy & Medication Helper", suite: "Healthcare Suite", desc: "Answers medication questions related to dosage, interactions, and refills. Routes refill requests and prior authorizations through correct workflows. Improves adherence and medication safety.", integrations: ["Pharmacy systems", "EHR systems", "PBM platforms"], second: ["Drug databases", "Alerts", "SMS", "Patient portals"] },
    { name: "Insurance Claims Query Agent", suite: "Healthcare Suite", desc: "Helps providers check claim status and understand required corrections quickly. Summarizes denial reasons and recommends next steps. Reduces revenue cycle delays and manual follow-ups.", integrations: ["Claims clearinghouses", "Payer systems"], second: ["RCM tools", "Analytics", "Email", "Provider portals"] },
    { name: "Nursing Station Automation", suite: "Healthcare Suite", desc: "Automates routine nursing station workflows such as vitals logging, task handoffs, and patient status updates. Coordinates shift changes and alerts clinicians to priority patient needs. Improves care efficiency while reducing nurse workload.", integrations: ["EHR systems", "Nurse call systems", "Scheduling tools"], second: ["Mobile apps", "Alerts", "Messaging", "Clinical dashboards"] },
    // Cross-Industry Analytics Suite (10)
    { name: "Sentiment & Emotion Analyzer", suite: "Cross-Industry Analytics Suite", desc: "Understands emotions at scale from text, reviews, and transcripts with nuance. Scores sentiment polarity and extracts themes across segments and time periods. Enables data-driven product and experience decisions from emotional insights.", integrations: ["Survey tools", "Social media APIs", "Call transcripts"], second: ["BI tools", "NLP platforms", "Visualization tools", "Email"] },
    { name: "Vehicle Damage Image Analyzer", suite: "Cross-Industry Analytics Suite", desc: "Assesses vehicle damage accurately from uploaded images for insurance workflows. Identifies impacted parts and estimates repair cost ranges automatically. Speeds up claims processing while reducing fraud risk.", integrations: ["Claims systems", "Image storage", "Repair databases"], second: ["Computer vision models", "ML pipelines", "Case tools", "Email"] },
    { name: "FAQ Document Generator", suite: "Cross-Industry Analytics Suite", desc: "Automatically generates structured FAQ content from spreadsheets or website data. Produces SEO-optimized question-answer pairs for support and search. Reduces manual content authoring effort significantly.", integrations: ["Google Sheets", "CMS platforms", "Knowledge bases"], second: ["AI writing tools", "Search optimization", "Analytics", "Email"] },
    { name: "Document Risk Analyzer", suite: "Cross-Industry Analytics Suite", desc: "Analyzes contracts and project documents to uncover risks and dependencies. Ranks threats by likelihood and business impact. Helps leaders mitigate issues before they escalate.", integrations: ["CLM tools", "SharePoint", "Google Drive", "Project systems"], second: ["Legal review tools", "Risk scoring engines", "Email"] },
    { name: "Meeting & Call Summarizer", suite: "Cross-Industry Analytics Suite", desc: "Converts meetings and calls into concise, action-oriented summaries instantly. Extracts decisions, owners, risks, and next steps automatically. Improves accountability and eliminates manual note-taking.", integrations: ["Zoom", "Microsoft Teams", "CRM", "Project tools"], second: ["Transcription engines", "Email", "Alerts", "Slack"] },
    { name: "Survey Response Synthesizer", suite: "Cross-Industry Analytics Suite", desc: "Clusters open-ended survey responses and quantifies dominant themes. Generates dashboards and executive-ready insight summaries. Turns qualitative feedback into measurable outcomes.", integrations: ["SurveyMonkey", "Typeform", "BI platforms"], second: ["NLP engines", "Visualization tools", "Analytics", "Email"] },
    { name: "Knowledge Graph Builder", suite: "Cross-Industry Analytics Suite", desc: "Builds a unified enterprise knowledge graph from documents and systems. Enables semantic search and context-aware reasoning for other agents. Creates a connected, organization-wide intelligence layer.", integrations: ["SharePoint", "Confluence", "Databases"], second: ["Vector databases", "NLP", "Search engines", "Visualization"] },
    { name: "Document Redaction & PII Scrubber", suite: "Cross-Industry Analytics Suite", desc: "Detects and masks sensitive personal and confidential data across documents. Applies privacy rules automatically before external sharing. Reduces breach risk and ensures regulatory compliance.", integrations: ["Document management systems", "DLP tools"], second: ["Storage systems", "Email", "Scanning tools", "Compliance engines"] },
    { name: "Multimodal Compliance Reviewer", suite: "Cross-Industry Analytics Suite", desc: "Reviews text, images, audio, and transcripts against compliance policies. Produces audit-ready evidence and compliance reports. Simplifies regulatory checks across multiple data formats.", integrations: ["Legal systems", "Storage platforms", "Email"], second: ["BI tools", "Reporting systems", "Risk scoring", "Alerts"] },
    { name: "Workflow Orchestration Agent", suite: "Cross-Industry Analytics Suite", desc: "Connects multiple agents and systems into end-to-end automated workflows. Optimizes routing, retries, and human-in-the-loop steps. Enables complex automation without custom code.", integrations: ["Core enterprise apps", "Webhooks", "iPaaS platforms"], second: ["Workflow engines", "Logging", "Monitoring", "APIs"] },
    // Community & Innovation Suite (10)
    { name: "Template Builder for Community", suite: "Community & Innovation Suite", desc: "Lets power users compose new agents from reusable recipes and prompts. Publishes them to a curated community gallery with governance controls. Democratizes agent creation and accelerates innovation at scale.", integrations: ["Your agent studio", "Git repositories", "Slack / Discord"], second: ["Prompt databases", "Version control", "Community tools"] },
    { name: "Data-to-Dashboard Recipe", suite: "Community & Innovation Suite", desc: "Transforms CSVs or spreadsheets into auto-refreshed dashboards instantly. Documents assumptions, metrics, and filters for easy sharing. Enables self-serve analytics without BI team dependency.", integrations: ["Google Sheets", "Excel", "BI tools"], second: ["Data connectors", "Templates", "Scheduling", "Email"] },
    { name: "Talk-to-Your-Docs Agent", suite: "Community & Innovation Suite", desc: "Allows users to ask natural-language questions over uploaded files and web links. Provides citations back to source snippets for verification. Turns document libraries into conversational knowledge systems.", integrations: ["File storage systems", "Web crawler", "Vector databases"], second: ["Search", "Authentication", "Embeddings", "Portals"] },
    { name: "Workflow Explainer Bot", suite: "Community & Innovation Suite", desc: "Explains how workflows operate in simple language for new team members. Visualizes steps, dependencies, and failure modes interactively. Accelerates onboarding and reduces documentation gaps.", integrations: ["BPM tools", "Documentation platforms", "Diagram tools"], second: ["Visualization engines", "Chat interfaces", "Knowledge bases", "Mobile"] },
    { name: "Personal Research Assistant", suite: "Community & Innovation Suite", desc: "Conducts structured web research with automatic note-taking and source tracking. Produces briefs, outlines, and slide drafts from findings. Speeds up research and learning for knowledge workers.", integrations: ["Browser tools", "Document editors", "Slide tools"], second: ["Citation managers", "Search APIs", "Outline tools"] },
    { name: "Prompt Engineering Coach", suite: "Community & Innovation Suite", desc: "Guides users in designing, testing, and improving prompts or agent recipes. Suggests patterns, safety guards, and evaluation strategies. Improves agent quality and consistency across teams.", integrations: ["LLM endpoints", "Experiment tracking platforms"], second: ["Documentation tools", "Version control", "Testing tools", "Slack"] },
    { name: "Code Refactor & Review Agent", suite: "Community & Innovation Suite", desc: "Reviews code for bugs, security risks, and style issues automatically. Proposes refactors and explains improvements with examples. Improves code quality and shared engineering knowledge.", integrations: ["GitHub / GitLab", "CI pipelines"], second: ["Issue trackers", "Code analysis tools", "Linting", "Email"] },
    { name: "Analytics Query Co-Pilot", suite: "Community & Innovation Suite", desc: "Converts natural-language questions into SQL or BI queries accurately. Validates metric definitions and previews sample outputs. Enables non-technical users to access analytics safely.", integrations: ["Data warehouses", "BI tools", "Metrics repositories"], second: ["Query testing", "Optimization tools", "Documentation"] },
    { name: "Workflow Cost Optimizer", suite: "Community & Innovation Suite", desc: "Estimates cost per workflow including model usage, APIs, and infrastructure. Recommends caching, batching, and optimal model choices. Maximizes ROI of AI agent deployments.", integrations: ["Cloud billing platforms", "LLM usage logs"], second: ["Orchestration tools", "Monitoring", "Analytics", "Email"] },
    { name: "Multi-Agent Recipe Hub (Rube-style)", suite: "Community & Innovation Suite", desc: "Discovers, chains, and executes reusable multi-agent \"recipes\" end-to-end. Supports visual composition like research → drafting → QA flows. Enables powerful no-code enterprise automation for advanced users.", integrations: ["All marketplace agents", "Orchestration engine"], second: ["UI builders", "Recipe templates", "Version control", "GitHub"] },
  ]

  return agentTemplates.map((template, index) => {
    const id = template.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")
    const details = generateAgentDetails(template.desc, template.suite)
    return {
      id,
      name: template.name,
      suite: template.suite,
      description: template.desc,
      detailedDescription: `${template.desc} This agent leverages advanced AI capabilities to automate and optimize ${template.suite.toLowerCase()} processes, ensuring consistent execution and improved outcomes.`,
      primaryIntegrations: template.integrations,
      secondaryIntegrations: template.second,
      author: `${template.suite} Team`,
      likes: 150 + (index % 100),
      videoUrl: "",
      ...details,
    }
  })
}

export const allAgents: Agent[] = [
  ...allAgentsData,
  ...generateRemainingAgents(),
]

export const suites = [
  "Sales Suite",
  "Marketing Suite",
  "Customer Service Suite",
  "HR & Talent Suite",
  "IT & Operations Suite",
  "Finance & Banking Suite",
  "Retail & E-Commerce Suite",
  "Healthcare Suite",
  "Cross-Industry Analytics Suite",
  "Community & Innovation Suite",
]

export function getAgentsBySuite(suite: string): Agent[] {
  return allAgents.filter(agent => agent.suite === suite)
}

export function getAgentById(id: string): Agent | undefined {
  return allAgents.find(agent => agent.id === id)
}

