import type { AgentFlow } from "@/components/flow-chart"
import {
  Clock,
  Calendar,
  Mail,
  FileText,
  Rocket,
  Database,
  Search,
  Zap,
  CheckCircle,
  AlertCircle,
  Users,
  MessageSquare,
  BarChart3,
  Shield,
  Target,
  TrendingUp,
  Settings,
  Eye,
  Send,
  Save,
  Briefcase,
  CreditCard,
  Phone,
  Headphones,
  Wrench,
  Server,
  Heart,
  ShoppingBag,
  Stethoscope,
  Globe,
  BookOpen,
  RefreshCw,
  Star,
  Mic,
  Code,
  LayoutGrid,
  HelpCircle,
  Lock,
  Network,
  type LucideIcon,
} from "lucide-react"

// Flow data for all 103 agents
export const agentFlows: Record<string, AgentFlow> = {
  // Sales Suite
  "proposal-reviewer": {
    trigger: "Proposal draft submitted for review",
    steps: [
      { number: 1, icon: FileText, text: "Proposal draft submitted for review" },
      { number: 2, icon: Database, text: "Gather proposal content, company style guide, and pricing rules" },
      { number: 3, icon: Search, text: "Enrich with past successful proposals and legal guidelines" },
      { number: 4, icon: BarChart3, text: "Analyze compliance with style, pricing, and legal requirements" },
      { number: 5, icon: CheckCircle, text: "Evaluate gaps and inconsistencies in messaging" },
      { number: 6, icon: FileText, text: "Generate revised sections with improved clarity and persuasion" },
      { number: 7, icon: Send, text: "Deliver review report with highlighted gaps and recommendations" },
    ],
  },
  "lead-analyzer": {
    trigger: "New lead created in CRM or marketing system",
    steps: [
      { number: 1, icon: Users, text: "New lead created in CRM or marketing system" },
      { number: 2, icon: Database, text: "Gather lead contact information and source data" },
      { number: 3, icon: TrendingUp, text: "Enrich with firmographic data and intent signals from Clearbit/ZoomInfo" },
      { number: 4, icon: BarChart3, text: "Analyze lead quality using company size, industry fit, and engagement patterns" },
      { number: 5, icon: Target, text: "Score lead priority based on multiple qualification factors" },
      { number: 6, icon: Send, text: "Route high-value leads to appropriate sales owner or sequence" },
    ],
  },
  "rfp-response-automation": {
    trigger: "RFP document received or uploaded",
    steps: [
      { number: 1, icon: FileText, text: "RFP document received or uploaded" },
      { number: 2, icon: Database, text: "Gather RFP questions and requirements from document" },
      { number: 3, icon: Search, text: "Enrich with content library, past deals, and product documentation" },
      { number: 4, icon: BarChart3, text: "Analyze questions and match to best-fit answers from knowledge base" },
      { number: 5, icon: AlertCircle, text: "Flag missing information and sections requiring SME review" },
      { number: 6, icon: FileText, text: "Generate first-draft RFP response with suggested answers" },
      { number: 7, icon: Send, text: "Deliver draft response with tracking for review status" },
    ],
  },
  "deal-desk-assistant": {
    trigger: "Deal with discount or non-standard terms submitted",
    steps: [
      { number: 1, icon: CreditCard, text: "Deal with discount or non-standard terms submitted" },
      { number: 2, icon: Database, text: "Gather deal data including pricing, terms, and customer information" },
      { number: 3, icon: Search, text: "Enrich with company policy rules and historical approval patterns" },
      { number: 4, icon: BarChart3, text: "Analyze deal against policy requirements and margin thresholds" },
      { number: 5, icon: CheckCircle, text: "Evaluate compliance and identify fastest approval path" },
      { number: 6, icon: FileText, text: "Generate approval request with policy validation and recommendations" },
      { number: 7, icon: Send, text: "Route to appropriate approvers with clear justification" },
    ],
  },
  "account-briefing-agent": {
    trigger: "Meeting scheduled with key account stakeholder",
    steps: [
      { number: 1, icon: Calendar, text: "Meeting scheduled with key account stakeholder" },
      { number: 2, icon: Database, text: "Gather account health metrics, open opportunities, and support tickets" },
      { number: 3, icon: Search, text: "Enrich with recent executive news and account activity history" },
      { number: 4, icon: BarChart3, text: "Analyze account status and identify key talking points" },
      { number: 5, icon: FileText, text: "Generate concise briefing tailored to attendee role and meeting objective" },
      { number: 6, icon: Send, text: "Deliver account briefing with talking points and recommendations" },
    ],
  },
  "competitive-battlecard-agent": {
    trigger: "Competitive threat detected in deal or inquiry",
    steps: [
      { number: 1, icon: Shield, text: "Competitive threat detected in deal or inquiry" },
      { number: 2, icon: Database, text: "Gather internal win-loss notes and competitive intelligence" },
      { number: 3, icon: Search, text: "Enrich with public sources, product changes, and pricing data" },
      { number: 4, icon: BarChart3, text: "Analyze competitive positioning and feature gaps" },
      { number: 5, icon: FileText, text: "Generate live battlecard with objection handling and comparisons" },
      { number: 6, icon: Send, text: "Deliver battlecard to sales rep with real-time competitive intelligence" },
    ],
  },
  "renewal-upsell-advisor": {
    trigger: "Contract renewal window approaching or usage threshold reached",
    steps: [
      { number: 1, icon: Calendar, text: "Contract renewal window approaching or usage threshold reached" },
      { number: 2, icon: Database, text: "Gather contract details, usage patterns, and customer sentiment data" },
      { number: 3, icon: TrendingUp, text: "Enrich with product adoption metrics and expansion signals" },
      { number: 4, icon: BarChart3, text: "Analyze renewal risk and upsell potential using predictive models" },
      { number: 5, icon: Target, text: "Evaluate account health and recommend renewal or expansion plays" },
      { number: 6, icon: FileText, text: "Generate tailored outreach cadence and value messaging recommendations" },
      { number: 7, icon: Send, text: "Deliver renewal playbook with next actions and talking points" },
    ],
  },
  "sales-email-drafter": {
    trigger: "Email needed for outreach, follow-up, or meeting recap",
    steps: [
      { number: 1, icon: Mail, text: "Email needed for outreach, follow-up, or meeting recap" },
      { number: 2, icon: Database, text: "Gather CRM data, call notes, and recipient information" },
      { number: 3, icon: Search, text: "Enrich with engagement history and segment preferences" },
      { number: 4, icon: BarChart3, text: "Analyze optimal tone, length, and CTA based on objective and segment" },
      { number: 5, icon: FileText, text: "Generate personalized email draft with optimized messaging" },
      { number: 6, icon: Send, text: "Deliver email draft ready for review and sending" },
    ],
  },
  "lead-routing-orchestrator": {
    trigger: "New lead assigned or requires routing",
    steps: [
      { number: 1, icon: Users, text: "New lead assigned or requires routing" },
      { number: 2, icon: Database, text: "Gather lead attributes including territory, industry, and product interest" },
      { number: 3, icon: Search, text: "Enrich with rep capacity, expertise, and current workload data" },
      { number: 4, icon: BarChart3, text: "Analyze best-fit rep based on territory, expertise, and capacity rules" },
      { number: 5, icon: CheckCircle, text: "Evaluate routing conflicts and apply resolution logic" },
      { number: 6, icon: Target, text: "Assign lead to optimal rep with transparent explanation" },
      { number: 7, icon: Send, text: "Notify assigned rep with lead context and routing rationale" },
    ],
  },
  "partner-sales-co-pilot": {
    trigger: "Partner requests deal registration, enablement content, or process guidance",
    steps: [
      { number: 1, icon: Briefcase, text: "Partner requests deal registration, enablement content, or process guidance" },
      { number: 2, icon: Database, text: "Gather partner information and request details" },
      { number: 3, icon: Search, text: "Enrich with partner portal content and enablement resources" },
      { number: 4, icon: BarChart3, text: "Analyze request type and match to appropriate resources or workflows" },
      { number: 5, icon: FileText, text: "Generate guided process or provide relevant enablement content" },
      { number: 6, icon: Send, text: "Deliver assistance with deal registration guidance or content access" },
    ],
  },
  "ai-sales-sdr": {
    trigger: "Outbound prospecting sequence initiated or prospect identified",
    steps: [
      { number: 1, icon: Target, text: "Outbound prospecting sequence initiated or prospect identified" },
      { number: 2, icon: Database, text: "Gather prospect information and research requirements" },
      { number: 3, icon: Search, text: "Enrich with company data, social signals, and intent indicators" },
      { number: 4, icon: BarChart3, text: "Analyze prospect fit and personalize outreach messaging" },
      { number: 5, icon: Mail, text: "Generate personalized outreach emails and execute multi-step sequences" },
      { number: 6, icon: CheckCircle, text: "Evaluate engagement and qualify intent automatically" },
      { number: 7, icon: Send, text: "Deliver qualified leads to sales team with full context" },
    ],
  },
  "ai-sales-coach": {
    trigger: "Sales call completed or deal stage updated",
    steps: [
      { number: 1, icon: Phone, text: "Sales call completed or deal stage updated" },
      { number: 2, icon: Database, text: "Gather call recording, email threads, and deal progress data" },
      { number: 3, icon: Search, text: "Enrich with best practices database and historical win patterns" },
      { number: 4, icon: BarChart3, text: "Analyze call performance, skill gaps, and coaching opportunities" },
      { number: 5, icon: Target, text: "Evaluate next actions tailored to opportunity stage and context" },
      { number: 6, icon: FileText, text: "Generate real-time coaching feedback and best practice recommendations" },
      { number: 7, icon: Send, text: "Deliver post-call coaching insights and suggested next steps" },
    ],
  },
  // Marketing Suite
  "campaign-planner-agent": {
    trigger: "Marketing goal and target audience defined",
    steps: [
      { number: 1, icon: Target, text: "Marketing goal and target audience defined" },
      { number: 2, icon: Database, text: "Gather campaign objectives, budget constraints, and audience segments" },
      { number: 3, icon: Search, text: "Enrich with historical campaign performance and channel capabilities" },
      { number: 4, icon: BarChart3, text: "Analyze optimal channel mix and messaging angles for funnel stages" },
      { number: 5, icon: FileText, text: "Generate multi-channel campaign plan with timelines and budgets" },
      { number: 6, icon: Send, text: "Deliver executable campaign roadmap with content recommendations" },
    ],
  },
  "content-brief-generator": {
    trigger: "Content piece requested or keyword research completed",
    steps: [
      { number: 1, icon: FileText, text: "Content piece requested or keyword research completed" },
      { number: 2, icon: Database, text: "Gather keyword research, persona data, and content requirements" },
      { number: 3, icon: Search, text: "Enrich with SEO best practices and brand guideline references" },
      { number: 4, icon: BarChart3, text: "Analyze SEO alignment and content structure requirements" },
      { number: 5, icon: FileText, text: "Generate detailed content brief with SEO optimization and brand alignment" },
      { number: 6, icon: Send, text: "Deliver content brief ready for writer with tracking status" },
    ],
  },
  "social-media-manager": {
    trigger: "Content ready for social distribution or engagement needed",
    steps: [
      { number: 1, icon: MessageSquare, text: "Content ready for social distribution or engagement needed" },
      { number: 2, icon: Database, text: "Gather content assets and platform-specific requirements" },
      { number: 3, icon: Search, text: "Enrich with brand voice guidelines and optimal posting times" },
      { number: 4, icon: BarChart3, text: "Analyze content format and adapt for each platform" },
      { number: 5, icon: FileText, text: "Generate platform-specific posts and repurpose content into multiple formats" },
      { number: 6, icon: Send, text: "Schedule posts and surface comments requiring responses" },
    ],
  },
  "brand-sentiment-analyzer": {
    trigger: "New review, social mention, or survey response received",
    steps: [
      { number: 1, icon: MessageSquare, text: "New review, social mention, or survey response received" },
      { number: 2, icon: Database, text: "Gather reviews, social mentions, and survey feedback across channels" },
      { number: 3, icon: Search, text: "Enrich with historical sentiment data and customer segment information" },
      { number: 4, icon: BarChart3, text: "Analyze sentiment polarity and extract themes across segments" },
      { number: 5, icon: AlertCircle, text: "Evaluate root causes and identify segments needing attention" },
      { number: 6, icon: FileText, text: "Generate sentiment score and actionable insights report" },
      { number: 7, icon: Send, text: "Deliver real-time sentiment dashboard with recommendations" },
    ],
  },
  "event-webinar-concierge": {
    trigger: "Event registration opened or webinar scheduled",
    steps: [
      { number: 1, icon: Calendar, text: "Event registration opened or webinar scheduled" },
      { number: 2, icon: Database, text: "Gather event details, registrant information, and engagement data" },
      { number: 3, icon: Search, text: "Enrich with CRM data and lead scoring models" },
      { number: 4, icon: BarChart3, text: "Analyze attendee engagement and qualification signals" },
      { number: 5, icon: Mail, text: "Generate registration confirmations, reminders, and post-event follow-ups" },
      { number: 6, icon: Send, text: "Sync attendance and engagement data to CRM automatically" },
    ],
  },
  "website-conversion-coach": {
    trigger: "Website analytics data updated or conversion goal defined",
    steps: [
      { number: 1, icon: Eye, text: "Website analytics data updated or conversion goal defined" },
      { number: 2, icon: Database, text: "Gather user journey data, drop-off points, and heatmap insights" },
      { number: 3, icon: Search, text: "Enrich with A/B test history and conversion best practices" },
      { number: 4, icon: BarChart3, text: "Analyze conversion bottlenecks and identify optimization opportunities" },
      { number: 5, icon: FileText, text: "Generate CRO experiment suggestions with copy variants and micro-interactions" },
      { number: 6, icon: Send, text: "Deliver actionable CRO recommendations for key pages and forms" },
    ],
  },
  "survey-nps-orchestrator": {
    trigger: "Survey response submitted or NPS campaign launched",
    steps: [
      { number: 1, icon: MessageSquare, text: "Survey response submitted or NPS campaign launched" },
      { number: 2, icon: Database, text: "Gather survey responses and respondent demographic data" },
      { number: 3, icon: Search, text: "Enrich with customer history and product usage data" },
      { number: 4, icon: BarChart3, text: "Analyze responses by persona and channel, clustering themes" },
      { number: 5, icon: FileText, text: "Generate insight summaries with high-impact verbatim comments" },
      { number: 6, icon: Send, text: "Deliver executive-ready dashboards and actionable recommendations" },
    ],
  },
  "product-launch-assistant": {
    trigger: "Product launch initiated or milestone deadline approaching",
    steps: [
      { number: 1, icon: Rocket, text: "Product launch initiated or milestone deadline approaching" },
      { number: 2, icon: Database, text: "Gather launch plan, checklists, and cross-team dependencies" },
      { number: 3, icon: Search, text: "Enrich with messaging assets and team capacity data" },
      { number: 4, icon: BarChart3, text: "Analyze dependency chains and identify potential blockers" },
      { number: 5, icon: AlertCircle, text: "Evaluate milestone status and alert owners of slips" },
      { number: 6, icon: FileText, text: "Generate launch status updates and coordination tasks" },
      { number: 7, icon: Send, text: "Deliver real-time launch dashboard keeping all teams aligned" },
    ],
  },
  "abm-engagement-agent": {
    trigger: "High-value account added to ABM program or engagement needed",
    steps: [
      { number: 1, icon: Target, text: "High-value account added to ABM program or engagement needed" },
      { number: 2, icon: Database, text: "Gather account intelligence and engagement history" },
      { number: 3, icon: Search, text: "Enrich with intent signals and account activity data" },
      { number: 4, icon: BarChart3, text: "Analyze account needs and personalize messaging angles" },
      { number: 5, icon: FileText, text: "Generate tailored microscripts and sequences with precision targeting" },
      { number: 6, icon: Send, text: "Deliver personalized engagement plays with recommended next actions" },
    ],
  },
  "seo-health-monitor": {
    trigger: "SEO crawl completed or ranking data updated",
    steps: [
      { number: 1, icon: Search, text: "SEO crawl completed or ranking data updated" },
      { number: 2, icon: Database, text: "Gather keyword rankings, crawl issues, and content freshness data" },
      { number: 3, icon: Search, text: "Enrich with historical ranking trends and competitor data" },
      { number: 4, icon: BarChart3, text: "Analyze ranking drops, crawl errors, and content decay signals" },
      { number: 5, icon: AlertCircle, text: "Evaluate critical issues requiring immediate attention" },
      { number: 6, icon: FileText, text: "Generate tasks to refresh content or fix technical issues" },
      { number: 7, icon: Send, text: "Trigger automated fixes and deliver SEO health report" },
    ],
  },
  // Customer Service Suite - flows continue below
  "omni-channel-support-agent": {
    trigger: "Customer inquiry received across chat, email, voice, or messaging",
    steps: [
      { number: 1, icon: Headphones, text: "Customer inquiry received across chat, email, voice, or messaging" },
      { number: 2, icon: Database, text: "Gather inquiry details and customer interaction history" },
      { number: 3, icon: Search, text: "Enrich with connected system data and knowledge base articles" },
      { number: 4, icon: BarChart3, text: "Analyze inquiry type and match to resolution workflows" },
      { number: 5, icon: CheckCircle, text: "Evaluate if issue can be resolved automatically or needs escalation" },
      { number: 6, icon: FileText, text: "Generate resolution response or escalate to live agent with full context" },
      { number: 7, icon: Send, text: "Deliver consistent support response across all channels" },
    ],
  },
  "ticket-triage-routing": {
    trigger: "New support ticket created",
    steps: [
      { number: 1, icon: FileText, text: "New support ticket created" },
      { number: 2, icon: Database, text: "Gather ticket content, customer information, and historical data" },
      { number: 3, icon: Search, text: "Enrich with knowledge base articles and similar resolved tickets" },
      { number: 4, icon: BarChart3, text: "Analyze ticket topic and predict priority level" },
      { number: 5, icon: Target, text: "Route to appropriate queue based on topic and priority" },
      { number: 6, icon: FileText, text: "Suggest response templates and knowledge articles" },
      { number: 7, icon: Send, text: "Deliver ticket to assigned agent with suggested resources" },
    ],
  },
  "order-status-returns-agent": {
    trigger: "Customer requests order status or return",
    steps: [
      { number: 1, icon: ShoppingBag, text: "Customer requests order status or return" },
      { number: 2, icon: Database, text: "Gather order details and logistics tracking information" },
      { number: 3, icon: Search, text: "Enrich with return policy rules and shipping carrier data" },
      { number: 4, icon: BarChart3, text: "Analyze order status and return eligibility" },
      { number: 5, icon: CheckCircle, text: "Validate return request against policy rules" },
      { number: 6, icon: FileText, text: "Generate return label and provide proactive status updates" },
      { number: 7, icon: Send, text: "Deliver order tracking or return instructions conversationally" },
    ],
  },
  "knowledge-base-curator": {
    trigger: "Support ticket resolved or knowledge gap identified",
    steps: [
      { number: 1, icon: FileText, text: "Support ticket resolved or knowledge gap identified" },
      { number: 2, icon: Database, text: "Gather resolved ticket content and resolution details" },
      { number: 3, icon: Search, text: "Enrich with existing knowledge base articles and usage data" },
      { number: 4, icon: BarChart3, text: "Analyze ticket resolution for knowledge article potential" },
      { number: 5, icon: CheckCircle, text: "Evaluate article usefulness and flag for SME review" },
      { number: 6, icon: FileText, text: "Generate or update knowledge base article automatically" },
      { number: 7, icon: Save, text: "Store article with de-duplication and scoring metadata" },
    ],
  },
  "warranty-claims-assistant": {
    trigger: "Warranty check or claim submission initiated",
    steps: [
      { number: 1, icon: Shield, text: "Warranty check or claim submission initiated" },
      { number: 2, icon: Database, text: "Gather product information and purchase history" },
      { number: 3, icon: Search, text: "Enrich with warranty policy rules and eligibility criteria" },
      { number: 4, icon: BarChart3, text: "Analyze warranty eligibility and claim requirements" },
      { number: 5, icon: CheckCircle, text: "Validate eligibility and required evidence automatically" },
      { number: 6, icon: FileText, text: "Generate structured claim form with evidence collection" },
      { number: 7, icon: Send, text: "Deliver claim status and processing timeline updates" },
    ],
  },
  "feedback-complaint-resolver": {
    trigger: "Customer complaint or feedback submitted",
    steps: [
      { number: 1, icon: MessageSquare, text: "Customer complaint or feedback submitted" },
      { number: 2, icon: Database, text: "Gather complaint details and customer history" },
      { number: 3, icon: Search, text: "Enrich with sentiment data and similar resolved cases" },
      { number: 4, icon: BarChart3, text: "Analyze complaint severity and classify automatically" },
      { number: 5, icon: AlertCircle, text: "Evaluate risk level and determine escalation need" },
      { number: 6, icon: FileText, text: "Generate empathetic response suggestions and resolution plan" },
      { number: 7, icon: Send, text: "Deliver response or escalate high-risk cases with SLA tracking" },
    ],
  },
  "subscription-billing-helper": {
    trigger: "Billing inquiry or subscription change requested",
    steps: [
      { number: 1, icon: CreditCard, text: "Billing inquiry or subscription change requested" },
      { number: 2, icon: Database, text: "Gather subscription details, usage data, and billing history" },
      { number: 3, icon: Search, text: "Enrich with plan options and pricing information" },
      { number: 4, icon: BarChart3, text: "Analyze usage patterns and recommend best-fit plan" },
      { number: 5, icon: CheckCircle, text: "Validate plan changes and explain charges clearly" },
      { number: 6, icon: FileText, text: "Generate clear billing explanations and plan recommendations" },
      { number: 7, icon: Send, text: "Deliver billing transparency and process refunds if needed" },
    ],
  },
  "multilingual-support-translator": {
    trigger: "Message received in non-primary language",
    steps: [
      { number: 1, icon: Globe, text: "Message received in non-primary language" },
      { number: 2, icon: Database, text: "Gather message content and language detection data" },
      { number: 3, icon: Search, text: "Enrich with product-specific terminology and regional context" },
      { number: 4, icon: BarChart3, text: "Analyze message context and preserve tone during translation" },
      { number: 5, icon: FileText, text: "Generate translated message maintaining context and tone" },
      { number: 6, icon: Send, text: "Deliver translated message to agent or customer" },
    ],
  },
  "proactive-outage-communicator": {
    trigger: "Service incident detected or outage declared",
    steps: [
      { number: 1, icon: AlertCircle, text: "Service incident detected or outage declared" },
      { number: 2, icon: Database, text: "Gather incident details, affected services, and customer segments" },
      { number: 3, icon: Search, text: "Enrich with customer preferences and communication channels" },
      { number: 4, icon: BarChart3, text: "Analyze impact scope and generate targeted update messages" },
      { number: 5, icon: FileText, text: "Generate FAQs, ETAs, and next steps for affected customers" },
      { number: 6, icon: Send, text: "Push proactive updates via preferred channels reducing ticket spikes" },
    ],
  },
  "community-forum-moderator": {
    trigger: "New post or comment submitted in community forum",
    steps: [
      { number: 1, icon: Users, text: "New post or comment submitted in community forum" },
      { number: 2, icon: Database, text: "Gather post content and user history" },
      { number: 3, icon: Search, text: "Enrich with knowledge base articles and moderation rules" },
      { number: 4, icon: BarChart3, text: "Analyze post for abuse, spam, or answer potential" },
      { number: 5, icon: CheckCircle, text: "Evaluate if post needs moderation or answer suggestion" },
      { number: 6, icon: FileText, text: "Generate answer suggestions or flag for moderation" },
      { number: 7, icon: Send, text: "Auto-tag posts and route unresolved threads to support" },
    ],
  },
  // HR & Talent Suite
  "leave-absence-assistant": {
    trigger: "Leave request submitted by employee or manager",
    steps: [
      { number: 1, icon: Calendar, text: "Leave request submitted by employee or manager" },
      { number: 2, icon: Database, text: "Gather employee leave balances and policy rules" },
      { number: 3, icon: Search, text: "Enrich with overlapping shift data and team coverage" },
      { number: 4, icon: BarChart3, text: "Analyze eligibility, balance, and policy compliance" },
      { number: 5, icon: CheckCircle, text: "Validate request against policy and team constraints" },
      { number: 6, icon: FileText, text: "Generate approval decision with clear explanation" },
      { number: 7, icon: Send, text: "Deliver instant self-service response reducing HR workload" },
    ],
  },
  "payroll-earnings-explainer": {
    trigger: "Employee queries payslip or earnings information",
    steps: [
      { number: 1, icon: CreditCard, text: "Employee queries payslip or earnings information" },
      { number: 2, icon: Database, text: "Gather payslip data, earnings history, and tax information" },
      { number: 3, icon: Search, text: "Enrich with deduction details and year-to-date summaries" },
      { number: 4, icon: BarChart3, text: "Analyze query and extract relevant earnings information" },
      { number: 5, icon: FileText, text: "Generate plain-language explanation of earnings and deductions" },
      { number: 6, icon: Send, text: "Deliver payslip retrieval and earnings breakdown improving transparency" },
    ],
  },
  "resume-screener-agent": {
    trigger: "Resume submitted for open position",
    steps: [
      { number: 1, icon: FileText, text: "Resume submitted for open position" },
      { number: 2, icon: Database, text: "Gather resume content and role requirements" },
      { number: 3, icon: Search, text: "Enrich with diversity goals and hiring criteria" },
      { number: 4, icon: BarChart3, text: "Analyze resume against role criteria and diversity objectives" },
      { number: 5, icon: CheckCircle, text: "Evaluate candidate fit and identify risk flags" },
      { number: 6, icon: FileText, text: "Generate shortlist with rationale and risk assessment" },
      { number: 7, icon: Send, text: "Deliver candidate evaluation to hiring manager accelerating recruiting" },
    ],
  },
  "interview-intelligence-agent": {
    trigger: "Interview completed or notes submitted",
    steps: [
      { number: 1, icon: Users, text: "Interview completed or notes submitted" },
      { number: 2, icon: Database, text: "Gather interview notes, transcripts, and role requirements" },
      { number: 3, icon: Search, text: "Enrich with candidate history and interview best practices" },
      { number: 4, icon: BarChart3, text: "Analyze interview performance and summarize strengths and concerns" },
      { number: 5, icon: Target, text: "Evaluate next-round decision and recommend follow-up questions" },
      { number: 6, icon: FileText, text: "Generate objective interview summary with recommendations" },
      { number: 7, icon: Send, text: "Deliver interview insights improving hiring quality and consistency" },
    ],
  },
  "onboarding-concierge": {
    trigger: "New hire start date approaching or onboarding initiated",
    steps: [
      { number: 1, icon: Users, text: "New hire start date approaching or onboarding initiated" },
      { number: 2, icon: Database, text: "Gather new hire information, role, and location data" },
      { number: 3, icon: Search, text: "Enrich with personalized checklists and stakeholder assignments" },
      { number: 4, icon: BarChart3, text: "Analyze onboarding requirements and generate personalized journey" },
      { number: 5, icon: CheckCircle, text: "Track task completion and identify blockers" },
      { number: 6, icon: FileText, text: "Generate onboarding checklist and guide through paperwork and tools" },
      { number: 7, icon: Send, text: "Deliver smooth first-day experience ensuring faster time-to-productivity" },
    ],
  },
  "policy-q-a-assistant": {
    trigger: "Employee question about benefits, travel, or company policy",
    steps: [
      { number: 1, icon: HelpCircle, text: "Employee question about benefits, travel, or company policy" },
      { number: 2, icon: Database, text: "Gather policy documents and knowledge base content" },
      { number: 3, icon: Search, text: "Enrich with employee context and policy updates" },
      { number: 4, icon: BarChart3, text: "Analyze question and match to relevant policy information" },
      { number: 5, icon: CheckCircle, text: "Evaluate if question needs HR partner escalation" },
      { number: 6, icon: FileText, text: "Generate policy answer or escalate ambiguous topics" },
      { number: 7, icon: Send, text: "Deliver 24/7 policy support reducing HR team burden" },
    ],
  },
  "time-attendance-helper": {
    trigger: "Time entry, shift swap, or overtime request submitted",
    steps: [
      { number: 1, icon: Clock, text: "Time entry, shift swap, or overtime request submitted" },
      { number: 2, icon: Database, text: "Gather time data, shift schedules, and union agreements" },
      { number: 3, icon: Search, text: "Enrich with approval workflows and policy rules" },
      { number: 4, icon: BarChart3, text: "Analyze request against rules and validate automatically" },
      { number: 5, icon: CheckCircle, text: "Evaluate compliance with rules, approvals, and union agreements" },
      { number: 6, icon: FileText, text: "Generate approval request or process time correction" },
      { number: 7, icon: Send, text: "Deliver real-time validation streamlining scheduling and administration" },
    ],
  },
  "performance-review-co-pilot": {
    trigger: "Performance review period opened or review initiated",
    steps: [
      { number: 1, icon: FileText, text: "Performance review period opened or review initiated" },
      { number: 2, icon: Database, text: "Gather goals, feedback, and outcomes from review period" },
      { number: 3, icon: Search, text: "Enrich with performance data and review best practices" },
      { number: 4, icon: BarChart3, text: "Analyze performance data and surface key achievements" },
      { number: 5, icon: FileText, text: "Generate balanced, data-driven review draft" },
      { number: 6, icon: Send, text: "Deliver review assistance improving quality and reducing manager effort" },
    ],
  },
  "learning-path-advisor": {
    trigger: "Learning request or career development goal set",
    steps: [
      { number: 1, icon: BookOpen, text: "Learning request or career development goal set" },
      { number: 2, icon: Database, text: "Gather employee role, skills, and career goals" },
      { number: 3, icon: Search, text: "Enrich with available courses and learning paths" },
      { number: 4, icon: BarChart3, text: "Analyze skill gaps and recommend relevant learning opportunities" },
      { number: 5, icon: FileText, text: "Generate personalized learning path with course recommendations" },
      { number: 6, icon: Save, text: "Track completion and link outcomes to performance metrics" },
      { number: 7, icon: Send, text: "Deliver learning recommendations driving continuous development" },
    ],
  },
  "hr-case-manager": {
    trigger: "Employee relations case opened or sensitive issue reported",
    steps: [
      { number: 1, icon: Shield, text: "Employee relations case opened or sensitive issue reported" },
      { number: 2, icon: Database, text: "Gather case details and employee information" },
      { number: 3, icon: Search, text: "Enrich with policy guidelines and compliance requirements" },
      { number: 4, icon: BarChart3, text: "Analyze case and guide through structured workflows" },
      { number: 5, icon: CheckCircle, text: "Evaluate compliance and maintain audit trails" },
      { number: 6, icon: FileText, text: "Generate case documentation with structured workflows" },
      { number: 7, icon: Save, text: "Store case records ensuring fair treatment and compliance" },
    ],
  },
  // IT & Operations Suite
  "it-helpdesk-virtual-agent": {
    trigger: "IT issue reported by employee",
    steps: [
      { number: 1, icon: Wrench, text: "IT issue reported by employee" },
      { number: 2, icon: Database, text: "Gather issue description and system diagnostics" },
      { number: 3, icon: Search, text: "Enrich with knowledge base articles and quick fix solutions" },
      { number: 4, icon: BarChart3, text: "Analyze issue type and match to resolution workflows" },
      { number: 5, icon: CheckCircle, text: "Evaluate if issue can be resolved automatically" },
      { number: 6, icon: FileText, text: "Generate quick fix suggestions or create ticket if needed" },
      { number: 7, icon: Send, text: "Deliver conversational IT support reducing helpdesk volume" },
    ],
  },
  "it-request-fulfillment-agent": {
    trigger: "Hardware, software, or access request submitted",
    steps: [
      { number: 1, icon: Server, text: "Hardware, software, or access request submitted" },
      { number: 2, icon: Database, text: "Gather request details and user information" },
      { number: 3, icon: Search, text: "Enrich with approval workflows and asset availability" },
      { number: 4, icon: BarChart3, text: "Analyze request and route through approval process" },
      { number: 5, icon: CheckCircle, text: "Track approvals and fulfillment status" },
      { number: 6, icon: FileText, text: "Generate request tracking and status updates" },
      { number: 7, icon: Send, text: "Deliver real-time fulfillment status accelerating onboarding" },
    ],
  },
  "password-reset-unlock-agent": {
    trigger: "Password reset or account unlock requested",
    steps: [
      { number: 1, icon: Lock, text: "Password reset or account unlock requested" },
      { number: 2, icon: Database, text: "Gather user identity and account information" },
      { number: 3, icon: Search, text: "Enrich with MFA requirements and security policies" },
      { number: 4, icon: BarChart3, text: "Analyze request and validate user identity" },
      { number: 5, icon: CheckCircle, text: "Enforce MFA and security policy compliance" },
      { number: 6, icon: FileText, text: "Generate secure password reset workflow" },
      { number: 7, icon: Send, text: "Deliver account unlock and password reset guidance" },
    ],
  },
  "incident-command-assistant": {
    trigger: "IT incident declared or outage detected",
    steps: [
      { number: 1, icon: AlertCircle, text: "IT incident declared or outage detected" },
      { number: 2, icon: Database, text: "Gather incident details and affected systems" },
      { number: 3, icon: Search, text: "Enrich with stakeholder information and escalation paths" },
      { number: 4, icon: BarChart3, text: "Analyze incident severity and orchestrate response" },
      { number: 5, icon: FileText, text: "Generate incident timeline and stakeholder updates" },
      { number: 6, icon: Send, text: "Deliver automated incident coordination improving communication" },
    ],
  },
  "change-request-co-pilot": {
    trigger: "Change request submitted or deployment initiated",
    steps: [
      { number: 1, icon: Settings, text: "Change request submitted or deployment initiated" },
      { number: 2, icon: Database, text: "Gather change details and system dependencies" },
      { number: 3, icon: Search, text: "Enrich with policy rules and risk assessment criteria" },
      { number: 4, icon: BarChart3, text: "Analyze dependencies, risks, and approval requirements" },
      { number: 5, icon: CheckCircle, text: "Evaluate change against policy and validate compliance" },
      { number: 6, icon: FileText, text: "Generate change request draft with policy checks" },
      { number: 7, icon: Send, text: "Deliver change guidance accelerating delivery while minimizing risk" },
    ],
  },
  "asset-license-tracker": {
    trigger: "Asset usage updated or license renewal approaching",
    steps: [
      { number: 1, icon: Server, text: "Asset usage updated or license renewal approaching" },
      { number: 2, icon: Database, text: "Gather hardware and software usage data" },
      { number: 3, icon: Search, text: "Enrich with license renewal dates and compliance requirements" },
      { number: 4, icon: BarChart3, text: "Analyze usage patterns and identify optimization opportunities" },
      { number: 5, icon: AlertCircle, text: "Evaluate underutilized licenses and renewal needs" },
      { number: 6, icon: FileText, text: "Generate asset reports and optimization recommendations" },
      { number: 7, icon: Save, text: "Store tracking data reducing software spend and improving visibility" },
    ],
  },
  "knowledge-search-for-it": {
    trigger: "IT question asked in natural language",
    steps: [
      { number: 1, icon: Search, text: "IT question asked in natural language" },
      { number: 2, icon: Database, text: "Gather question and search documentation repositories" },
      { number: 3, icon: Search, text: "Enrich with related ticket history and resolution data" },
      { number: 4, icon: BarChart3, text: "Analyze question and match to relevant documentation" },
      { number: 5, icon: FileText, text: "Generate step-by-step resolution with related ticket context" },
      { number: 6, icon: Send, text: "Deliver self-service IT knowledge enabling lower ticket volume" },
    ],
  },
  "devops-release-assistant": {
    trigger: "Release pipeline initiated or deployment gate reached",
    steps: [
      { number: 1, icon: Rocket, text: "Release pipeline initiated or deployment gate reached" },
      { number: 2, icon: Database, text: "Gather build status, test coverage, and deployment data" },
      { number: 3, icon: Search, text: "Enrich with release history and quality standards" },
      { number: 4, icon: BarChart3, text: "Analyze build status and release readiness" },
      { number: 5, icon: CheckCircle, text: "Evaluate test coverage and rollback options" },
      { number: 6, icon: FileText, text: "Generate release summary with insights and recommendations" },
      { number: 7, icon: Send, text: "Deliver release guidance speeding up deployments while maintaining quality" },
    ],
  },
  "access-review-agent": {
    trigger: "Access certification period opened or exception requested",
    steps: [
      { number: 1, icon: Shield, text: "Access certification period opened or exception requested" },
      { number: 2, icon: Database, text: "Gather user access data and certification requirements" },
      { number: 3, icon: Search, text: "Enrich with policy rules and approver assignments" },
      { number: 4, icon: BarChart3, text: "Analyze access certifications and exception requests" },
      { number: 5, icon: CheckCircle, text: "Evaluate compliance and maintain audit trails" },
      { number: 6, icon: FileText, text: "Generate certification workflows and exception handling" },
      { number: 7, icon: Save, text: "Store audit evidence reducing security risk and audit findings" },
    ],
  },
  "itsm-analytics-analyst": {
    trigger: "ITSM data updated or analytics report requested",
    steps: [
      { number: 1, icon: BarChart3, text: "ITSM data updated or analytics report requested" },
      { number: 2, icon: Database, text: "Gather incident, problem, and change data" },
      { number: 3, icon: Search, text: "Enrich with historical trends and benchmark data" },
      { number: 4, icon: BarChart3, text: "Analyze trends and identify inefficiencies" },
      { number: 5, icon: FileText, text: "Generate analytics insights and automation recommendations" },
      { number: 6, icon: Send, text: "Deliver continuous improvement insights across IT operations" },
    ],
  },
  // Finance & Banking Suite
  "account-management-assistant": {
    trigger: "Customer requests account information or self-service action",
    steps: [
      { number: 1, icon: CreditCard, text: "Customer requests account information or self-service action" },
      { number: 2, icon: Database, text: "Gather account data and customer identity information" },
      { number: 3, icon: Search, text: "Enrich with KYC verification and security protocols" },
      { number: 4, icon: BarChart3, text: "Analyze request and validate customer identity securely" },
      { number: 5, icon: CheckCircle, text: "Verify security and authorize self-service actions" },
      { number: 6, icon: FileText, text: "Generate account information or process self-service request" },
      { number: 7, icon: Send, text: "Deliver secure account support reducing branch visits and call volume" },
    ],
  },
  "dispute-fraud-handler": {
    trigger: "Suspicious transaction reported or dispute initiated",
    steps: [
      { number: 1, icon: AlertCircle, text: "Suspicious transaction reported or dispute initiated" },
      { number: 2, icon: Database, text: "Gather transaction details and customer information" },
      { number: 3, icon: Search, text: "Enrich with fraud detection data and case management tools" },
      { number: 4, icon: BarChart3, text: "Analyze transaction patterns and collect evidence" },
      { number: 5, icon: CheckCircle, text: "Evaluate fraud risk and initiate dispute workflow" },
      { number: 6, icon: FileText, text: "Generate case documentation and explain timelines transparently" },
      { number: 7, icon: Send, text: "Deliver case updates building customer trust during fraud incidents" },
    ],
  },
  "atm-branch-locator": {
    trigger: "Customer requests ATM or branch location",
    steps: [
      { number: 1, icon: Target, text: "Customer requests ATM or branch location" },
      { number: 2, icon: Database, text: "Gather location data and customer preferences" },
      { number: 3, icon: Search, text: "Enrich with maps data and accessibility filters" },
      { number: 4, icon: BarChart3, text: "Analyze location request and find nearby options" },
      { number: 5, icon: FileText, text: "Generate location results with hours and services" },
      { number: 6, icon: Send, text: "Deliver instant location assistance improving convenience" },
    ],
  },
  "loan-eligibility-pre-qualification-agent": {
    trigger: "Loan application initiated or eligibility check requested",
    steps: [
      { number: 1, icon: CreditCard, text: "Loan application initiated or eligibility check requested" },
      { number: 2, icon: Database, text: "Gather applicant data and declared financial information" },
      { number: 3, icon: Search, text: "Enrich with credit bureau data and loan rules" },
      { number: 4, icon: BarChart3, text: "Analyze eligibility using credit rules and declared data" },
      { number: 5, icon: CheckCircle, text: "Evaluate loan eligibility and generate pre-qualified offers" },
      { number: 6, icon: FileText, text: "Generate personalized pre-qualified offers with clear next steps" },
      { number: 7, icon: Send, text: "Deliver real-time eligibility accelerating loan origination pipeline" },
    ],
  },
  "investment-profile-generator": {
    trigger: "Company or investor profile requested",
    steps: [
      { number: 1, icon: Briefcase, text: "Company or investor profile requested" },
      { number: 2, icon: Database, text: "Gather company data and financial metrics" },
      { number: 3, icon: Search, text: "Enrich with market data feeds and research platforms" },
      { number: 4, icon: BarChart3, text: "Analyze financial metrics and strategic fit" },
      { number: 5, icon: FileText, text: "Generate structured profile with ownership and risk factors" },
      { number: 6, icon: Send, text: "Deliver investment profiles speeding up deal evaluation" },
    ],
  },
  "client-briefing-sentiment-agent": {
    trigger: "Client meeting scheduled or call completed",
    steps: [
      { number: 1, icon: Calendar, text: "Client meeting scheduled or call completed" },
      { number: 2, icon: Database, text: "Gather meeting notes, emails, and call transcripts" },
      { number: 3, icon: Search, text: "Enrich with CRM data and historical interaction context" },
      { number: 4, icon: BarChart3, text: "Analyze meeting content and extract sentiment cues" },
      { number: 5, icon: FileText, text: "Generate client briefing with sentiment and risk indicators" },
      { number: 6, icon: Send, text: "Deliver automated briefings improving account insights" },
    ],
  },
  "expense-management-assistant": {
    trigger: "Expense submission or approval request initiated",
    steps: [
      { number: 1, icon: CreditCard, text: "Expense submission or approval request initiated" },
      { number: 2, icon: Database, text: "Gather expense details and receipt data" },
      { number: 3, icon: Search, text: "Enrich with policy rules and approval workflows" },
      { number: 4, icon: BarChart3, text: "Analyze expenses for policy violations and duplicates" },
      { number: 5, icon: CheckCircle, text: "Validate compliance and detect fraud risk" },
      { number: 6, icon: FileText, text: "Generate compliant expense submission or flag violations" },
      { number: 7, icon: Send, text: "Deliver expense processing reducing time and fraud risk" },
    ],
  },
  "invoice-processing-agent-finance": {
    trigger: "Invoice received or uploaded for processing",
    steps: [
      { number: 1, icon: FileText, text: "Invoice received or uploaded for processing" },
      { number: 2, icon: Database, text: "Gather invoice data using OCR and purchase order information" },
      { number: 3, icon: Search, text: "Enrich with vendor data and payment history" },
      { number: 4, icon: BarChart3, text: "Analyze invoice and match to purchase orders" },
      { number: 5, icon: AlertCircle, text: "Flag exceptions and missing information automatically" },
      { number: 6, icon: FileText, text: "Generate payment status updates and exception reports" },
      { number: 7, icon: Send, text: "Deliver seamless invoice processing accelerating accounts payable" },
    ],
  },
  "treasury-cash-insight-agent": {
    trigger: "Cash position updated or treasury report requested",
    steps: [
      { number: 1, icon: BarChart3, text: "Cash position updated or treasury report requested" },
      { number: 2, icon: Database, text: "Gather cash positions, forecasts, and bank feed data" },
      { number: 3, icon: Search, text: "Enrich with liquidity scenarios and threshold data" },
      { number: 4, icon: BarChart3, text: "Analyze cash positions and liquidity forecasts" },
      { number: 5, icon: AlertCircle, text: "Evaluate anomalies and threshold breaches" },
      { number: 6, icon: FileText, text: "Generate real-time cash summaries and alerts" },
      { number: 7, icon: Send, text: "Deliver treasury insights improving cash optimization" },
    ],
  },
  "compliance-policy-checker": {
    trigger: "Transaction processed or communication sent",
    steps: [
      { number: 1, icon: Shield, text: "Transaction processed or communication sent" },
      { number: 2, icon: Database, text: "Gather transaction data and communication content" },
      { number: 3, icon: Search, text: "Enrich with compliance rules and regulatory requirements" },
      { number: 4, icon: BarChart3, text: "Analyze transactions and communications for violations" },
      { number: 5, icon: AlertCircle, text: "Evaluate risk level and recommend remediation actions" },
      { number: 6, icon: FileText, text: "Generate compliance reports and escalate high-risk cases" },
      { number: 7, icon: Save, text: "Store compliance evidence reducing regulatory exposure" },
    ],
  },
  // Retail & E-Commerce Suite
  "product-search-discovery-agent": {
    trigger: "Customer searches for product or browses catalog",
    steps: [
      { number: 1, icon: Search, text: "Customer searches for product or browses catalog" },
      { number: 2, icon: Database, text: "Gather search query and product catalog data" },
      { number: 3, icon: Search, text: "Enrich with product attributes and recommendation engines" },
      { number: 4, icon: BarChart3, text: "Analyze search intent and match to relevant products" },
      { number: 5, icon: FileText, text: "Generate product results with comparisons and guided discovery" },
      { number: 6, icon: Send, text: "Deliver conversational product search reducing browsing time" },
    ],
  },
  "cart-checkout-assistant": {
    trigger: "Customer adds item to cart or initiates checkout",
    steps: [
      { number: 1, icon: ShoppingBag, text: "Customer adds item to cart or initiates checkout" },
      { number: 2, icon: Database, text: "Gather cart contents and customer information" },
      { number: 3, icon: Search, text: "Enrich with shipping options and payment methods" },
      { number: 4, icon: BarChart3, text: "Analyze cart and suggest upsells or answer questions" },
      { number: 5, icon: FileText, text: "Generate real-time cart experience via chat" },
      { number: 6, icon: Send, text: "Deliver checkout assistance reducing abandonment and recovering sales" },
    ],
  },
  "order-management-helper": {
    trigger: "Order placed or status update needed",
    steps: [
      { number: 1, icon: ShoppingBag, text: "Order placed or status update needed" },
      { number: 2, icon: Database, text: "Gather order details and logistics tracking data" },
      { number: 3, icon: Search, text: "Enrich with logistics APIs and carrier information" },
      { number: 4, icon: BarChart3, text: "Analyze order status and sync across channels" },
      { number: 5, icon: FileText, text: "Generate order tracking and status updates" },
      { number: 6, icon: Send, text: "Deliver live order updates improving satisfaction" },
    ],
  },
  "in-store-associate-co-pilot": {
    trigger: "Store associate needs product information or customer assistance",
    steps: [
      { number: 1, icon: Users, text: "Store associate needs product information or customer assistance" },
      { number: 2, icon: Database, text: "Gather product details, inventory, and customer scenario" },
      { number: 3, icon: Search, text: "Enrich with policies and cross-sell recommendations" },
      { number: 4, icon: BarChart3, text: "Analyze customer needs and suggest recommendations" },
      { number: 5, icon: FileText, text: "Generate product information and service suggestions" },
      { number: 6, icon: Send, text: "Deliver instant access elevating in-store customer experience" },
    ],
  },
  "pricing-promotion-advisor": {
    trigger: "Promotion planning initiated or competitor pricing updated",
    steps: [
      { number: 1, icon: TrendingUp, text: "Promotion planning initiated or competitor pricing updated" },
      { number: 2, icon: Database, text: "Gather demand elasticity and competitor pricing data" },
      { number: 3, icon: Search, text: "Enrich with margin data and historical promotion performance" },
      { number: 4, icon: BarChart3, text: "Analyze optimal promotions and simulate margin impact" },
      { number: 5, icon: FileText, text: "Generate promotion recommendations maximizing revenue" },
      { number: 6, icon: Send, text: "Deliver pricing insights protecting profitability" },
    ],
  },
  "returns-intelligence-agent": {
    trigger: "Return processed or return reason submitted",
    steps: [
      { number: 1, icon: RefreshCw, text: "Return processed or return reason submitted" },
      { number: 2, icon: Database, text: "Gather return reasons and product data" },
      { number: 3, icon: Search, text: "Enrich with product quality data and customer feedback" },
      { number: 4, icon: BarChart3, text: "Analyze return patterns and detect quality or sizing issues" },
      { number: 5, icon: FileText, text: "Generate policy and product page improvement recommendations" },
      { number: 6, icon: Save, text: "Store insights reducing future returns and improving quality" },
    ],
  },
  "store-operations-helper": {
    trigger: "Daily checklist due or audit required",
    steps: [
      { number: 1, icon: CheckCircle, text: "Daily checklist due or audit required" },
      { number: 2, icon: Database, text: "Gather checklist items and store location data" },
      { number: 3, icon: Search, text: "Enrich with compliance requirements and task assignments" },
      { number: 4, icon: BarChart3, text: "Analyze checklist completion and identify compliance gaps" },
      { number: 5, icon: FileText, text: "Generate automated checklists and highlight exceptions" },
      { number: 6, icon: Send, text: "Deliver operations automation ensuring consistent store operations" },
    ],
  },
  "loyalty-rewards-assistant": {
    trigger: "Customer queries loyalty program or redemption requested",
    steps: [
      { number: 1, icon: Star, text: "Customer queries loyalty program or redemption requested" },
      { number: 2, icon: Database, text: "Gather loyalty tier data and customer history" },
      { number: 3, icon: Search, text: "Enrich with rewards catalog and personalized offers" },
      { number: 4, icon: BarChart3, text: "Analyze customer segment and recommend re-engagement offers" },
      { number: 5, icon: FileText, text: "Generate loyalty explanations and personalized offers" },
      { number: 6, icon: Send, text: "Deliver loyalty support increasing retention and lifetime value" },
    ],
  },
  "visual-merchandising-planner": {
    trigger: "Planogram update needed or performance data updated",
    steps: [
      { number: 1, icon: LayoutGrid, text: "Planogram update needed or performance data updated" },
      { number: 2, icon: Database, text: "Gather performance data and planogram information" },
      { number: 3, icon: Search, text: "Enrich with sales per square foot and display rotation data" },
      { number: 4, icon: BarChart3, text: "Analyze performance and recommend planogram improvements" },
      { number: 5, icon: FileText, text: "Generate store-level guidelines and display rotation tasks" },
      { number: 6, icon: Send, text: "Deliver merchandising recommendations improving shelf utilization" },
    ],
  },
  "voice-commerce-agent": {
    trigger: "Voice shopping request or reorder initiated",
    steps: [
      { number: 1, icon: Mic, text: "Voice shopping request or reorder initiated" },
      { number: 2, icon: Database, text: "Gather voice command and customer purchase history" },
      { number: 3, icon: Search, text: "Enrich with product catalog and inventory data" },
      { number: 4, icon: BarChart3, text: "Analyze voice intent and build shopping basket" },
      { number: 5, icon: FileText, text: "Generate voice-based shopping experience with checkout" },
      { number: 6, icon: Send, text: "Deliver convenience-first shopping via voice" },
    ],
  },
  // Healthcare Suite
  "patient-access-assistant": {
    trigger: "Appointment booking requested or rescheduling needed",
    steps: [
      { number: 1, icon: Calendar, text: "Appointment booking requested or rescheduling needed" },
      { number: 2, icon: Database, text: "Gather patient information and appointment preferences" },
      { number: 3, icon: Search, text: "Enrich with provider availability and insurance verification" },
      { number: 4, icon: BarChart3, text: "Analyze eligibility and schedule optimal appointment" },
      { number: 5, icon: FileText, text: "Generate appointment confirmation and pre-visit information collection" },
      { number: 6, icon: Send, text: "Deliver automated reminders improving patient access" },
    ],
  },
  "care-navigation-agent": {
    trigger: "Patient discharged or care pathway guidance needed",
    steps: [
      { number: 1, icon: Heart, text: "Patient discharged or care pathway guidance needed" },
      { number: 2, icon: Database, text: "Gather discharge instructions and patient information" },
      { number: 3, icon: Search, text: "Enrich with care pathways and follow-up resources" },
      { number: 4, icon: BarChart3, text: "Analyze patient needs and detect risk signals" },
      { number: 5, icon: AlertCircle, text: "Evaluate risk level and escalate to care coordinators if needed" },
      { number: 6, icon: FileText, text: "Generate care guidance and follow-up resource recommendations" },
      { number: 7, icon: Send, text: "Deliver care navigation reducing readmissions" },
    ],
  },
  "benefits-coverage-explainer": {
    trigger: "Patient questions coverage or authorization requirements",
    steps: [
      { number: 1, icon: HelpCircle, text: "Patient questions coverage or authorization requirements" },
      { number: 2, icon: Database, text: "Gather patient insurance information and coverage data" },
      { number: 3, icon: Search, text: "Enrich with payer systems and eligibility APIs" },
      { number: 4, icon: BarChart3, text: "Analyze coverage and calculate out-of-pocket costs" },
      { number: 5, icon: FileText, text: "Generate coverage explanations and cost estimates" },
      { number: 6, icon: Send, text: "Deliver benefits clarity reducing billing confusion" },
    ],
  },
  "provider-support-co-pilot": {
    trigger: "Clinician needs protocol access or patient encounter approaching",
    steps: [
      { number: 1, icon: Stethoscope, text: "Clinician needs protocol access or patient encounter approaching" },
      { number: 2, icon: Database, text: "Gather patient history and clinical guidelines" },
      { number: 3, icon: Search, text: "Enrich with order sets and reference content" },
      { number: 4, icon: BarChart3, text: "Analyze patient history and highlight risks" },
      { number: 5, icon: FileText, text: "Generate patient summary and protocol recommendations" },
      { number: 6, icon: Send, text: "Deliver provider support improving care quality" },
    ],
  },
  "clinical-documentation-assistant": {
    trigger: "Clinical notes or dictation completed",
    steps: [
      { number: 1, icon: FileText, text: "Clinical notes or dictation completed" },
      { number: 2, icon: Database, text: "Gather notes and transcripts" },
      { number: 3, icon: Search, text: "Enrich with coding requirements and billing guidelines" },
      { number: 4, icon: BarChart3, text: "Analyze notes and convert to structured documentation" },
      { number: 5, icon: AlertCircle, text: "Flag missing elements needed for billing and quality reporting" },
      { number: 6, icon: FileText, text: "Generate coded clinical documentation" },
      { number: 7, icon: Save, text: "Store documentation improving coding accuracy" },
    ],
  },
  "prior-authorization-orchestrator": {
    trigger: "Prior authorization required for procedure or medication",
    steps: [
      { number: 1, icon: Shield, text: "Prior authorization required for procedure or medication" },
      { number: 2, icon: Database, text: "Gather required documentation and authorization criteria" },
      { number: 3, icon: Search, text: "Enrich with payer portals and approval workflows" },
      { number: 4, icon: BarChart3, text: "Analyze requirements and collect documentation automatically" },
      { number: 5, icon: FileText, text: "Generate authorization request and submit to payer" },
      { number: 6, icon: Send, text: "Deliver real-time approval tracking accelerating care delivery" },
    ],
  },
  "population-health-insight-agent": {
    trigger: "Population health data updated or care gap identified",
    steps: [
      { number: 1, icon: BarChart3, text: "Population health data updated or care gap identified" },
      { number: 2, icon: Database, text: "Gather patient cohort data and care gap information" },
      { number: 3, icon: Search, text: "Enrich with risk stratification and engagement scripts" },
      { number: 4, icon: BarChart3, text: "Analyze high-risk cohorts and prioritize outreach" },
      { number: 5, icon: FileText, text: "Generate prioritized patient lists and engagement recommendations" },
      { number: 6, icon: Send, text: "Deliver population health insights improving quality scores" },
    ],
  },
  "clinical-trial-matchmaker": {
    trigger: "Patient eligible for clinical trial or trial recruitment needed",
    steps: [
      { number: 1, icon: Search, text: "Patient eligible for clinical trial or trial recruitment needed" },
      { number: 2, icon: Database, text: "Gather patient medical history and trial criteria" },
      { number: 3, icon: Search, text: "Enrich with trial registries and protocol databases" },
      { number: 4, icon: BarChart3, text: "Analyze eligibility and match patients to trials" },
      { number: 5, icon: FileText, text: "Generate pre-screening summaries for research teams" },
      { number: 6, icon: Send, text: "Deliver trial matching accelerating recruitment" },
    ],
  },
  "pharmacy-medication-helper": {
    trigger: "Medication question asked or refill requested",
    steps: [
      { number: 1, icon: Heart, text: "Medication question asked or refill requested" },
      { number: 2, icon: Database, text: "Gather medication information and patient history" },
      { number: 3, icon: Search, text: "Enrich with drug databases and interaction checkers" },
      { number: 4, icon: BarChart3, text: "Analyze medication questions and check interactions" },
      { number: 5, icon: FileText, text: "Generate medication answers and route refill requests" },
      { number: 6, icon: Send, text: "Deliver pharmacy support improving adherence and safety" },
    ],
  },
  "insurance-claims-query-agent": {
    trigger: "Provider queries claim status or denial received",
    steps: [
      { number: 1, icon: FileText, text: "Provider queries claim status or denial received" },
      { number: 2, icon: Database, text: "Gather claim data and payer information" },
      { number: 3, icon: Search, text: "Enrich with claims clearinghouses and denial reasons" },
      { number: 4, icon: BarChart3, text: "Analyze claim status and denial reasons" },
      { number: 5, icon: FileText, text: "Generate claim status summary and correction recommendations" },
      { number: 6, icon: Send, text: "Deliver claims support reducing revenue cycle delays" },
    ],
  },
  "nursing-station-automation": {
    trigger: "Nursing task due or shift change approaching",
    steps: [
      { number: 1, icon: Clock, text: "Nursing task due or shift change approaching" },
      { number: 2, icon: Database, text: "Gather vitals data and patient status information" },
      { number: 3, icon: Search, text: "Enrich with task assignments and priority patient needs" },
      { number: 4, icon: BarChart3, text: "Analyze patient needs and coordinate shift handoffs" },
      { number: 5, icon: FileText, text: "Generate automated workflows for vitals logging and handoffs" },
      { number: 6, icon: AlertCircle, text: "Alert clinicians to priority patient needs" },
      { number: 7, icon: Send, text: "Deliver nursing automation improving care efficiency" },
    ],
  },
  // Cross-Industry Analytics Suite
  "sentiment-emotion-analyzer": {
    trigger: "Text, review, or transcript data received",
    steps: [
      { number: 1, icon: MessageSquare, text: "Text, review, or transcript data received" },
      { number: 2, icon: Database, text: "Gather text data from surveys, reviews, and transcripts" },
      { number: 3, icon: Search, text: "Enrich with historical sentiment data and segment information" },
      { number: 4, icon: BarChart3, text: "Analyze emotions and sentiment polarity with nuance" },
      { number: 5, icon: FileText, text: "Generate sentiment scores and extract themes across segments" },
      { number: 6, icon: Save, text: "Store insights enabling data-driven product decisions" },
    ],
  },
  "vehicle-damage-image-analyzer": {
    trigger: "Vehicle damage image uploaded for insurance claim",
    steps: [
      { number: 1, icon: Eye, text: "Vehicle damage image uploaded for insurance claim" },
      { number: 2, icon: Database, text: "Gather uploaded images and claim information" },
      { number: 3, icon: Search, text: "Enrich with repair databases and cost estimation models" },
      { number: 4, icon: BarChart3, text: "Analyze damage and identify impacted parts using computer vision" },
      { number: 5, icon: FileText, text: "Generate repair cost range estimates automatically" },
      { number: 6, icon: Send, text: "Deliver damage assessment speeding up claims processing" },
    ],
  },
  "faq-document-generator": {
    trigger: "FAQ content needed or spreadsheet data provided",
    steps: [
      { number: 1, icon: FileText, text: "FAQ content needed or spreadsheet data provided" },
      { number: 2, icon: Database, text: "Gather spreadsheet data or website content" },
      { number: 3, icon: Search, text: "Enrich with SEO best practices and knowledge base structure" },
      { number: 4, icon: BarChart3, text: "Analyze content and generate structured FAQ pairs" },
      { number: 5, icon: FileText, text: "Generate SEO-optimized question-answer pairs" },
      { number: 6, icon: Save, text: "Store FAQ content reducing manual authoring effort" },
    ],
  },
  "document-risk-analyzer": {
    trigger: "Contract or project document uploaded for review",
    steps: [
      { number: 1, icon: FileText, text: "Contract or project document uploaded for review" },
      { number: 2, icon: Database, text: "Gather document content and project data" },
      { number: 3, icon: Search, text: "Enrich with risk scoring engines and dependency data" },
      { number: 4, icon: BarChart3, text: "Analyze documents to uncover risks and dependencies" },
      { number: 5, icon: AlertCircle, text: "Rank threats by likelihood and business impact" },
      { number: 6, icon: FileText, text: "Generate risk analysis report with mitigation recommendations" },
      { number: 7, icon: Send, text: "Deliver risk insights helping leaders mitigate issues early" },
    ],
  },
  "meeting-call-summarizer": {
    trigger: "Meeting or call recording completed",
    steps: [
      { number: 1, icon: Phone, text: "Meeting or call recording completed" },
      { number: 2, icon: Database, text: "Gather meeting recording and transcript data" },
      { number: 3, icon: Search, text: "Enrich with transcription engines and participant information" },
      { number: 4, icon: BarChart3, text: "Analyze transcript and extract decisions, owners, and next steps" },
      { number: 5, icon: FileText, text: "Generate concise, action-oriented summary automatically" },
      { number: 6, icon: Send, text: "Deliver meeting summaries improving accountability" },
    ],
  },
  "survey-response-synthesizer": {
    trigger: "Survey responses collected or analysis requested",
    steps: [
      { number: 1, icon: MessageSquare, text: "Survey responses collected or analysis requested" },
      { number: 2, icon: Database, text: "Gather open-ended survey responses" },
      { number: 3, icon: Search, text: "Enrich with NLP engines and visualization tools" },
      { number: 4, icon: BarChart3, text: "Analyze responses and cluster dominant themes" },
      { number: 5, icon: FileText, text: "Generate dashboards and executive-ready insight summaries" },
      { number: 6, icon: Send, text: "Deliver synthesized feedback turning qualitative into measurable outcomes" },
    ],
  },
  "knowledge-graph-builder": {
    trigger: "Document added or knowledge graph update needed",
    steps: [
      { number: 1, icon: Network, text: "Document added or knowledge graph update needed" },
      { number: 2, icon: Database, text: "Gather documents from SharePoint, Confluence, and databases" },
      { number: 3, icon: Search, text: "Enrich with vector databases and NLP processing" },
      { number: 4, icon: BarChart3, text: "Analyze documents and build unified knowledge graph" },
      { number: 5, icon: FileText, text: "Generate semantic connections and context-aware reasoning" },
      { number: 6, icon: Save, text: "Store knowledge graph creating organization-wide intelligence layer" },
    ],
  },
  "document-redaction-pii-scrubber": {
    trigger: "Document prepared for external sharing",
    steps: [
      { number: 1, icon: Shield, text: "Document prepared for external sharing" },
      { number: 2, icon: Database, text: "Gather document content and privacy rules" },
      { number: 3, icon: Search, text: "Enrich with DLP tools and compliance engines" },
      { number: 4, icon: BarChart3, text: "Analyze document and detect sensitive PII data" },
      { number: 5, icon: FileText, text: "Generate redacted document with masked sensitive information" },
      { number: 6, icon: Save, text: "Store redacted version reducing breach risk and ensuring compliance" },
    ],
  },
  "multimodal-compliance-reviewer": {
    trigger: "Text, image, audio, or transcript submitted for compliance review",
    steps: [
      { number: 1, icon: Eye, text: "Text, image, audio, or transcript submitted for compliance review" },
      { number: 2, icon: Database, text: "Gather multimodal content and compliance policies" },
      { number: 3, icon: Search, text: "Enrich with risk scoring and legal review tools" },
      { number: 4, icon: BarChart3, text: "Analyze content across formats against compliance policies" },
      { number: 5, icon: FileText, text: "Generate audit-ready evidence and compliance reports" },
      { number: 6, icon: Save, text: "Store compliance evidence simplifying regulatory checks" },
    ],
  },
  "workflow-orchestration-agent": {
    trigger: "Multi-agent workflow initiated or system integration needed",
    steps: [
      { number: 1, icon: Zap, text: "Multi-agent workflow initiated or system integration needed" },
      { number: 2, icon: Database, text: "Gather workflow requirements and agent capabilities" },
      { number: 3, icon: Search, text: "Enrich with routing logic and retry policies" },
      { number: 4, icon: BarChart3, text: "Analyze workflow and optimize routing and human-in-the-loop steps" },
      { number: 5, icon: FileText, text: "Generate end-to-end automated workflow connections" },
      { number: 6, icon: Send, text: "Deliver workflow orchestration enabling complex automation" },
    ],
  },
  // Community & Innovation Suite
  "template-builder-for-community": {
    trigger: "Agent template creation requested or recipe shared",
    steps: [
      { number: 1, icon: FileText, text: "Agent template creation requested or recipe shared" },
      { number: 2, icon: Database, text: "Gather reusable recipes and prompt templates" },
      { number: 3, icon: Search, text: "Enrich with version control and governance controls" },
      { number: 4, icon: BarChart3, text: "Analyze template and compose new agent from reusable components" },
      { number: 5, icon: FileText, text: "Generate agent template ready for community gallery" },
      { number: 6, icon: Save, text: "Publish to curated gallery democratizing agent creation" },
    ],
  },
  "data-to-dashboard-recipe": {
    trigger: "CSV or spreadsheet data provided for dashboard creation",
    steps: [
      { number: 1, icon: BarChart3, text: "CSV or spreadsheet data provided for dashboard creation" },
      { number: 2, icon: Database, text: "Gather spreadsheet data and metrics definitions" },
      { number: 3, icon: Search, text: "Enrich with BI tools and visualization templates" },
      { number: 4, icon: BarChart3, text: "Analyze data and transform into dashboard structure" },
      { number: 5, icon: FileText, text: "Generate auto-refreshed dashboard with documented assumptions" },
      { number: 6, icon: Save, text: "Store dashboard enabling self-serve analytics" },
    ],
  },
  "talk-to-your-docs-agent": {
    trigger: "Natural language question asked over documents",
    steps: [
      { number: 1, icon: Search, text: "Natural language question asked over documents" },
      { number: 2, icon: Database, text: "Gather question and uploaded files or web links" },
      { number: 3, icon: Search, text: "Enrich with vector databases and embeddings" },
      { number: 4, icon: BarChart3, text: "Analyze question and search document library semantically" },
      { number: 5, icon: FileText, text: "Generate answer with citations back to source snippets" },
      { number: 6, icon: Send, text: "Deliver conversational knowledge system from document libraries" },
    ],
  },
  "workflow-explainer-bot": {
    trigger: "Workflow explanation requested or new team member onboarded",
    steps: [
      { number: 1, icon: HelpCircle, text: "Workflow explanation requested or new team member onboarded" },
      { number: 2, icon: Database, text: "Gather workflow definitions and documentation" },
      { number: 3, icon: Search, text: "Enrich with visualization engines and diagram tools" },
      { number: 4, icon: BarChart3, text: "Analyze workflow and visualize steps and dependencies" },
      { number: 5, icon: FileText, text: "Generate simple language explanation with interactive visualization" },
      { number: 6, icon: Send, text: "Deliver workflow explanations accelerating onboarding" },
    ],
  },
  "personal-research-assistant": {
    trigger: "Research request submitted or web search initiated",
    steps: [
      { number: 1, icon: Search, text: "Research request submitted or web search initiated" },
      { number: 2, icon: Database, text: "Gather research topic and requirements" },
      { number: 3, icon: Search, text: "Enrich with web search APIs and citation managers" },
      { number: 4, icon: BarChart3, text: "Analyze findings and structure research notes" },
      { number: 5, icon: FileText, text: "Generate briefs, outlines, and slide drafts from findings" },
      { number: 6, icon: Save, text: "Store research with source tracking speeding up learning" },
    ],
  },
  "prompt-engineering-coach": {
    trigger: "Prompt design requested or agent recipe needs improvement",
    steps: [
      { number: 1, icon: FileText, text: "Prompt design requested or agent recipe needs improvement" },
      { number: 2, icon: Database, text: "Gather prompt or recipe and evaluation criteria" },
      { number: 3, icon: Search, text: "Enrich with prompt patterns and safety guards" },
      { number: 4, icon: BarChart3, text: "Analyze prompt quality and suggest improvements" },
      { number: 5, icon: FileText, text: "Generate improved prompt with patterns and evaluation strategies" },
      { number: 6, icon: Send, text: "Deliver prompt coaching improving agent quality and consistency" },
    ],
  },
  "code-refactor-review-agent": {
    trigger: "Code commit pushed or pull request opened",
    steps: [
      { number: 1, icon: Code, text: "Code commit pushed or pull request opened" },
      { number: 2, icon: Database, text: "Gather code changes and repository data" },
      { number: 3, icon: Search, text: "Enrich with code analysis tools and linting rules" },
      { number: 4, icon: BarChart3, text: "Analyze code for bugs, security risks, and style issues" },
      { number: 5, icon: FileText, text: "Generate refactor suggestions with examples and explanations" },
      { number: 6, icon: Send, text: "Deliver code review improving quality and shared knowledge" },
    ],
  },
  "analytics-query-co-pilot": {
    trigger: "Natural language analytics question asked",
    steps: [
      { number: 1, icon: BarChart3, text: "Natural language analytics question asked" },
      { number: 2, icon: Database, text: "Gather question and data warehouse schema" },
      { number: 3, icon: Search, text: "Enrich with metrics repositories and query optimization tools" },
      { number: 4, icon: BarChart3, text: "Analyze question and convert to SQL or BI query" },
      { number: 5, icon: CheckCircle, text: "Validate metric definitions and preview sample outputs" },
      { number: 6, icon: FileText, text: "Generate accurate query enabling non-technical analytics access" },
      { number: 7, icon: Send, text: "Deliver query co-pilot enabling safe analytics access" },
    ],
  },
  "workflow-cost-optimizer": {
    trigger: "Workflow cost analysis requested or usage data updated",
    steps: [
      { number: 1, icon: BarChart3, text: "Workflow cost analysis requested or usage data updated" },
      { number: 2, icon: Database, text: "Gather workflow usage logs and cloud billing data" },
      { number: 3, icon: Search, text: "Enrich with model costs and infrastructure pricing" },
      { number: 4, icon: BarChart3, text: "Analyze costs including model usage, APIs, and infrastructure" },
      { number: 5, icon: FileText, text: "Generate cost estimates and optimization recommendations" },
      { number: 6, icon: Send, text: "Deliver cost insights maximizing ROI of AI deployments" },
    ],
  },
  "multi-agent-recipe-hub-rube-style": {
    trigger: "Multi-agent recipe execution requested or workflow composed",
    steps: [
      { number: 1, icon: Zap, text: "Multi-agent recipe execution requested or workflow composed" },
      { number: 2, icon: Database, text: "Gather recipe definition and agent capabilities" },
      { number: 3, icon: Search, text: "Enrich with orchestration engine and version control" },
      { number: 4, icon: BarChart3, text: "Analyze recipe and chain agents end-to-end" },
      { number: 5, icon: FileText, text: "Generate visual composition and execute reusable recipes" },
      { number: 6, icon: Send, text: "Deliver powerful no-code enterprise automation" },
    ],
  },
}

// Helper function to get flow for an agent
export function getAgentFlow(agentId: string): AgentFlow | undefined {
  return agentFlows[agentId]
}

