export const AGENT_BRAND_INTEGRATIONS: Record<string, string[]> = {
  "Proposal Reviewer": ["Salesforce", "HubSpot", "Gmail", "Outlook", "Google Drive", "SharePoint"],
  "Lead Analyzer": ["Salesforce", "HubSpot", "Google Sheets", "Slack", "Microsoft Teams"],
  "RFP Response Automation": ["Salesforce", "Google Drive", "SharePoint", "Gmail", "Outlook"],
  "Deal Desk Assistant": ["Salesforce", "Slack", "Microsoft Teams"],
  "Account Briefing Agent": ["Salesforce", "Zendesk", "Freshdesk", "Google Search Console", "Gmail", "Outlook"],
  "Competitive Battlecard Agent": ["Confluence", "Notion", "Google Search API", "Salesforce", "Slack"],
  "Renewal & Upsell Advisor": ["Salesforce", "Stripe", "Chargebee"],
  "Sales Email Drafter": ["Salesforce", "Outreach", "Salesloft", "Gmail", "Outlook"],
  "Lead Routing Orchestrator": ["Salesforce", "HubSpot", "Slack", "Microsoft Teams"],
  "Partner Sales Co-Pilot": ["Salesforce", "Slack"],
  "AI Sales SDR": ["Salesforce", "Slack"],
  "AI Sales Coach": ["Salesforce", "Slack"],
  "Campaign Planner Agent": ["Google Ads", "Meta Ads", "LinkedIn Ads", "Google Sheets", "Jira"],
  "Content Brief Generator": ["Google Search Console", "SEMrush", "Ahrefs", "Notion"],
  "Social Media Manager": ["LinkedIn Ads", "Meta Ads", "Hootsuite", "Buffer"],
  "Brand Sentiment Analyzer": ["SurveyMonkey"],
  "Event & Webinar Concierge": ["Eventbrite", "HubSpot", "Salesforce", "Microsoft Teams"],
  "Survey & NPS Orchestrator": ["SurveyMonkey", "Typeform", "Zendesk", "Freshdesk", "Slack", "Microsoft Teams"],
  "Product Launch Assistant": ["Jira", "Notion", "Slack", "Microsoft Teams"],
  "ABM Engagement Agent": ["Salesforce", "Outreach", "Salesloft", "LinkedIn Ads"],
  "SEO Health Monitor": ["Google Search Console", "Ahrefs", "SEMrush", "Jira"],
  "Omni-Channel Support Agent": ["Zendesk", "Freshdesk", "Salesforce Service", "WhatsApp"],
  "Ticket Triage & Routing": ["Zendesk", "ServiceNow", "Freshdesk", "Jira Service Management"],
  "Order Status & Returns Agent": ["Shopify", "BigCommerce", "Zendesk"],
  "Knowledge-Base Curator": ["Zendesk Guide", "Confluence", "Notion"],
  "Feedback & Complaint Resolver": ["Zendesk", "SurveyMonkey", "Slack"],
  "Subscription & Billing Helper": ["Stripe", "Chargebee", "Recurly"],
  "Multilingual Support Translator": ["Zendesk", "Freshdesk", "Slack", "Microsoft Teams"],
  "Proactive Outage Communicator": ["Zendesk"],
  "Community Forum Moderator": ["Discourse", "Khoros", "Reddit", "Slack Communities"],
  "Leave & Absence Assistant": ["BambooHR", "Workday", "UKG"],
  "Resume Screener Agent": ["Workday"],
  "Interview Intelligence Agent": ["Microsoft Teams"],
  "Onboarding Concierge": ["Slack"],
  "Policy Q&A Assistant": ["Slack", "Microsoft Teams"],
  "Time & Attendance Helper": ["Slack"],
  "Performance Review Co-Pilot": ["Slack"],
  "Learning Path Advisor": ["Google Calendar"],
  "HR Case Manager": ["Slack"],
  "IT Helpdesk Virtual Agent": ["ServiceNow", "Jira Service Management"],
  "IT Request Fulfillment Agent": ["ServiceNow", "Okta", "Azure AD", "Slack"],
  "Password Reset & Unlock Agent": ["Active Directory", "Okta", "Azure AD"],
  "Incident Command Assistant": ["Slack", "Microsoft Teams", "Jira"],
  "Change Request Co-Pilot": ["ServiceNow", "Jira", "GitHub", "GitLab"],
  "Asset & License Tracker": ["ServiceNow"],
  "Knowledge Search for IT": ["Confluence", "SharePoint"],
  "DevOps Release Assistant": ["Jenkins", "GitHub Actions", "Jira", "Kubernetes"],
  "Access Review Agent": ["Okta", "Azure AD"],
  "ITSM Analytics Analyst": ["ServiceNow", "Jira"],
  "Expense Management Assistant": ["SAP Concur", "Expensify"],
  "Product Search & Discovery Agent": ["Shopify", "BigCommerce"],
  "Order Management Helper": ["Shopify"],
  "Loyalty & Rewards Assistant": ["Shopify"],
  "FAQ Document Generator": ["Google Sheets"],
  "Document Risk Analyzer": ["SharePoint", "Google Drive"],
  "Meeting & Call Summarizer": ["Microsoft Teams", "Slack"],
  "Survey Response Synthesizer": ["SurveyMonkey", "Typeform"],
  "Knowledge Graph Builder": ["SharePoint", "Confluence"],
  "Template Builder for Community": ["Slack", "Discord"],
  "Data-to-Dashboard Recipe": ["Google Sheets", "Excel"],
  "Code Refactor & Review Agent": ["GitHub", "GitLab"],
};
