// Comprehensive integrations data for all tools
export interface Integration {
  id: string
  name: string
  provider: string
  category: string
  description: string
  capabilities: string[]
  iconColor?: string
  iconBg?: string
  logo?: string
  industries?: string[]
  functions?: string[]
  useCases?: string[]
}

const baseIntegrations: Integration[] = [
  // CRM & Sales Platforms
  {
    id: "salesforce",
    name: "Salesforce",
    provider: "Salesforce Inc.",
    category: "CRM & Sales",
    description: "Salesforce is a cloud-based customer relationship management platform that helps businesses manage customer interactions, sales processes, and marketing campaigns.",
    capabilities: [
      "CREATE CONTACT",
      "UPDATE CONTACT",
      "DELETE CONTACT",
      "GET CONTACT",
      "LIST CONTACTS",
      "CREATE LEAD",
      "UPDATE LEAD",
      "CONVERT LEAD",
      "CREATE OPPORTUNITY",
      "UPDATE OPPORTUNITY",
      "GET OPPORTUNITY",
      "LIST OPPORTUNITIES",
      "CREATE ACCOUNT",
      "UPDATE ACCOUNT",
      "GET ACCOUNT",
      "LIST ACCOUNTS",
      "CREATE CASE",
      "UPDATE CASE",
      "GET CASE",
      "LIST CASES",
    ],
    iconColor: "bg-blue-600",
    logo: "/integration-logos/salesforce (1).png",
    industries: ["Technology", "Finance", "Retail", "E-Commerce", "Professional Services", "Healthcare", "Manufacturing"],
    functions: ["Sales", "Marketing", "Customer Support"],
    useCases: ["Team Performance", "Team Productivity", "Technical Communication"],
  },
  {
    id: "hubspot",
    name: "HubSpot",
    provider: "HubSpot Inc.",
    category: "CRM & Sales",
    description: "HubSpot is an all-in-one inbound marketing, sales, and service platform that helps businesses attract visitors, convert leads, and close customers.",
    industries: ["Technology", "Retail", "E-Commerce", "Professional Services", "Media & Entertainment"],
    functions: ["Sales", "Marketing", "Customer Support"],
    useCases: ["Team Performance", "Team Productivity", "Website Management"],
    capabilities: [
      "CREATE CONTACT",
      "UPDATE CONTACT",
      "GET CONTACT",
      "LIST CONTACTS",
      "CREATE DEAL",
      "UPDATE DEAL",
      "GET DEAL",
      "LIST DEALS",
      "CREATE COMPANY",
      "UPDATE COMPANY",
      "GET COMPANY",
      "LIST COMPANIES",
      "CREATE TICKET",
      "UPDATE TICKET",
      "GET TICKET",
      "LIST TICKETS",
    ],
    iconColor: "bg-orange-500",
    logo: "/integration-logos/hubspot.png",
  },
  {
    id: "outreach",
    name: "Outreach",
    provider: "Outreach.io",
    category: "CRM & Sales",
    description: "Outreach is a sales engagement platform that helps sales teams automate and personalize their outreach efforts.",
    capabilities: [
      "CREATE SEQUENCE",
      "UPDATE SEQUENCE",
      "GET SEQUENCE",
      "LIST SEQUENCES",
      "CREATE PROSPECT",
      "UPDATE PROSPECT",
      "GET PROSPECT",
      "LIST PROSPECTS",
      "SEND EMAIL",
      "TRACK EMAIL",
      "GET EMAIL METRICS",
    ],
    iconColor: "bg-purple-600",
    logo: "/integration-logos/outreach.png",
  },
  {
    id: "salesloft",
    name: "Salesloft",
    provider: "Salesloft Inc.",
    category: "CRM & Sales",
    description: "Salesloft is a sales engagement platform that helps sales teams connect with prospects and customers more effectively.",
    capabilities: [
      "CREATE CADENCE",
      "UPDATE CADENCE",
      "GET CADENCE",
      "LIST CADENCES",
      "CREATE PERSON",
      "UPDATE PERSON",
      "GET PERSON",
      "LIST PERSONS",
      "SEND EMAIL",
      "TRACK EMAIL",
      "GET EMAIL ANALYTICS",
    ],
    iconColor: "bg-blue-500",
    logo: "/integration-logos/salesloft.png",
  },
  {
    id: "prm",
    name: "PRM",
    provider: "Partner Relationship Management",
    category: "CRM & Sales",
    description: "Partner Relationship Management platforms help manage relationships with channel partners, distributors, and resellers.",
    capabilities: [
      "MANAGE PARTNERS",
      "TRACK DEALS",
      "MANAGE COMMISSIONS",
      "GENERATE REPORTS",
      "MANAGE PROGRAMS",
    ],
    iconColor: "bg-indigo-600",
  },
  {
    id: "cpq",
    name: "CPQ",
    provider: "Configure, Price, Quote",
    category: "CRM & Sales",
    description: "CPQ solutions help sales teams configure products, calculate pricing, and generate accurate quotes quickly.",
    capabilities: [
      "CONFIGURE PRODUCT",
      "CALCULATE PRICE",
      "GENERATE QUOTE",
      "UPDATE QUOTE",
      "SEND QUOTE",
      "TRACK QUOTE",
    ],
    iconColor: "bg-teal-600",
  },
  {
    id: "crm-generic",
    name: "CRM",
    provider: "Generic CRM",
    category: "CRM & Sales",
    description: "Generic CRM platform for managing customer relationships, sales pipelines, and business processes.",
    capabilities: [
      "MANAGE CONTACTS",
      "MANAGE DEALS",
      "TRACK ACTIVITIES",
      "GENERATE REPORTS",
      "MANAGE ACCOUNTS",
    ],
    iconColor: "bg-gray-600",
  },
  {
    id: "marketing-automation",
    name: "Marketing Automation",
    provider: "Marketing Automation Platforms",
    category: "CRM & Sales",
    description: "Marketing automation platforms help automate marketing tasks and workflows to increase efficiency and grow revenue.",
    capabilities: [
      "CREATE CAMPAIGN",
      "UPDATE CAMPAIGN",
      "TRACK CAMPAIGN",
      "MANAGE LEADS",
      "SCORE LEADS",
      "SEND EMAILS",
      "TRACK ENGAGEMENT",
    ],
    iconColor: "bg-pink-600",
  },

  // Email, Calendar & Communication
  {
    id: "gmail",
    name: "Gmail",
    provider: "Google LLC",
    category: "Email & Communication",
    description: "Gmail is Google's email service, featuring spam protection, search functions, and seamless integration with other G Suite apps for productivity.",
    logo: "/integration-logos/gmail.png",
    capabilities: [
      "CREATE EMAIL DRAFT",
      "DELETE DRAFT",
      "DELETE MESSAGE",
      "FETCH EMAILS",
      "FETCH MESSAGE BY MESSAGE ID",
      "GET ATTACHMENT",
      "LIST DRAFTS",
      "MOVE TO TRASH",
      "PATCH LABEL",
      "REPLY TO THREAD",
      "SEARCH PEOPLE",
      "SEND DRAFT",
      "SEND EMAIL",
      "ADD LABEL TO EMAIL",
      "CREATE LABEL",
      "FETCH MESSAGE BY THREAD ID",
      "GET CONTACTS",
      "GET PEOPLE",
      "GET PROFILE",
      "LIST LABELS",
      "LIST THREADS",
      "MODIFY THREAD LABELS",
      "REMOVE LABEL",
    ],
    iconColor: "bg-red-500",
  },
  {
    id: "outlook",
    name: "Outlook",
    provider: "Microsoft Corporation",
    category: "Email & Communication",
    description: "Microsoft Outlook is a personal information manager and email client that helps manage emails, calendars, contacts, and tasks.",
    logo: "/integration-logos/outlook.jpeg",
    capabilities: [
      "SEND EMAIL",
      "READ EMAIL",
      "DELETE EMAIL",
      "CREATE DRAFT",
      "SEND DRAFT",
      "GET ATTACHMENTS",
      "MANAGE FOLDERS",
      "SEARCH EMAILS",
      "GET CONTACTS",
      "CREATE CONTACT",
      "UPDATE CONTACT",
    ],
    iconColor: "bg-blue-500",
  },
  {
    id: "email-generic",
    name: "Email",
    provider: "Generic Email Service",
    category: "Email & Communication",
    description: "Generic email service for sending and receiving emails programmatically.",
    capabilities: [
      "SEND EMAIL",
      "READ EMAIL",
      "DELETE EMAIL",
      "MANAGE FOLDERS",
      "GET ATTACHMENTS",
    ],
    iconColor: "bg-gray-600",
  },
  {
    id: "google-calendar",
    name: "Google Calendar",
    provider: "Google LLC",
    category: "Email & Communication",
    description: "Google Calendar is a time-management and scheduling calendar service that helps organize schedules and coordinate events.",
    logo: "/integration-logos/google-calendar.png",
    capabilities: [
      "CREATE EVENT",
      "UPDATE EVENT",
      "DELETE EVENT",
      "GET EVENT",
      "LIST EVENTS",
      "GET CALENDAR",
      "LIST CALENDARS",
      "CREATE CALENDAR",
      "DELETE CALENDAR",
      "SHARE CALENDAR",
    ],
    iconColor: "bg-blue-500",
  },
  {
    id: "calendars",
    name: "Calendars",
    provider: "Calendar Services",
    category: "Email & Communication",
    description: "Generic calendar service for managing events, meetings, and schedules.",
    capabilities: [
      "CREATE EVENT",
      "UPDATE EVENT",
      "DELETE EVENT",
      "GET EVENT",
      "LIST EVENTS",
      "MANAGE ATTENDEES",
    ],
    iconColor: "bg-indigo-500",
  },
  {
    id: "microsoft-teams",
    name: "Microsoft Teams",
    provider: "Microsoft Corporation",
    category: "Email & Communication",
    description: "Microsoft Teams is a collaboration platform that combines workplace chat, video meetings, file storage, and application integration.",
    logo: "/integration-logos/microsoft teams.png",
    capabilities: [
      "SEND MESSAGE",
      "GET MESSAGES",
      "CREATE CHANNEL",
      "GET CHANNELS",
      "SCHEDULE MEETING",
      "JOIN MEETING",
      "SHARE FILE",
      "GET FILES",
      "MANAGE MEMBERS",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "slack",
    name: "Slack",
    provider: "Slack Technologies",
    category: "Email & Communication",
    description: "Slack is a business communication platform that brings teams together with channels, direct messages, and file sharing.",
    logo: "/integration-logos/slack.png",
    capabilities: [
      "SEND MESSAGE",
      "GET MESSAGES",
      "CREATE CHANNEL",
      "GET CHANNELS",
      "UPLOAD FILE",
      "GET FILES",
      "MANAGE MEMBERS",
      "CREATE THREAD",
      "REPLY TO THREAD",
    ],
    iconColor: "bg-purple-500",
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    provider: "Meta Platforms",
    category: "Email & Communication",
    description: "WhatsApp is a messaging platform that enables businesses to communicate with customers through text, voice, and video.",
    logo: "/integration-logos/whatsapp.png",
    capabilities: [
      "SEND MESSAGE",
      "SEND MEDIA",
      "GET MESSAGES",
      "SEND TEMPLATE",
      "MANAGE CONTACTS",
    ],
    iconColor: "bg-green-500",
  },
  {
    id: "sms",
    name: "SMS",
    provider: "SMS Service Providers",
    category: "Email & Communication",
    description: "SMS service for sending and receiving text messages programmatically.",
    capabilities: [
      "SEND SMS",
      "RECEIVE SMS",
      "GET DELIVERY STATUS",
      "MANAGE CONTACTS",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "ivr",
    name: "IVR",
    provider: "IVR Service Providers",
    category: "Email & Communication",
    description: "Interactive Voice Response systems for automated phone interactions and call routing.",
    capabilities: [
      "MAKE CALL",
      "RECEIVE CALL",
      "PLAY MESSAGE",
      "COLLECT INPUT",
      "ROUTE CALL",
      "RECORD CALL",
    ],
    iconColor: "bg-teal-600",
  },
  {
    id: "messaging-platforms",
    name: "Messaging Platforms",
    provider: "Messaging Services",
    category: "Email & Communication",
    description: "Generic messaging platforms for real-time communication and notifications.",
    capabilities: [
      "SEND MESSAGE",
      "GET MESSAGES",
      "MANAGE CHANNELS",
      "SEND NOTIFICATIONS",
    ],
    iconColor: "bg-gray-600",
  },
  {
    id: "push-notifications",
    name: "Push Notifications",
    provider: "Notification Services",
    category: "Email & Communication",
    description: "Push notification services for sending alerts and updates to mobile and web applications.",
    capabilities: [
      "SEND NOTIFICATION",
      "SCHEDULE NOTIFICATION",
      "TRACK DELIVERY",
      "MANAGE SUBSCRIPTIONS",
    ],
    iconColor: "bg-orange-500",
  },

  // Document, Content & Knowledge Management
  {
    id: "google-drive",
    name: "Google Drive",
    provider: "Google LLC",
    category: "Document & Content",
    description: "Google Drive is a file storage and synchronization service that allows users to store files, share files, and collaborate on documents.",
    logo: "/integration-logos/google drive.png",
    capabilities: [
      "UPLOAD FILE",
      "DOWNLOAD FILE",
      "DELETE FILE",
      "SHARE FILE",
      "GET FILE",
      "LIST FILES",
      "CREATE FOLDER",
      "SEARCH FILES",
      "GET FILE METADATA",
    ],
    iconColor: "bg-blue-500",
  },
  {
    id: "sharepoint",
    name: "SharePoint",
    provider: "Microsoft Corporation",
    category: "Document & Content",
    description: "SharePoint is a web-based collaborative platform that integrates with Microsoft Office for document management and storage.",
    logo: "/integration-logos/sharepoint.svg",
    capabilities: [
      "UPLOAD DOCUMENT",
      "DOWNLOAD DOCUMENT",
      "DELETE DOCUMENT",
      "SHARE DOCUMENT",
      "GET DOCUMENT",
      "LIST DOCUMENTS",
      "SEARCH DOCUMENTS",
      "MANAGE PERMISSIONS",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "confluence",
    name: "Confluence",
    provider: "Atlassian",
    category: "Document & Content",
    description: "Confluence is a collaboration wiki tool used to help teams collaborate and share knowledge effectively.",
    logo: "/integration-logos/Confluence_icon.png",
    capabilities: [
      "CREATE PAGE",
      "UPDATE PAGE",
      "DELETE PAGE",
      "GET PAGE",
      "LIST PAGES",
      "SEARCH PAGES",
      "CREATE SPACE",
      "GET SPACE",
      "LIST SPACES",
      "ADD COMMENT",
      "GET COMMENTS",
    ],
    iconColor: "bg-blue-500",
  },
  {
    id: "notion",
    name: "Notion",
    provider: "Notion Labs",
    category: "Document & Content",
    description: "Notion is an all-in-one workspace for notes, docs, tasks, wikis, and databases.",
    logo: "/integration-logos/notion.png",
    capabilities: [
      "CREATE PAGE",
      "UPDATE PAGE",
      "DELETE PAGE",
      "GET PAGE",
      "LIST PAGES",
      "CREATE DATABASE",
      "QUERY DATABASE",
      "ADD COMMENT",
      "SEARCH CONTENT",
    ],
    iconColor: "bg-gray-900",
  },
  {
    id: "document-management",
    name: "Document Management",
    provider: "Document Management Systems",
    category: "Document & Content",
    description: "Document management systems for storing, organizing, and retrieving documents.",
    capabilities: [
      "UPLOAD DOCUMENT",
      "DOWNLOAD DOCUMENT",
      "DELETE DOCUMENT",
      "SEARCH DOCUMENTS",
      "MANAGE VERSIONS",
      "SET PERMISSIONS",
    ],
    iconColor: "bg-gray-600",
  },
  {
    id: "document-vaults",
    name: "Document Vaults",
    provider: "Document Vault Services",
    category: "Document & Content",
    description: "Secure document vaults for storing sensitive documents with encryption and access controls.",
    capabilities: [
      "STORE DOCUMENT",
      "RETRIEVE DOCUMENT",
      "DELETE DOCUMENT",
      "MANAGE ACCESS",
      "AUDIT ACCESS",
    ],
    iconColor: "bg-indigo-600",
  },
  {
    id: "cms",
    name: "CMS",
    provider: "Content Management Systems",
    category: "Document & Content",
    description: "Content management systems for creating, managing, and publishing digital content.",
    capabilities: [
      "CREATE CONTENT",
      "UPDATE CONTENT",
      "DELETE CONTENT",
      "PUBLISH CONTENT",
      "MANAGE MEDIA",
      "MANAGE USERS",
    ],
    iconColor: "bg-purple-600",
  },
  {
    id: "knowledge-bases",
    name: "Knowledge Bases",
    provider: "Knowledge Base Platforms",
    category: "Document & Content",
    description: "Knowledge base platforms for creating, organizing, and searching documentation and information.",
    capabilities: [
      "CREATE ARTICLE",
      "UPDATE ARTICLE",
      "DELETE ARTICLE",
      "SEARCH ARTICLES",
      "MANAGE CATEGORIES",
      "TRACK VIEWS",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "knowledge-repositories",
    name: "Knowledge Repositories",
    provider: "Knowledge Repository Services",
    category: "Document & Content",
    description: "Knowledge repositories for storing and retrieving organizational knowledge and information.",
    capabilities: [
      "STORE KNOWLEDGE",
      "RETRIEVE KNOWLEDGE",
      "SEARCH KNOWLEDGE",
      "UPDATE KNOWLEDGE",
      "MANAGE VERSIONS",
    ],
    iconColor: "bg-teal-600",
  },
  {
    id: "dam",
    name: "DAM",
    provider: "Digital Asset Management",
    category: "Document & Content",
    description: "Digital Asset Management systems for organizing, storing, and retrieving rich media assets.",
    capabilities: [
      "UPLOAD ASSET",
      "DOWNLOAD ASSET",
      "DELETE ASSET",
      "SEARCH ASSETS",
      "MANAGE METADATA",
      "GENERATE THUMBNAILS",
    ],
    iconColor: "bg-pink-600",
  },

  // Finance, Billing & Payments
  {
    id: "stripe",
    name: "Stripe",
    provider: "Stripe Inc.",
    category: "Finance & Payments",
    description: "Stripe is a payment processing platform that enables businesses to accept payments online and in mobile applications.",
    logo: "/integration-logos/stripe.png",
    capabilities: [
      "PROCESS PAYMENT",
      "CREATE CUSTOMER",
      "UPDATE CUSTOMER",
      "GET CUSTOMER",
      "CREATE SUBSCRIPTION",
      "CANCEL SUBSCRIPTION",
      "GET INVOICE",
      "LIST INVOICES",
      "REFUND PAYMENT",
      "GET PAYMENT",
    ],
    iconColor: "bg-indigo-600",
  },
  {
    id: "chargebee",
    name: "Chargebee",
    provider: "Chargebee Inc.",
    category: "Finance & Payments",
    description: "Chargebee is a subscription billing and revenue management platform for SaaS businesses.",
    logo: "/integration-logos/chargebee.png",
    capabilities: [
      "CREATE SUBSCRIPTION",
      "UPDATE SUBSCRIPTION",
      "CANCEL SUBSCRIPTION",
      "GET SUBSCRIPTION",
      "CREATE INVOICE",
      "GET INVOICE",
      "LIST INVOICES",
      "PROCESS PAYMENT",
      "MANAGE PLANS",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "recurly",
    name: "Recurly",
    provider: "Recurly Inc.",
    category: "Finance & Payments",
    description: "Recurly is a subscription management platform that automates recurring billing and revenue recognition.",
    logo: "/integration-logos/recurly.png",
    capabilities: [
      "CREATE SUBSCRIPTION",
      "UPDATE SUBSCRIPTION",
      "CANCEL SUBSCRIPTION",
      "GET SUBSCRIPTION",
      "CREATE INVOICE",
      "PROCESS PAYMENT",
      "MANAGE PLANS",
    ],
    iconColor: "bg-green-600",
  },
  {
    id: "sap-concur",
    name: "SAP Concur",
    provider: "SAP SE",
    category: "Finance & Payments",
    description: "SAP Concur is an expense management solution that automates travel, expense, and invoice management.",
    logo: "/integration-logos/sap concur.png",
    capabilities: [
      "CREATE EXPENSE",
      "UPDATE EXPENSE",
      "SUBMIT EXPENSE",
      "APPROVE EXPENSE",
      "GET EXPENSE",
      "LIST EXPENSES",
      "CREATE REPORT",
      "GET REPORT",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "expensify",
    name: "Expensify",
    provider: "Expensify Inc.",
    category: "Finance & Payments",
    description: "Expensify is an expense management platform that helps businesses track expenses, receipts, and reimbursements.",
    logo: "/integration-logos/expensify.png",
    capabilities: [
      "CREATE EXPENSE",
      "UPDATE EXPENSE",
      "SUBMIT EXPENSE",
      "APPROVE EXPENSE",
      "GET EXPENSE",
      "LIST EXPENSES",
      "UPLOAD RECEIPT",
      "GET RECEIPT",
    ],
    iconColor: "bg-green-500",
  },
  {
    id: "erp-systems",
    name: "ERP Systems",
    provider: "ERP Providers",
    category: "Finance & Payments",
    description: "Enterprise Resource Planning systems for managing business processes and operations.",
    capabilities: [
      "MANAGE INVENTORY",
      "PROCESS ORDERS",
      "MANAGE FINANCIALS",
      "GENERATE REPORTS",
      "MANAGE SUPPLIERS",
    ],
    iconColor: "bg-gray-600",
  },
  {
    id: "accounts-payable",
    name: "Accounts Payable",
    provider: "AP Systems",
    category: "Finance & Payments",
    description: "Accounts payable systems for managing vendor invoices and payments.",
    capabilities: [
      "PROCESS INVOICE",
      "APPROVE INVOICE",
      "SCHEDULE PAYMENT",
      "GET INVOICE",
      "LIST INVOICES",
      "MANAGE VENDORS",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "payment-gateways",
    name: "Payment Gateways",
    provider: "Payment Gateway Providers",
    category: "Finance & Payments",
    description: "Payment gateway services for processing online payments securely.",
    capabilities: [
      "PROCESS PAYMENT",
      "REFUND PAYMENT",
      "GET PAYMENT",
      "LIST PAYMENTS",
      "MANAGE CARDS",
    ],
    iconColor: "bg-indigo-600",
  },
  {
    id: "corporate-cards",
    name: "Corporate Cards",
    provider: "Corporate Card Providers",
    category: "Finance & Payments",
    description: "Corporate card management platforms for tracking business expenses and managing card programs.",
    capabilities: [
      "GET CARD",
      "LIST CARDS",
      "GET TRANSACTIONS",
      "SET LIMITS",
      "MANAGE USERS",
    ],
    iconColor: "bg-purple-600",
  },
  {
    id: "treasury-management",
    name: "Treasury Management",
    provider: "Treasury Platforms",
    category: "Finance & Payments",
    description: "Treasury management platforms for managing cash, investments, and financial risk.",
    capabilities: [
      "GET CASH POSITION",
      "MANAGE INVESTMENTS",
      "FORECAST CASH",
      "MANAGE RISK",
      "GENERATE REPORTS",
    ],
    iconColor: "bg-teal-600",
  },
  {
    id: "bank-feeds",
    name: "Bank Feeds",
    provider: "Bank Feed Services",
    category: "Finance & Payments",
    description: "Bank feed services for automatically importing bank transactions into accounting systems.",
    capabilities: [
      "SYNC TRANSACTIONS",
      "GET TRANSACTIONS",
      "RECONCILE TRANSACTIONS",
      "MANAGE ACCOUNTS",
    ],
    iconColor: "bg-green-600",
  },

  // Analytics, BI & Data
  {
    id: "analytics-platforms",
    name: "Analytics Platforms",
    provider: "Analytics Providers",
    category: "Analytics & BI",
    description: "Analytics platforms for tracking, analyzing, and visualizing business metrics and user behavior.",
    capabilities: [
      "TRACK EVENT",
      "GET METRICS",
      "CREATE DASHBOARD",
      "GENERATE REPORT",
      "EXPORT DATA",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "bi-tools",
    name: "BI Tools",
    provider: "Business Intelligence Providers",
    category: "Analytics & BI",
    description: "Business intelligence tools for analyzing data and generating insights to support decision-making.",
    capabilities: [
      "CREATE REPORT",
      "UPDATE REPORT",
      "GET REPORT",
      "LIST REPORTS",
      "CREATE DASHBOARD",
      "QUERY DATA",
      "EXPORT DATA",
    ],
    iconColor: "bg-indigo-600",
  },
  {
    id: "data-warehouses",
    name: "Data Warehouses",
    provider: "Data Warehouse Providers",
    category: "Analytics & BI",
    description: "Data warehouse platforms for storing and analyzing large volumes of structured and unstructured data.",
    capabilities: [
      "STORE DATA",
      "QUERY DATA",
      "LOAD DATA",
      "EXPORT DATA",
      "MANAGE SCHEMAS",
    ],
    iconColor: "bg-purple-600",
  },
  {
    id: "reporting-tools",
    name: "Reporting Tools",
    provider: "Reporting Platforms",
    category: "Analytics & BI",
    description: "Reporting tools for creating, scheduling, and distributing business reports.",
    capabilities: [
      "CREATE REPORT",
      "UPDATE REPORT",
      "SCHEDULE REPORT",
      "GET REPORT",
      "EXPORT REPORT",
      "SHARE REPORT",
    ],
    iconColor: "bg-teal-600",
  },
  {
    id: "visualization-tools",
    name: "Visualization Tools",
    provider: "Visualization Platforms",
    category: "Analytics & BI",
    description: "Data visualization tools for creating charts, graphs, and interactive dashboards.",
    capabilities: [
      "CREATE CHART",
      "UPDATE CHART",
      "GET CHART",
      "CREATE DASHBOARD",
      "EXPORT VISUALIZATION",
    ],
    iconColor: "bg-pink-600",
  },
  {
    id: "metrics-repositories",
    name: "Metrics Repositories",
    provider: "Metrics Platforms",
    category: "Analytics & BI",
    description: "Metrics repositories for storing and managing business metrics and KPIs.",
    capabilities: [
      "STORE METRIC",
      "GET METRIC",
      "UPDATE METRIC",
      "QUERY METRICS",
      "CALCULATE METRICS",
    ],
    iconColor: "bg-orange-600",
  },
  {
    id: "product-analytics",
    name: "Product Analytics",
    provider: "Product Analytics Platforms",
    category: "Analytics & BI",
    description: "Product analytics platforms for tracking user behavior and product performance.",
    capabilities: [
      "TRACK EVENT",
      "GET FUNNEL",
      "GET COHORT",
      "GET RETENTION",
      "GET METRICS",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "engagement-tracking",
    name: "Engagement Tracking",
    provider: "Engagement Platforms",
    category: "Analytics & BI",
    description: "Engagement tracking tools for measuring user engagement and interaction metrics.",
    capabilities: [
      "TRACK ENGAGEMENT",
      "GET ENGAGEMENT METRICS",
      "ANALYZE BEHAVIOR",
      "GENERATE INSIGHTS",
    ],
    iconColor: "bg-green-600",
  },

  // Search, SEO & Research
  {
    id: "google-search-console",
    name: "Google Search Console",
    provider: "Google LLC",
    category: "Search & SEO",
    description: "Google Search Console helps you monitor, maintain, and troubleshoot your site's presence in Google Search results.",
    logo: "/integration-logos/google_search_console.png",
    capabilities: [
      "GET SEARCH ANALYTICS",
      "GET SITEMAP STATUS",
      "GET URL INSPECTION",
      "GET INDEX STATUS",
      "SUBMIT SITEMAP",
      "GET PERFORMANCE DATA",
    ],
    iconColor: "bg-green-600",
  },
  {
    id: "ahrefs",
    name: "Ahrefs",
    provider: "Ahrefs Pte. Ltd.",
    category: "Search & SEO",
    description: "Ahrefs is an SEO toolset for backlink analysis, keyword research, competitor analysis, and rank tracking.",
    logo: "/integration-logos/Ahrefs.png",
    capabilities: [
      "GET BACKLINKS",
      "ANALYZE KEYWORDS",
      "GET RANKINGS",
      "ANALYZE COMPETITORS",
      "GET DOMAIN RATING",
      "EXPORT DATA",
    ],
    iconColor: "bg-orange-600",
  },
  {
    id: "semrush",
    name: "SEMrush",
    provider: "SEMrush Inc.",
    category: "Search & SEO",
    description: "SEMrush is an all-in-one marketing toolkit for SEO, PPC, content, social media, and competitive research.",
    logo: "/integration-logos/SEMrush.png",
    capabilities: [
      "ANALYZE KEYWORDS",
      "GET RANKINGS",
      "ANALYZE COMPETITORS",
      "GET BACKLINKS",
      "ANALYZE DOMAIN",
      "EXPORT DATA",
    ],
    iconColor: "bg-red-600",
  },
  {
    id: "google-search-api",
    name: "Google Search API",
    provider: "Google LLC",
    category: "Search & SEO",
    description: "Google Search API for programmatic access to Google search results and search functionality.",
    logo: "/integration-logos/Google Search API.png",
    capabilities: [
      "PERFORM SEARCH",
      "GET SEARCH RESULTS",
      "CUSTOMIZE SEARCH",
      "FILTER RESULTS",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "search-engines",
    name: "Search Engines",
    provider: "Search Engine Providers",
    category: "Search & SEO",
    description: "Generic search engine APIs for programmatic search functionality.",
    capabilities: [
      "PERFORM SEARCH",
      "GET RESULTS",
      "FILTER RESULTS",
      "RANK RESULTS",
    ],
    iconColor: "bg-gray-600",
  },
  {
    id: "web-crawlers",
    name: "Web Crawlers",
    provider: "Crawler Services",
    category: "Search & SEO",
    description: "Web crawling services for extracting and indexing web content.",
    capabilities: [
      "CRAWL URL",
      "EXTRACT CONTENT",
      "INDEX CONTENT",
      "GET CRAWL STATUS",
    ],
    iconColor: "bg-indigo-600",
  },
  {
    id: "search-apis",
    name: "Search APIs",
    provider: "Search API Providers",
    category: "Search & SEO",
    description: "Generic search APIs for implementing search functionality in applications.",
    capabilities: [
      "PERFORM SEARCH",
      "GET RESULTS",
      "RANK RESULTS",
      "SUGGEST QUERIES",
    ],
    iconColor: "bg-purple-600",
  },

  // AI, ML & NLP
  {
    id: "nlp-platforms",
    name: "NLP Platforms",
    provider: "NLP Service Providers",
    category: "AI & ML",
    description: "Natural Language Processing platforms for text analysis, sentiment analysis, and language understanding.",
    capabilities: [
      "ANALYZE TEXT",
      "EXTRACT ENTITIES",
      "ANALYZE SENTIMENT",
      "TRANSLATE TEXT",
      "SUMMARIZE TEXT",
      "CLASSIFY TEXT",
    ],
    iconColor: "bg-purple-600",
  },
  {
    id: "ai-writing-tools",
    name: "AI Writing Tools",
    provider: "AI Writing Platforms",
    category: "AI & ML",
    description: "AI-powered writing tools for generating, editing, and optimizing content.",
    capabilities: [
      "GENERATE TEXT",
      "EDIT TEXT",
      "OPTIMIZE TEXT",
      "CHECK GRAMMAR",
      "REWRITE TEXT",
    ],
    iconColor: "bg-pink-600",
  },
  {
    id: "ml-pipelines",
    name: "Machine Learning Pipelines",
    provider: "ML Platform Providers",
    category: "AI & ML",
    description: "Machine learning pipeline platforms for building, training, and deploying ML models.",
    capabilities: [
      "TRAIN MODEL",
      "DEPLOY MODEL",
      "PREDICT",
      "EVALUATE MODEL",
      "MANAGE MODELS",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "computer-vision",
    name: "Computer Vision Models",
    provider: "CV Platform Providers",
    category: "AI & ML",
    description: "Computer vision models for image analysis, object detection, and visual recognition.",
    capabilities: [
      "ANALYZE IMAGE",
      "DETECT OBJECTS",
      "RECOGNIZE FACES",
      "CLASSIFY IMAGE",
      "EXTRACT TEXT",
    ],
    iconColor: "bg-indigo-600",
  },
  {
    id: "vector-databases",
    name: "Vector Databases",
    provider: "Vector DB Providers",
    category: "AI & ML",
    description: "Vector databases for storing and querying high-dimensional vectors for similarity search.",
    capabilities: [
      "STORE VECTORS",
      "SEARCH VECTORS",
      "GET SIMILAR",
      "UPDATE VECTORS",
      "DELETE VECTORS",
    ],
    iconColor: "bg-teal-600",
  },
  {
    id: "embeddings",
    name: "Embeddings",
    provider: "Embedding Services",
    category: "AI & ML",
    description: "Embedding services for converting text, images, and other data into vector representations.",
    capabilities: [
      "GENERATE EMBEDDING",
      "BATCH EMBED",
      "GET EMBEDDING",
      "COMPARE EMBEDDINGS",
    ],
    iconColor: "bg-green-600",
  },
  {
    id: "risk-scoring",
    name: "Risk Scoring Engines",
    provider: "Risk Scoring Platforms",
    category: "AI & ML",
    description: "Risk scoring engines for evaluating and scoring risk factors in various business contexts.",
    capabilities: [
      "CALCULATE RISK",
      "GET RISK SCORE",
      "UPDATE RISK MODEL",
      "GET RISK FACTORS",
    ],
    iconColor: "bg-red-600",
  },

  // HR, Talent & Workforce
  {
    id: "bamboohr",
    name: "BambooHR",
    provider: "BambooHR LLC",
    category: "HR & Talent",
    description: "BambooHR is an HR software platform that helps manage employee data, time off, performance, and recruiting.",
    logo: "/integration-logos/BambooHR.png",
    capabilities: [
      "GET EMPLOYEE",
      "UPDATE EMPLOYEE",
      "CREATE EMPLOYEE",
      "LIST EMPLOYEES",
      "MANAGE TIME OFF",
      "GET TIME OFF",
      "MANAGE PERFORMANCE",
      "GET PERFORMANCE",
    ],
    iconColor: "bg-green-600",
  },
  {
    id: "workday",
    name: "Workday",
    provider: "Workday Inc.",
    category: "HR & Talent",
    description: "Workday is a cloud-based enterprise software for human resources, financial management, and student information systems.",
    logo: "/integration-logos/Workday.png",
    capabilities: [
      "GET WORKER",
      "UPDATE WORKER",
      "CREATE WORKER",
      "LIST WORKERS",
      "MANAGE TIME",
      "GET TIME",
      "MANAGE BENEFITS",
      "GET BENEFITS",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "ukg",
    name: "UKG",
    provider: "UKG Inc.",
    category: "HR & Talent",
    description: "UKG (Ultimate Kronos Group) provides workforce management and human capital management solutions.",
    capabilities: [
      "GET EMPLOYEE",
      "UPDATE EMPLOYEE",
      "MANAGE SCHEDULE",
      "GET SCHEDULE",
      "TRACK TIME",
      "GET TIME",
      "MANAGE PAYROLL",
    ],
    iconColor: "bg-purple-600",
  },
  {
    id: "hris",
    name: "HRIS",
    provider: "HRIS Providers",
    category: "HR & Talent",
    description: "Human Resources Information Systems for managing employee data and HR processes.",
    capabilities: [
      "MANAGE EMPLOYEES",
      "TRACK ATTENDANCE",
      "MANAGE BENEFITS",
      "GENERATE REPORTS",
      "MANAGE PAYROLL",
    ],
    iconColor: "bg-indigo-600",
  },
  {
    id: "ats",
    name: "ATS",
    provider: "Applicant Tracking Systems",
    category: "HR & Talent",
    description: "Applicant Tracking Systems for managing recruitment, candidate pipelines, and hiring processes.",
    capabilities: [
      "CREATE CANDIDATE",
      "UPDATE CANDIDATE",
      "GET CANDIDATE",
      "LIST CANDIDATES",
      "CREATE JOB",
      "GET JOB",
      "LIST JOBS",
      "MOVE CANDIDATE",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "lms",
    name: "LMS",
    provider: "Learning Management Systems",
    category: "HR & Talent",
    description: "Learning Management Systems for delivering, tracking, and managing training and educational content.",
    capabilities: [
      "CREATE COURSE",
      "UPDATE COURSE",
      "GET COURSE",
      "LIST COURSES",
      "ENROLL USER",
      "TRACK PROGRESS",
      "GET PROGRESS",
    ],
    iconColor: "bg-green-600",
  },
  {
    id: "skill-taxonomies",
    name: "Skill Taxonomies",
    provider: "Skill Platform Providers",
    category: "HR & Talent",
    description: "Skill taxonomy platforms for defining, organizing, and tracking skills and competencies.",
    capabilities: [
      "DEFINE SKILL",
      "GET SKILL",
      "LIST SKILLS",
      "MAP SKILLS",
      "ASSESS SKILLS",
    ],
    iconColor: "bg-teal-600",
  },
  {
    id: "hr-case-management",
    name: "HR Case Management",
    provider: "HR Case Management Tools",
    category: "HR & Talent",
    description: "HR case management tools for tracking and resolving employee relations cases and inquiries.",
    capabilities: [
      "CREATE CASE",
      "UPDATE CASE",
      "GET CASE",
      "LIST CASES",
      "ASSIGN CASE",
      "RESOLVE CASE",
    ],
    iconColor: "bg-purple-600",
  },
  {
    id: "time-tracking",
    name: "Time Tracking Systems",
    provider: "Time Tracking Providers",
    category: "HR & Talent",
    description: "Time tracking systems for monitoring employee work hours, attendance, and productivity.",
    capabilities: [
      "TRACK TIME",
      "GET TIME",
      "APPROVE TIME",
      "EXPORT TIME",
      "MANAGE SCHEDULES",
    ],
    iconColor: "bg-orange-600",
  },
  {
    id: "scheduling-tools",
    name: "Scheduling Tools",
    provider: "Scheduling Platforms",
    category: "HR & Talent",
    description: "Scheduling tools for managing employee shifts, schedules, and workforce planning.",
    capabilities: [
      "CREATE SCHEDULE",
      "UPDATE SCHEDULE",
      "GET SCHEDULE",
      "LIST SCHEDULES",
      "MANAGE SHIFTS",
      "ASSIGN SHIFTS",
    ],
    iconColor: "bg-blue-600",
  },

  // IT, DevOps & Engineering
  {
    id: "servicenow",
    name: "ServiceNow",
    provider: "ServiceNow Inc.",
    category: "IT & DevOps",
    description: "ServiceNow is a cloud computing platform that helps companies manage digital workflows for enterprise operations.",
    logo: "/integration-logos/ServiceNow.png",
    capabilities: [
      "CREATE INCIDENT",
      "UPDATE INCIDENT",
      "GET INCIDENT",
      "LIST INCIDENTS",
      "CREATE CHANGE",
      "APPROVE CHANGE",
      "GET CHANGE",
      "CREATE REQUEST",
      "GET REQUEST",
      "LIST REQUESTS",
    ],
    iconColor: "bg-green-600",
  },
  {
    id: "jira",
    name: "Jira",
    provider: "Atlassian",
    category: "IT & DevOps",
    description: "Jira is a project management tool used for issue tracking, bug tracking, and agile project management.",
    logo: "/integration-logos/Jira_icon.png",
    capabilities: [
      "CREATE ISSUE",
      "UPDATE ISSUE",
      "GET ISSUE",
      "LIST ISSUES",
      "CREATE PROJECT",
      "GET PROJECT",
      "LIST PROJECTS",
      "ADD COMMENT",
      "GET COMMENTS",
      "TRANSITION ISSUE",
    ],
    iconColor: "bg-blue-500",
  },
  {
    id: "jira-service-management",
    name: "Jira Service Management",
    provider: "Atlassian",
    category: "IT & DevOps",
    description: "Jira Service Management is an IT service management solution built on Jira for managing IT operations and service requests.",
    logo: "/integration-logos/Jira-Service-Management_icon.png",
    capabilities: [
      "CREATE REQUEST",
      "UPDATE REQUEST",
      "GET REQUEST",
      "LIST REQUESTS",
      "CREATE INCIDENT",
      "RESOLVE INCIDENT",
      "MANAGE SLAs",
      "GET METRICS",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "github",
    name: "GitHub",
    provider: "GitHub Inc.",
    category: "IT & DevOps",
    description: "GitHub is a code hosting platform for version control and collaboration using Git.",
    logo: "/integration-logos/GitHub.png",
    capabilities: [
      "CREATE REPOSITORY",
      "GET REPOSITORY",
      "LIST REPOSITORIES",
      "CREATE ISSUE",
      "GET ISSUE",
      "LIST ISSUES",
      "CREATE PULL REQUEST",
      "GET PULL REQUEST",
      "MERGE PULL REQUEST",
      "GET COMMITS",
    ],
    iconColor: "bg-gray-900",
  },
  {
    id: "gitlab",
    name: "GitLab",
    provider: "GitLab Inc.",
    category: "IT & DevOps",
    description: "GitLab is a complete DevOps platform that provides a Git repository manager with wiki, issue-tracking, and CI/CD pipeline features.",
    logo: "/integration-logos/GitLab.png",
    capabilities: [
      "CREATE PROJECT",
      "GET PROJECT",
      "LIST PROJECTS",
      "CREATE ISSUE",
      "GET ISSUE",
      "CREATE MERGE REQUEST",
      "GET MERGE REQUEST",
      "RUN PIPELINE",
      "GET PIPELINE",
    ],
    iconColor: "bg-orange-600",
  },
  {
    id: "jenkins",
    name: "Jenkins",
    provider: "Jenkins Project",
    category: "IT & DevOps",
    description: "Jenkins is an open-source automation server that helps automate parts of software development related to building, testing, and deploying.",
    logo: "/integration-logos/jenkins.png",
    capabilities: [
      "TRIGGER BUILD",
      "GET BUILD",
      "GET BUILD STATUS",
      "GET BUILD LOGS",
      "MANAGE JOBS",
      "GET JOBS",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "github-actions",
    name: "GitHub Actions",
    provider: "GitHub Inc.",
    category: "IT & DevOps",
    description: "GitHub Actions is a CI/CD platform that allows you to automate workflows directly in your GitHub repository.",
    logo: "/integration-logos/GitHub Actions.png",
    capabilities: [
      "TRIGGER WORKFLOW",
      "GET WORKFLOW",
      "GET WORKFLOW RUN",
      "GET WORKFLOW LOGS",
      "MANAGE SECRETS",
    ],
    iconColor: "bg-gray-900",
  },
  {
    id: "cicd-tools",
    name: "CI/CD Tools",
    provider: "CI/CD Platform Providers",
    category: "IT & DevOps",
    description: "Continuous Integration and Continuous Deployment tools for automating software build, test, and deployment processes.",
    capabilities: [
      "TRIGGER PIPELINE",
      "GET PIPELINE",
      "GET PIPELINE STATUS",
      "GET PIPELINE LOGS",
      "MANAGE CONFIG",
    ],
    iconColor: "bg-indigo-600",
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    provider: "Kubernetes Project",
    category: "IT & DevOps",
    description: "Kubernetes is an open-source container orchestration platform for automating deployment, scaling, and management of containerized applications.",
    logo: "/integration-logos/Kubernetes.png",
    capabilities: [
      "DEPLOY APPLICATION",
      "SCALE APPLICATION",
      "GET PODS",
      "GET SERVICES",
      "MANAGE CONFIGMAPS",
      "MANAGE SECRETS",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "cmdb",
    name: "CMDB",
    provider: "Configuration Management Databases",
    category: "IT & DevOps",
    description: "Configuration Management Databases for storing information about IT assets and their relationships.",
    capabilities: [
      "CREATE CI",
      "UPDATE CI",
      "GET CI",
      "LIST CIs",
      "MANAGE RELATIONSHIPS",
      "SEARCH CIs",
    ],
    iconColor: "bg-purple-600",
  },
  {
    id: "itsm-tools",
    name: "ITSM Tools",
    provider: "ITSM Platform Providers",
    category: "IT & DevOps",
    description: "IT Service Management tools for managing IT services, incidents, problems, and changes.",
    capabilities: [
      "CREATE TICKET",
      "UPDATE TICKET",
      "GET TICKET",
      "LIST TICKETS",
      "RESOLVE TICKET",
      "MANAGE SLAs",
    ],
    iconColor: "bg-teal-600",
  },
  {
    id: "chatops",
    name: "ChatOps",
    provider: "ChatOps Platforms",
    category: "IT & DevOps",
    description: "ChatOps platforms for managing DevOps workflows through chat interfaces.",
    capabilities: [
      "SEND MESSAGE",
      "TRIGGER ACTION",
      "GET STATUS",
      "EXECUTE COMMAND",
    ],
    iconColor: "bg-pink-600",
  },

  // Identity, Access & Security
  {
    id: "okta",
    name: "Okta",
    provider: "Okta Inc.",
    category: "Identity & Security",
    description: "Okta is an identity and access management platform that provides single sign-on, multi-factor authentication, and user management.",
    logo: "/integration-logos/okta.png",
    capabilities: [
      "CREATE USER",
      "UPDATE USER",
      "GET USER",
      "LIST USERS",
      "ASSIGN APP",
      "GET GROUPS",
      "MANAGE MFA",
      "RESET PASSWORD",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "azure-ad",
    name: "Azure AD",
    provider: "Microsoft Corporation",
    category: "Identity & Security",
    description: "Azure Active Directory is Microsoft's cloud-based identity and access management service.",
    logo: "/integration-logos/azure-active-directory.svg",
    capabilities: [
      "CREATE USER",
      "UPDATE USER",
      "GET USER",
      "LIST USERS",
      "ASSIGN LICENSE",
      "GET GROUPS",
      "MANAGE ROLES",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "active-directory",
    name: "Active Directory",
    provider: "Microsoft Corporation",
    category: "Identity & Security",
    description: "Active Directory is a directory service for managing users, computers, and other resources on a network.",
    capabilities: [
      "CREATE USER",
      "UPDATE USER",
      "GET USER",
      "LIST USERS",
      "MANAGE GROUPS",
      "MANAGE PERMISSIONS",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "iga-tools",
    name: "IGA Tools",
    provider: "Identity Governance Platforms",
    category: "Identity & Security",
    description: "Identity Governance and Administration tools for managing user access, roles, and compliance.",
    capabilities: [
      "MANAGE ACCESS",
      "REVIEW ACCESS",
      "PROVISION ACCESS",
      "DEPROVISION ACCESS",
      "MANAGE ROLES",
      "GENERATE REPORTS",
    ],
    iconColor: "bg-indigo-600",
  },
  {
    id: "mfa-platforms",
    name: "MFA Platforms",
    provider: "MFA Service Providers",
    category: "Identity & Security",
    description: "Multi-Factor Authentication platforms for securing user accounts with additional authentication factors.",
    capabilities: [
      "ENABLE MFA",
      "VERIFY MFA",
      "MANAGE DEVICES",
      "GET MFA STATUS",
    ],
    iconColor: "bg-purple-600",
  },
  {
    id: "security-tools",
    name: "Security Tools",
    provider: "Security Platform Providers",
    category: "Identity & Security",
    description: "Security tools for monitoring, detecting, and responding to security threats and vulnerabilities.",
    capabilities: [
      "SCAN FOR THREATS",
      "GET ALERTS",
      "QUARANTINE THREAT",
      "GENERATE REPORT",
      "MANAGE POLICIES",
    ],
    iconColor: "bg-red-600",
  },
  {
    id: "dlp-tools",
    name: "DLP Tools",
    provider: "Data Loss Prevention Platforms",
    category: "Identity & Security",
    description: "Data Loss Prevention tools for detecting and preventing unauthorized access, use, or transmission of sensitive data.",
    capabilities: [
      "SCAN DATA",
      "DETECT VIOLATIONS",
      "BLOCK TRANSFER",
      "GENERATE ALERT",
      "MANAGE POLICIES",
    ],
    iconColor: "bg-orange-600",
  },

  // Retail, Commerce & Logistics
  {
    id: "shopify",
    name: "Shopify",
    provider: "Shopify Inc.",
    category: "Retail & Commerce",
    description: "Shopify is an e-commerce platform that allows businesses to create online stores and sell products.",
    logo: "/integration-logos/shopify.png",
    capabilities: [
      "GET PRODUCT",
      "CREATE PRODUCT",
      "UPDATE PRODUCT",
      "LIST PRODUCTS",
      "GET ORDER",
      "LIST ORDERS",
      "UPDATE ORDER",
      "GET CUSTOMER",
      "LIST CUSTOMERS",
    ],
    iconColor: "bg-green-600",
  },
  {
    id: "bigcommerce",
    name: "BigCommerce",
    provider: "BigCommerce Inc.",
    category: "Retail & Commerce",
    description: "BigCommerce is an e-commerce platform that provides tools for building and managing online stores.",
    logo: "/integration-logos/bigcommerce.png",
    capabilities: [
      "GET PRODUCT",
      "CREATE PRODUCT",
      "UPDATE PRODUCT",
      "LIST PRODUCTS",
      "GET ORDER",
      "LIST ORDERS",
      "GET CUSTOMER",
      "LIST CUSTOMERS",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "pos-systems",
    name: "POS Systems",
    provider: "POS Platform Providers",
    category: "Retail & Commerce",
    description: "Point of Sale systems for processing transactions, managing inventory, and tracking sales.",
    capabilities: [
      "PROCESS SALE",
      "GET SALE",
      "LIST SALES",
      "MANAGE INVENTORY",
      "GET INVENTORY",
      "PROCESS RETURN",
    ],
    iconColor: "bg-indigo-600",
  },
  {
    id: "inventory-systems",
    name: "Inventory Systems",
    provider: "Inventory Management Providers",
    category: "Retail & Commerce",
    description: "Inventory management systems for tracking stock levels, orders, and warehouse operations.",
    capabilities: [
      "GET INVENTORY",
      "UPDATE INVENTORY",
      "TRACK STOCK",
      "MANAGE WAREHOUSES",
      "GENERATE REPORTS",
    ],
    iconColor: "bg-purple-600",
  },
  {
    id: "logistics-apis",
    name: "Logistics APIs",
    provider: "Logistics Service Providers",
    category: "Retail & Commerce",
    description: "Logistics APIs for managing shipping, tracking, and delivery of orders and packages.",
    capabilities: [
      "CREATE SHIPMENT",
      "GET SHIPMENT",
      "TRACK SHIPMENT",
      "GET RATES",
      "CREATE LABEL",
    ],
    iconColor: "bg-teal-600",
  },
  {
    id: "returns-platforms",
    name: "Returns Platforms",
    provider: "Returns Management Providers",
    category: "Retail & Commerce",
    description: "Returns management platforms for processing product returns, exchanges, and refunds.",
    capabilities: [
      "CREATE RETURN",
      "GET RETURN",
      "LIST RETURNS",
      "PROCESS RETURN",
      "ISSUE REFUND",
    ],
    iconColor: "bg-pink-600",
  },
  {
    id: "loyalty-platforms",
    name: "Loyalty Platforms",
    provider: "Loyalty Program Providers",
    category: "Retail & Commerce",
    description: "Loyalty program platforms for managing customer rewards, points, and membership programs.",
    capabilities: [
      "GET MEMBER",
      "UPDATE MEMBER",
      "ADD POINTS",
      "REDEEM POINTS",
      "GET BALANCE",
      "GET HISTORY",
    ],
    iconColor: "bg-orange-600",
  },
  {
    id: "pricing-tools",
    name: "Pricing Tools",
    provider: "Pricing Platform Providers",
    category: "Retail & Commerce",
    description: "Pricing tools for managing product prices, promotions, and dynamic pricing strategies.",
    capabilities: [
      "GET PRICE",
      "UPDATE PRICE",
      "SET PROMOTION",
      "GET PROMOTIONS",
      "CALCULATE PRICE",
    ],
    iconColor: "bg-yellow-600",
  },
  {
    id: "planogram-tools",
    name: "Planogram Tools",
    provider: "Planogram Platform Providers",
    category: "Retail & Commerce",
    description: "Planogram tools for designing and managing product placement and store layouts.",
    capabilities: [
      "CREATE PLANOGRAM",
      "UPDATE PLANOGRAM",
      "GET PLANOGRAM",
      "LIST PLANOGRAMS",
      "OPTIMIZE LAYOUT",
    ],
    iconColor: "bg-cyan-600",
  },
  {
    id: "commerce-platforms",
    name: "Commerce Platforms",
    provider: "E-commerce Platform Providers",
    category: "Retail & Commerce",
    description: "Generic e-commerce platforms for building and managing online stores and marketplaces.",
    capabilities: [
      "MANAGE PRODUCTS",
      "MANAGE ORDERS",
      "MANAGE CUSTOMERS",
      "PROCESS PAYMENTS",
      "MANAGE INVENTORY",
    ],
    iconColor: "bg-gray-600",
  },

  // Healthcare & Life Sciences
  {
    id: "ehr-systems",
    name: "EHR Systems",
    provider: "Electronic Health Record Providers",
    category: "Healthcare",
    description: "Electronic Health Record systems for storing and managing patient medical records and health information.",
    capabilities: [
      "GET PATIENT",
      "CREATE PATIENT",
      "UPDATE PATIENT",
      "GET RECORD",
      "CREATE RECORD",
      "SEARCH RECORDS",
      "GET APPOINTMENT",
      "SCHEDULE APPOINTMENT",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "care-management",
    name: "Care Management Platforms",
    provider: "Care Management Providers",
    category: "Healthcare",
    description: "Care management platforms for coordinating patient care, managing care plans, and tracking outcomes.",
    capabilities: [
      "CREATE CARE PLAN",
      "UPDATE CARE PLAN",
      "GET CARE PLAN",
      "TRACK OUTCOMES",
      "MANAGE PROVIDERS",
    ],
    iconColor: "bg-green-600",
  },
  {
    id: "telehealth",
    name: "Telehealth Platforms",
    provider: "Telehealth Providers",
    category: "Healthcare",
    description: "Telehealth platforms for delivering remote healthcare services and virtual consultations.",
    capabilities: [
      "SCHEDULE VISIT",
      "START VISIT",
      "GET VISIT",
      "RECORD VISIT",
      "MANAGE PROVIDERS",
    ],
    iconColor: "bg-teal-600",
  },
  {
    id: "payer-systems",
    name: "Payer Systems",
    provider: "Health Insurance Providers",
    category: "Healthcare",
    description: "Health insurance payer systems for managing claims, eligibility, and benefits.",
    capabilities: [
      "CHECK ELIGIBILITY",
      "SUBMIT CLAIM",
      "GET CLAIM",
      "PROCESS CLAIM",
      "GET BENEFITS",
    ],
    iconColor: "bg-indigo-600",
  },
  {
    id: "eligibility-apis",
    name: "Eligibility APIs",
    provider: "Eligibility Service Providers",
    category: "Healthcare",
    description: "Eligibility APIs for checking patient insurance coverage and benefit eligibility.",
    capabilities: [
      "CHECK ELIGIBILITY",
      "GET BENEFITS",
      "VERIFY COVERAGE",
      "GET DEDUCTIBLES",
    ],
    iconColor: "bg-purple-600",
  },
  {
    id: "claims-clearinghouses",
    name: "Claims Clearinghouses",
    provider: "Claims Clearinghouse Providers",
    category: "Healthcare",
    description: "Claims clearinghouses for processing and routing healthcare claims between providers and payers.",
    capabilities: [
      "SUBMIT CLAIM",
      "GET CLAIM STATUS",
      "PROCESS CLAIM",
      "GET REMITTANCE",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "pbm-platforms",
    name: "PBM Platforms",
    provider: "Pharmacy Benefit Managers",
    category: "Healthcare",
    description: "Pharmacy Benefit Management platforms for managing prescription drug benefits and pharmacy networks.",
    capabilities: [
      "CHECK FORMULARY",
      "GET COVERAGE",
      "PROCESS CLAIM",
      "GET PRICING",
    ],
    iconColor: "bg-green-600",
  },
  {
    id: "pharmacy-systems",
    name: "Pharmacy Systems",
    provider: "Pharmacy Management Providers",
    category: "Healthcare",
    description: "Pharmacy management systems for processing prescriptions, managing inventory, and dispensing medications.",
    capabilities: [
      "PROCESS PRESCRIPTION",
      "GET PRESCRIPTION",
      "MANAGE INVENTORY",
      "DISPENSE MEDICATION",
    ],
    iconColor: "bg-teal-600",
  },
  {
    id: "nurse-call-systems",
    name: "Nurse Call Systems",
    provider: "Nurse Call Providers",
    category: "Healthcare",
    description: "Nurse call systems for managing patient requests, alerts, and communication in healthcare facilities.",
    capabilities: [
      "CREATE ALERT",
      "GET ALERT",
      "RESPOND TO ALERT",
      "MANAGE CALLS",
    ],
    iconColor: "bg-pink-600",
  },
  {
    id: "clinical-dashboards",
    name: "Clinical Dashboards",
    provider: "Clinical Dashboard Providers",
    category: "Healthcare",
    description: "Clinical dashboards for displaying patient information, vitals, and clinical metrics.",
    capabilities: [
      "GET PATIENT DATA",
      "DISPLAY METRICS",
      "GET ALERTS",
      "UPDATE STATUS",
    ],
    iconColor: "bg-blue-600",
  },

  // Legal, Compliance & Risk
  {
    id: "clm-tools",
    name: "CLM Tools",
    provider: "Contract Lifecycle Management",
    category: "Legal & Compliance",
    description: "Contract Lifecycle Management tools for creating, managing, and tracking contracts throughout their lifecycle.",
    capabilities: [
      "CREATE CONTRACT",
      "UPDATE CONTRACT",
      "GET CONTRACT",
      "LIST CONTRACTS",
      "APPROVE CONTRACT",
      "TRACK EXPIRATIONS",
    ],
    iconColor: "bg-indigo-600",
  },
  {
    id: "legal-systems",
    name: "Legal Systems",
    provider: "Legal Platform Providers",
    category: "Legal & Compliance",
    description: "Legal management systems for managing cases, documents, and legal workflows.",
    capabilities: [
      "CREATE CASE",
      "UPDATE CASE",
      "GET CASE",
      "LIST CASES",
      "MANAGE DOCUMENTS",
      "TRACK DEADLINES",
    ],
    iconColor: "bg-purple-600",
  },
  {
    id: "trade-surveillance",
    name: "Trade Surveillance Tools",
    provider: "Trade Surveillance Providers",
    category: "Legal & Compliance",
    description: "Trade surveillance tools for monitoring and detecting suspicious trading activities and compliance violations.",
    capabilities: [
      "MONITOR TRADES",
      "DETECT ANOMALIES",
      "GENERATE ALERTS",
      "INVESTIGATE CASES",
      "GENERATE REPORTS",
    ],
    iconColor: "bg-red-600",
  },
  {
    id: "aml-systems",
    name: "AML Systems",
    provider: "Anti-Money Laundering Platforms",
    category: "Legal & Compliance",
    description: "Anti-Money Laundering systems for detecting and preventing money laundering and financial crimes.",
    capabilities: [
      "SCAN TRANSACTIONS",
      "DETECT SUSPICIOUS ACTIVITY",
      "GENERATE ALERT",
      "FILE SAR",
      "GENERATE REPORT",
    ],
    iconColor: "bg-orange-600",
  },
  {
    id: "compliance-engines",
    name: "Compliance Engines",
    provider: "Compliance Platform Providers",
    category: "Legal & Compliance",
    description: "Compliance engines for monitoring regulatory compliance and managing compliance workflows.",
    capabilities: [
      "CHECK COMPLIANCE",
      "GENERATE REPORT",
      "TRACK VIOLATIONS",
      "MANAGE POLICIES",
      "AUDIT ACTIVITIES",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "case-management",
    name: "Case Management Systems",
    provider: "Case Management Providers",
    category: "Legal & Compliance",
    description: "Case management systems for tracking and managing legal cases, investigations, and compliance matters.",
    capabilities: [
      "CREATE CASE",
      "UPDATE CASE",
      "GET CASE",
      "LIST CASES",
      "ASSIGN CASE",
      "TRACK PROGRESS",
    ],
    iconColor: "bg-gray-600",
  },
  {
    id: "policy-databases",
    name: "Policy Databases",
    provider: "Policy Management Providers",
    category: "Legal & Compliance",
    description: "Policy databases for storing, managing, and retrieving organizational policies and procedures.",
    capabilities: [
      "CREATE POLICY",
      "UPDATE POLICY",
      "GET POLICY",
      "LIST POLICIES",
      "SEARCH POLICIES",
      "TRACK VERSIONS",
    ],
    iconColor: "bg-indigo-600",
  },

  // Customer Support & Service
  {
    id: "zendesk",
    name: "Zendesk",
    provider: "Zendesk Inc.",
    category: "Customer Support",
    description: "Zendesk is a customer service platform that provides help desk software and support ticket management.",
    logo: "/integration-logos/zendesk.png",
    capabilities: [
      "CREATE TICKET",
      "UPDATE TICKET",
      "GET TICKET",
      "LIST TICKETS",
      "ADD COMMENT",
      "GET COMMENTS",
      "SOLVE TICKET",
      "GET METRICS",
    ],
    iconColor: "bg-green-600",
  },
  {
    id: "freshdesk",
    name: "Freshdesk",
    provider: "Freshworks Inc.",
    category: "Customer Support",
    description: "Freshdesk is a cloud-based customer support software that helps businesses manage customer inquiries and support tickets.",
    logo: "/integration-logos/freshdesk.png",
    capabilities: [
      "CREATE TICKET",
      "UPDATE TICKET",
      "GET TICKET",
      "LIST TICKETS",
      "ADD COMMENT",
      "RESOLVE TICKET",
      "GET METRICS",
    ],
    iconColor: "bg-green-600",
  },
  {
    id: "salesforce-service",
    name: "Salesforce Service",
    provider: "Salesforce Inc.",
    category: "Customer Support",
    description: "Salesforce Service Cloud is a customer service platform that helps businesses deliver personalized customer support.",
    capabilities: [
      "CREATE CASE",
      "UPDATE CASE",
      "GET CASE",
      "LIST CASES",
      "ADD COMMENT",
      "RESOLVE CASE",
      "GET KNOWLEDGE ARTICLES",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "zendesk-guide",
    name: "Zendesk Guide",
    provider: "Zendesk Inc.",
    category: "Customer Support",
    description: "Zendesk Guide is a knowledge base platform for creating and managing help center content and documentation.",
    logo: "/integration-logos/zendesk guide.png",
    capabilities: [
      "CREATE ARTICLE",
      "UPDATE ARTICLE",
      "GET ARTICLE",
      "LIST ARTICLES",
      "SEARCH ARTICLES",
      "PUBLISH ARTICLE",
    ],
    iconColor: "bg-green-600",
  },
  {
    id: "status-page-tools",
    name: "Status Page Tools",
    provider: "Status Page Providers",
    category: "Customer Support",
    description: "Status page tools for communicating service status, incidents, and maintenance updates to customers.",
    capabilities: [
      "CREATE INCIDENT",
      "UPDATE INCIDENT",
      "GET INCIDENT",
      "LIST INCIDENTS",
      "UPDATE STATUS",
      "POST UPDATE",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "incident-management",
    name: "Incident Management Tools",
    provider: "Incident Management Providers",
    category: "Customer Support",
    description: "Incident management tools for tracking, managing, and resolving service incidents and outages.",
    capabilities: [
      "CREATE INCIDENT",
      "UPDATE INCIDENT",
      "GET INCIDENT",
      "LIST INCIDENTS",
      "ASSIGN INCIDENT",
      "RESOLVE INCIDENT",
    ],
    iconColor: "bg-red-600",
  },
  {
    id: "voice-of-customer",
    name: "Voice of Customer Platforms",
    provider: "VoC Platform Providers",
    category: "Customer Support",
    description: "Voice of Customer platforms for collecting, analyzing, and acting on customer feedback and insights.",
    capabilities: [
      "COLLECT FEEDBACK",
      "ANALYZE SENTIMENT",
      "GET INSIGHTS",
      "CREATE SURVEY",
      "GET SURVEY RESULTS",
    ],
    iconColor: "bg-purple-600",
  },

  // Marketing, Ads & Engagement
  {
    id: "google-ads",
    name: "Google Ads",
    provider: "Google LLC",
    category: "Marketing & Ads",
    description: "Google Ads is an online advertising platform that allows businesses to display ads on Google's search results and partner websites.",
    logo: "/integration-logos/google-ads.png",
    capabilities: [
      "CREATE CAMPAIGN",
      "UPDATE CAMPAIGN",
      "GET CAMPAIGN",
      "LIST CAMPAIGNS",
      "CREATE AD",
      "GET AD",
      "GET METRICS",
      "OPTIMIZE CAMPAIGN",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "meta-ads",
    name: "Meta Ads",
    provider: "Meta Platforms",
    category: "Marketing & Ads",
    description: "Meta Ads (Facebook Ads) is an advertising platform for creating and managing ads on Facebook, Instagram, and other Meta properties.",
    logo: "/integration-logos/meta ads.png",
    capabilities: [
      "CREATE CAMPAIGN",
      "UPDATE CAMPAIGN",
      "GET CAMPAIGN",
      "LIST CAMPAIGNS",
      "CREATE AD",
      "GET METRICS",
      "OPTIMIZE CAMPAIGN",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "linkedin-ads",
    name: "LinkedIn Ads",
    provider: "LinkedIn Corporation",
    category: "Marketing & Ads",
    description: "LinkedIn Ads is an advertising platform for creating and managing professional ads on LinkedIn.",
    logo: "/integration-logos/linkedin ads.png",
    capabilities: [
      "CREATE CAMPAIGN",
      "UPDATE CAMPAIGN",
      "GET CAMPAIGN",
      "LIST CAMPAIGNS",
      "CREATE AD",
      "GET METRICS",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "hootsuite",
    name: "Hootsuite",
    provider: "Hootsuite Inc.",
    category: "Marketing & Ads",
    description: "Hootsuite is a social media management platform for managing multiple social media accounts and scheduling posts.",
    logo: "/integration-logos/Hootsuite.png",
    capabilities: [
      "CREATE POST",
      "SCHEDULE POST",
      "GET POST",
      "LIST POSTS",
      "GET ANALYTICS",
      "MANAGE ACCOUNTS",
    ],
    iconColor: "bg-orange-600",
  },
  {
    id: "buffer",
    name: "Buffer",
    provider: "Buffer Inc.",
    category: "Marketing & Ads",
    description: "Buffer is a social media management tool for scheduling posts, analyzing performance, and managing social media accounts.",
    logo: "/integration-logos/Buffer.png",
    capabilities: [
      "CREATE POST",
      "SCHEDULE POST",
      "GET POST",
      "LIST POSTS",
      "GET ANALYTICS",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "eventbrite",
    name: "Eventbrite",
    provider: "Eventbrite Inc.",
    category: "Marketing & Ads",
    description: "Eventbrite is an event management and ticketing platform for creating, promoting, and selling tickets to events.",
    logo: "/integration-logos/Eventbrite.png",
    capabilities: [
      "CREATE EVENT",
      "UPDATE EVENT",
      "GET EVENT",
      "LIST EVENTS",
      "GET TICKETS",
      "GET ATTENDEES",
    ],
    iconColor: "bg-orange-600",
  },
  {
    id: "surveymonkey",
    name: "SurveyMonkey",
    provider: "SurveyMonkey Inc.",
    category: "Marketing & Ads",
    description: "SurveyMonkey is an online survey platform for creating, distributing, and analyzing surveys and questionnaires.",
    logo: "/integration-logos/surveymonkey.png",
    capabilities: [
      "CREATE SURVEY",
      "UPDATE SURVEY",
      "GET SURVEY",
      "LIST SURVEYS",
      "GET RESPONSES",
      "ANALYZE RESPONSES",
    ],
    iconColor: "bg-green-600",
  },
  {
    id: "typeform",
    name: "Typeform",
    provider: "Typeform SL",
    category: "Marketing & Ads",
    description: "Typeform is an online form and survey builder that creates interactive forms and surveys with a conversational interface.",
    logo: "/integration-logos/typeform.png",
    capabilities: [
      "CREATE FORM",
      "UPDATE FORM",
      "GET FORM",
      "LIST FORMS",
      "GET RESPONSES",
      "ANALYZE RESPONSES",
    ],
    iconColor: "bg-purple-600",
  },
  {
    id: "app-store-reviews",
    name: "App Store Reviews",
    provider: "Apple Inc.",
    category: "Marketing & Ads",
    description: "App Store Reviews API for accessing and managing app reviews and ratings on the Apple App Store.",
    capabilities: [
      "GET REVIEWS",
      "LIST REVIEWS",
      "GET RATINGS",
      "RESPOND TO REVIEW",
    ],
    iconColor: "bg-gray-900",
  },
  {
    id: "play-store-reviews",
    name: "Play Store Reviews",
    provider: "Google LLC",
    category: "Marketing & Ads",
    description: "Play Store Reviews API for accessing and managing app reviews and ratings on the Google Play Store.",
    capabilities: [
      "GET REVIEWS",
      "LIST REVIEWS",
      "GET RATINGS",
      "RESPOND TO REVIEW",
    ],
    iconColor: "bg-green-600",
  },

  // Automation, Workflow & Orchestration
  {
    id: "webhooks",
    name: "Webhooks",
    provider: "Webhook Services",
    category: "Automation & Workflow",
    description: "Webhook services for receiving real-time notifications and triggering actions based on events.",
    capabilities: [
      "CREATE WEBHOOK",
      "UPDATE WEBHOOK",
      "DELETE WEBHOOK",
      "GET WEBHOOK",
      "LIST WEBHOOKS",
      "TRIGGER WEBHOOK",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "ipaas-platforms",
    name: "iPaaS Platforms",
    provider: "Integration Platform Providers",
    category: "Automation & Workflow",
    description: "Integration Platform as a Service for connecting applications, data, and services through APIs and workflows.",
    capabilities: [
      "CREATE INTEGRATION",
      "UPDATE INTEGRATION",
      "GET INTEGRATION",
      "LIST INTEGRATIONS",
      "RUN WORKFLOW",
      "GET WORKFLOW STATUS",
    ],
    iconColor: "bg-indigo-600",
  },
  {
    id: "workflow-engines",
    name: "Workflow Engines",
    provider: "Workflow Platform Providers",
    category: "Automation & Workflow",
    description: "Workflow engines for designing, executing, and managing automated business processes and workflows.",
    capabilities: [
      "CREATE WORKFLOW",
      "UPDATE WORKFLOW",
      "GET WORKFLOW",
      "LIST WORKFLOWS",
      "EXECUTE WORKFLOW",
      "GET WORKFLOW STATUS",
    ],
    iconColor: "bg-purple-600",
  },
  {
    id: "orchestration-engines",
    name: "Orchestration Engines",
    provider: "Orchestration Platform Providers",
    category: "Automation & Workflow",
    description: "Orchestration engines for coordinating multiple services, APIs, and workflows in complex automation scenarios.",
    capabilities: [
      "ORCHESTRATE SERVICES",
      "COORDINATE WORKFLOWS",
      "MANAGE DEPENDENCIES",
      "GET STATUS",
      "HANDLE ERRORS",
    ],
    iconColor: "bg-teal-600",
  },
  {
    id: "approval-workflows",
    name: "Approval Workflows",
    provider: "Approval Platform Providers",
    category: "Automation & Workflow",
    description: "Approval workflow platforms for managing and automating approval processes and decision-making workflows.",
    capabilities: [
      "CREATE APPROVAL",
      "GET APPROVAL",
      "APPROVE REQUEST",
      "REJECT REQUEST",
      "GET APPROVAL STATUS",
      "LIST APPROVALS",
    ],
    iconColor: "bg-pink-600",
  },
  {
    id: "logging-tools",
    name: "Logging Tools",
    provider: "Logging Platform Providers",
    category: "Automation & Workflow",
    description: "Logging tools for collecting, storing, and analyzing application logs and system events.",
    capabilities: [
      "WRITE LOG",
      "GET LOGS",
      "SEARCH LOGS",
      "ANALYZE LOGS",
      "EXPORT LOGS",
    ],
    iconColor: "bg-gray-600",
  },
  {
    id: "monitoring-tools",
    name: "Monitoring Tools",
    provider: "Monitoring Platform Providers",
    category: "Automation & Workflow",
    description: "Monitoring tools for tracking system performance, availability, and health metrics.",
    capabilities: [
      "GET METRICS",
      "CREATE ALERT",
      "GET ALERTS",
      "GET STATUS",
      "TRACK PERFORMANCE",
    ],
    iconColor: "bg-red-600",
  },

  // Community & Collaboration
  {
    id: "slack-communities",
    name: "Slack Communities",
    provider: "Slack Technologies",
    category: "Community & Collaboration",
    description: "Slack communities for team collaboration, communication, and knowledge sharing.",
    logo: "/integration-logos/slack communities.png",
    capabilities: [
      "SEND MESSAGE",
      "GET MESSAGES",
      "CREATE CHANNEL",
      "GET CHANNELS",
      "MANAGE MEMBERS",
    ],
    iconColor: "bg-purple-500",
  },
  {
    id: "discord",
    name: "Discord",
    provider: "Discord Inc.",
    category: "Community & Collaboration",
    description: "Discord is a communication platform for creating communities, chatting, and voice/video calls.",
    logo: "/integration-logos/discord.png",
    capabilities: [
      "SEND MESSAGE",
      "GET MESSAGES",
      "CREATE CHANNEL",
      "GET CHANNELS",
      "MANAGE MEMBERS",
      "MANAGE ROLES",
    ],
    iconColor: "bg-indigo-600",
  },
  {
    id: "discourse",
    name: "Discourse",
    provider: "Discourse Project",
    category: "Community & Collaboration",
    description: "Discourse is an open-source discussion platform for building community forums and discussion boards.",
    logo: "/integration-logos/discourse.png",
    capabilities: [
      "CREATE TOPIC",
      "GET TOPIC",
      "LIST TOPICS",
      "ADD POST",
      "GET POSTS",
      "MANAGE USERS",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "khoros",
    name: "Khoros",
    provider: "Khoros LLC",
    category: "Community & Collaboration",
    description: "Khoros is a community engagement platform for building and managing online communities and customer engagement.",
    logo: "/integration-logos/khoros.png",
    capabilities: [
      "CREATE POST",
      "GET POST",
      "LIST POSTS",
      "MANAGE USERS",
      "MODERATE CONTENT",
    ],
    iconColor: "bg-green-600",
  },
  {
    id: "reddit",
    name: "Reddit",
    provider: "Reddit Inc.",
    category: "Community & Collaboration",
    description: "Reddit is a social news aggregation and discussion website where users can post content and engage in discussions.",
    logo: "/integration-logos/reddit.png",
    capabilities: [
      "GET POST",
      "LIST POSTS",
      "CREATE POST",
      "GET COMMENTS",
      "ADD COMMENT",
      "VOTE",
    ],
    iconColor: "bg-orange-600",
  },

  // Storage & File Handling
  {
    id: "file-storage",
    name: "File Storage Systems",
    provider: "File Storage Providers",
    category: "Storage & Files",
    description: "File storage systems for storing, retrieving, and managing files and documents in the cloud.",
    capabilities: [
      "UPLOAD FILE",
      "DOWNLOAD FILE",
      "DELETE FILE",
      "GET FILE",
      "LIST FILES",
      "MANAGE PERMISSIONS",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "image-storage",
    name: "Image Storage",
    provider: "Image Storage Providers",
    category: "Storage & Files",
    description: "Image storage services for storing, optimizing, and delivering images and media files.",
    capabilities: [
      "UPLOAD IMAGE",
      "GET IMAGE",
      "DELETE IMAGE",
      "OPTIMIZE IMAGE",
      "GENERATE THUMBNAIL",
    ],
    iconColor: "bg-pink-600",
  },
  {
    id: "document-upload",
    name: "Document Upload Tools",
    provider: "Document Upload Services",
    category: "Storage & Files",
    description: "Document upload tools for securely uploading, processing, and managing document files.",
    capabilities: [
      "UPLOAD DOCUMENT",
      "GET DOCUMENT",
      "PROCESS DOCUMENT",
      "EXTRACT TEXT",
      "DELETE DOCUMENT",
    ],
    iconColor: "bg-indigo-600",
  },
  {
    id: "storage-platforms",
    name: "Storage Platforms",
    provider: "Storage Service Providers",
    category: "Storage & Files",
    description: "Generic storage platforms for storing and managing data, files, and objects in the cloud.",
    capabilities: [
      "STORE DATA",
      "RETRIEVE DATA",
      "DELETE DATA",
      "LIST OBJECTS",
      "MANAGE BUCKETS",
    ],
    iconColor: "bg-gray-600",
  },

  // Miscellaneous / Supporting Tools
  {
    id: "google-sheets",
    name: "Google Sheets",
    provider: "Google LLC",
    category: "Miscellaneous",
    description: "Google Sheets is a web-based spreadsheet application for creating, editing, and collaborating on spreadsheets.",
    logo: "/integration-logos/google-sheets.png",
    capabilities: [
      "CREATE SPREADSHEET",
      "UPDATE SPREADSHEET",
      "GET SPREADSHEET",
      "READ CELLS",
      "WRITE CELLS",
      "GET RANGE",
      "UPDATE RANGE",
    ],
    iconColor: "bg-green-600",
  },
  {
    id: "excel",
    name: "Excel",
    provider: "Microsoft Corporation",
    category: "Miscellaneous",
    description: "Microsoft Excel is a spreadsheet application for creating, editing, and analyzing data in tabular format.",
    logo: "/integration-logos/excel.png",
    capabilities: [
      "READ CELLS",
      "WRITE CELLS",
      "GET RANGE",
      "UPDATE RANGE",
      "CREATE WORKSHEET",
      "GET WORKSHEET",
    ],
    iconColor: "bg-green-600",
  },
  {
    id: "forms",
    name: "Forms",
    provider: "Form Builders",
    category: "Miscellaneous",
    description: "Form builders for creating, distributing, and collecting data through online forms and surveys.",
    capabilities: [
      "CREATE FORM",
      "UPDATE FORM",
      "GET FORM",
      "LIST FORMS",
      "GET RESPONSES",
      "SUBMIT RESPONSE",
    ],
    iconColor: "bg-blue-600",
  },
  {
    id: "notification-systems",
    name: "Notification Systems",
    provider: "Notification Service Providers",
    category: "Miscellaneous",
    description: "Notification systems for sending alerts, updates, and messages across multiple channels.",
    capabilities: [
      "SEND NOTIFICATION",
      "SCHEDULE NOTIFICATION",
      "GET NOTIFICATION",
      "LIST NOTIFICATIONS",
      "TRACK DELIVERY",
    ],
    iconColor: "bg-orange-600",
  },
  {
    id: "alerts",
    name: "Alerts",
    provider: "Alert Service Providers",
    category: "Miscellaneous",
    description: "Alert services for sending real-time notifications and alerts based on events and conditions.",
    capabilities: [
      "CREATE ALERT",
      "GET ALERT",
      "LIST ALERTS",
      "TRIGGER ALERT",
      "MANAGE RULES",
    ],
    iconColor: "bg-red-600",
  },
  {
    id: "mobile-apps",
    name: "Mobile Apps",
    provider: "Mobile App Platforms",
    category: "Miscellaneous",
    description: "Mobile app platforms for building, deploying, and managing mobile applications.",
    capabilities: [
      "GET APP",
      "LIST APPS",
      "DEPLOY APP",
      "GET METRICS",
      "MANAGE VERSIONS",
    ],
    iconColor: "bg-indigo-600",
  },
  {
    id: "web-apps",
    name: "Web Apps",
    provider: "Web App Platforms",
    category: "Miscellaneous",
    description: "Web app platforms for building, deploying, and managing web applications and services.",
    capabilities: [
      "GET APP",
      "LIST APPS",
      "DEPLOY APP",
      "GET METRICS",
      "MANAGE CONFIG",
    ],
    iconColor: "bg-blue-600",
  },
]

// Helper function to get industries, functions, and use cases based on category
function getCategoryMetadata(category: string): { industries: string[]; functions: string[]; useCases: string[] } {
  const categoryMap: Record<string, { industries: string[]; functions: string[]; useCases: string[] }> = {
    "CRM & Sales": {
      industries: ["Technology", "Finance", "Retail", "E-Commerce", "Professional Services", "Healthcare", "Manufacturing"],
      functions: ["Sales", "Marketing"],
      useCases: ["Team Performance", "Team Productivity", "Technical Communication"],
    },
    "Email & Communication": {
      industries: ["Technology", "Professional Services", "Healthcare", "Education", "Government & Public Sector"],
      functions: ["Customer Support", "Sales", "Marketing", "HR", "IT", "Operations"],
      useCases: ["Team Development", "Team Productivity", "Technical Communication"],
    },
    "Document & Content": {
      industries: ["Technology", "Professional Services", "Education", "Healthcare", "Government & Public Sector"],
      functions: ["IT", "Operations", "HR"],
      useCases: ["Team Development", "Team Productivity", "Website Management"],
    },
    "Finance & Payments": {
      industries: ["Finance", "Retail", "E-Commerce", "Healthcare", "Government & Public Sector"],
      functions: ["Finance", "Operations"],
      useCases: ["Team Performance", "Time Optimization"],
    },
    "Analytics & BI": {
      industries: ["Technology", "Finance", "Retail", "E-Commerce", "Media & Entertainment", "Healthcare"],
      functions: ["Marketing", "Sales", "IT", "Operations"],
      useCases: ["Team Performance", "Team Productivity", "UX Design"],
    },
    "Search & SEO": {
      industries: ["Technology", "Retail", "E-Commerce", "Media & Entertainment", "Professional Services"],
      functions: ["Marketing", "IT"],
      useCases: ["Website Management", "Team Performance"],
    },
    "AI & ML": {
      industries: ["Technology", "Healthcare", "Finance", "Retail", "E-Commerce"],
      functions: ["IT", "Operations", "Marketing"],
      useCases: ["Team Development", "Team Performance", "UX Design"],
    },
    "HR & Talent": {
      industries: ["Technology", "Healthcare", "Finance", "Education", "Professional Services", "Government & Public Sector"],
      functions: ["HR", "Operations"],
      useCases: ["Team Development", "Team Performance", "Team Productivity"],
    },
    "IT & DevOps": {
      industries: ["Technology", "Finance", "Healthcare", "Government & Public Sector"],
      functions: ["IT", "Operations"],
      useCases: ["Team Development", "Technical Communication", "Team Productivity"],
    },
    "Identity & Security": {
      industries: ["Technology", "Finance", "Healthcare", "Government & Public Sector"],
      functions: ["IT", "Operations"],
      useCases: ["Team Development", "Technical Communication"],
    },
    "Retail & Commerce": {
      industries: ["Retail", "E-Commerce", "Hospitality & Tourism"],
      functions: ["Sales", "Marketing", "Operations"],
      useCases: ["Team Performance", "Website Management", "User Survey"],
    },
    "Healthcare": {
      industries: ["Healthcare"],
      functions: ["Operations"],
      useCases: ["Team Performance", "Team Productivity"],
    },
    "Legal & Compliance": {
      industries: ["Finance", "Healthcare", "Government & Public Sector", "Professional Services"],
      functions: ["Operations", "Finance"],
      useCases: ["Team Performance"],
    },
    "Customer Support": {
      industries: ["Technology", "Retail", "E-Commerce", "Healthcare", "Telecommunications"],
      functions: ["Customer Support"],
      useCases: ["Ticket Management", "Team Productivity", "Technical Communication"],
    },
    "Marketing & Ads": {
      industries: ["Technology", "Retail", "E-Commerce", "Media & Entertainment", "Professional Services"],
      functions: ["Marketing"],
      useCases: ["Team Performance", "User Survey", "Website Management"],
    },
    "Automation & Workflow": {
      industries: ["Technology", "Finance", "Healthcare", "Manufacturing"],
      functions: ["IT", "Operations"],
      useCases: ["Team Development", "Team Productivity", "Time Optimization"],
    },
    "Community & Collaboration": {
      industries: ["Technology", "Education", "Media & Entertainment"],
      functions: ["Marketing", "Customer Support"],
      useCases: ["Team Development", "Technical Communication"],
    },
    "Storage & Files": {
      industries: ["Technology", "Professional Services", "Education", "Healthcare"],
      functions: ["IT", "Operations"],
      useCases: ["Team Development", "Team Productivity"],
    },
    "Miscellaneous": {
      industries: ["Technology", "Professional Services", "Education"],
      functions: ["IT", "Operations", "Marketing"],
      useCases: ["Team Development", "Team Productivity", "Website Management"],
    },
  }

  return categoryMap[category] || {
    industries: ["Technology"],
    functions: ["Operations"],
    useCases: ["Team Productivity"],
  }
}

// Enrich integrations with metadata
export const integrations: Integration[] = baseIntegrations.map((integration) => {
  const metadata = getCategoryMetadata(integration.category)
  return {
    ...integration,
    industries: integration.industries || metadata.industries,
    functions: integration.functions || metadata.functions,
    useCases: integration.useCases || metadata.useCases,
  }
})

export function getIntegrationById(id: string): Integration | undefined {
  return integrations.find((integration) => integration.id === id)
}

export function getIntegrationsByCategory(category: string): Integration[] {
  return integrations.filter((integration) => integration.category === category)
}

// Helper function to get logo path for an integration
// Falls back to generated path if logo field is not set
export function getIntegrationLogoPath(integration: Integration): string | null {
  // If logo is explicitly set, use it
  if (integration.logo) {
    return integration.logo
  }
  
  // Generate path from integration ID
  const slug = integration.id.toLowerCase().replace(/\s+/g, '-')
  return `/integration-logos/${slug}.png`
}

export const categories = Array.from(new Set(integrations.map((i) => i.category))).sort()
